// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: api_keys.sql

package db

import (
	"context"
	"time"
)

const createAPIKey = `-- name: CreateAPIKey :one
INSERT INTO api_keys (org_id, user_id, name, key_hash, scopes)
VALUES ($1, $2, $3, $4, $5) RETURNING id
`

type CreateAPIKeyParams struct {
	OrgID   string   `json:"org_id"`
	UserID  *string  `json:"user_id"`
	Name    string   `json:"name"`
	KeyHash string   `json:"key_hash"`
	Scopes  []string `json:"scopes"`
}

func (q *Queries) CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) (string, error) {
	row := q.db.QueryRow(ctx, createAPIKey,
		arg.OrgID,
		arg.UserID,
		arg.Name,
		arg.KeyHash,
		arg.Scopes,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}

const deleteAPIKey = `-- name: DeleteAPIKey :execrows
DELETE FROM api_keys WHERE id = $1
`

func (q *Queries) DeleteAPIKey(ctx context.Context, id string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAPIKey, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listAPIKeys = `-- name: ListAPIKeys :many
SELECT id, name, scopes, expires_at, last_used_at, created_at
FROM api_keys WHERE org_id = $1 ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListAPIKeysParams struct {
	OrgID  string `json:"org_id"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

type ListAPIKeysRow struct {
	ID         string     `json:"id"`
	Name       string     `json:"name"`
	Scopes     []string   `json:"scopes"`
	ExpiresAt  *time.Time `json:"expires_at"`
	LastUsedAt *time.Time `json:"last_used_at"`
	CreatedAt  time.Time  `json:"created_at"`
}

func (q *Queries) ListAPIKeys(ctx context.Context, arg ListAPIKeysParams) ([]ListAPIKeysRow, error) {
	rows, err := q.db.Query(ctx, listAPIKeys, arg.OrgID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAPIKeysRow{}
	for rows.Next() {
		var i ListAPIKeysRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Scopes,
			&i.ExpiresAt,
			&i.LastUsedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAPIKeysDetailed = `-- name: ListAPIKeysDetailed :many
SELECT ak.id, ak.name, COALESCE(r.slug, 'viewer')::text AS role,
       COALESCE(u.email, 'system')::text AS created_by,
       ak.expires_at, ak.last_used_at, ak.created_at
FROM api_keys ak
LEFT JOIN roles r ON r.id = ak.role_id
LEFT JOIN users u ON u.id = ak.user_id
WHERE ak.org_id = $1 ORDER BY ak.created_at DESC LIMIT $2 OFFSET $3
`

type ListAPIKeysDetailedParams struct {
	OrgID  string `json:"org_id"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

type ListAPIKeysDetailedRow struct {
	ID         string     `json:"id"`
	Name       string     `json:"name"`
	Role       string     `json:"role"`
	CreatedBy  string     `json:"created_by"`
	ExpiresAt  *time.Time `json:"expires_at"`
	LastUsedAt *time.Time `json:"last_used_at"`
	CreatedAt  time.Time  `json:"created_at"`
}

// API keys with role slug + creator email for the settings list.
func (q *Queries) ListAPIKeysDetailed(ctx context.Context, arg ListAPIKeysDetailedParams) ([]ListAPIKeysDetailedRow, error) {
	rows, err := q.db.Query(ctx, listAPIKeysDetailed, arg.OrgID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAPIKeysDetailedRow{}
	for rows.Next() {
		var i ListAPIKeysDetailedRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Role,
			&i.CreatedBy,
			&i.ExpiresAt,
			&i.LastUsedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listValidAPIKeys = `-- name: ListValidAPIKeys :many
SELECT id, org_id, user_id, name, key_hash, scopes
FROM api_keys WHERE (expires_at IS NULL OR expires_at > now())
`

type ListValidAPIKeysRow struct {
	ID      string   `json:"id"`
	OrgID   string   `json:"org_id"`
	UserID  *string  `json:"user_id"`
	Name    string   `json:"name"`
	KeyHash string   `json:"key_hash"`
	Scopes  []string `json:"scopes"`
}

func (q *Queries) ListValidAPIKeys(ctx context.Context) ([]ListValidAPIKeysRow, error) {
	rows, err := q.db.Query(ctx, listValidAPIKeys)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListValidAPIKeysRow{}
	for rows.Next() {
		var i ListValidAPIKeysRow
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.UserID,
			&i.Name,
			&i.KeyHash,
			&i.Scopes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const touchAPIKey = `-- name: TouchAPIKey :exec
UPDATE api_keys SET last_used_at = now() WHERE id = $1
`

func (q *Queries) TouchAPIKey(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, touchAPIKey, id)
	return err
}
