// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth_stores.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimCompletedDeviceCode = `-- name: ClaimCompletedDeviceCode :one
DELETE FROM device_codes WHERE device_code = $1 AND completed = true
RETURNING access_token, refresh_token
`

type ClaimCompletedDeviceCodeRow struct {
	AccessToken  *string `json:"access_token"`
	RefreshToken *string `json:"refresh_token"`
}

// Atomic claim: return the tokens and delete the row in one statement, only if
// completed. This is the TOCTOU fix — no read-then-mutate window.
func (q *Queries) ClaimCompletedDeviceCode(ctx context.Context, deviceCode string) (ClaimCompletedDeviceCodeRow, error) {
	row := q.db.QueryRow(ctx, claimCompletedDeviceCode, deviceCode)
	var i ClaimCompletedDeviceCodeRow
	err := row.Scan(&i.AccessToken, &i.RefreshToken)
	return i, err
}

const completeDeviceCode = `-- name: CompleteDeviceCode :exec
UPDATE device_codes
SET completed = true, access_token = $2, refresh_token = $3, user_id = $4
WHERE device_code = $1
`

type CompleteDeviceCodeParams struct {
	DeviceCode   string  `json:"device_code"`
	AccessToken  *string `json:"access_token"`
	RefreshToken *string `json:"refresh_token"`
	UserID       *string `json:"user_id"`
}

func (q *Queries) CompleteDeviceCode(ctx context.Context, arg CompleteDeviceCodeParams) error {
	_, err := q.db.Exec(ctx, completeDeviceCode,
		arg.DeviceCode,
		arg.AccessToken,
		arg.RefreshToken,
		arg.UserID,
	)
	return err
}

const deleteDeviceCode = `-- name: DeleteDeviceCode :exec
DELETE FROM device_codes WHERE device_code = $1
`

func (q *Queries) DeleteDeviceCode(ctx context.Context, deviceCode string) error {
	_, err := q.db.Exec(ctx, deleteDeviceCode, deviceCode)
	return err
}

const deleteExpiredDeviceCodes = `-- name: DeleteExpiredDeviceCodes :exec
DELETE FROM device_codes WHERE expires_at < now()
`

func (q *Queries) DeleteExpiredDeviceCodes(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredDeviceCodes)
	return err
}

const deleteExpiredMFAPendingTokens = `-- name: DeleteExpiredMFAPendingTokens :exec
DELETE FROM mfa_pending_tokens WHERE expires_at < now()
`

func (q *Queries) DeleteExpiredMFAPendingTokens(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredMFAPendingTokens)
	return err
}

const deleteExpiredSAMLAssertions = `-- name: DeleteExpiredSAMLAssertions :exec
DELETE FROM saml_used_assertions WHERE expires_at < now()
`

func (q *Queries) DeleteExpiredSAMLAssertions(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredSAMLAssertions)
	return err
}

const deleteMFAPendingToken = `-- name: DeleteMFAPendingToken :exec
DELETE FROM mfa_pending_tokens WHERE token = $1
`

func (q *Queries) DeleteMFAPendingToken(ctx context.Context, token string) error {
	_, err := q.db.Exec(ctx, deleteMFAPendingToken, token)
	return err
}

const findDeviceCodeByOAuthState = `-- name: FindDeviceCodeByOAuthState :one
SELECT device_code FROM device_codes
WHERE oauth_state = $1 AND expires_at > now()
LIMIT 1
`

func (q *Queries) FindDeviceCodeByOAuthState(ctx context.Context, oauthState *string) (string, error) {
	row := q.db.QueryRow(ctx, findDeviceCodeByOAuthState, oauthState)
	var device_code string
	err := row.Scan(&device_code)
	return device_code, err
}

const findDeviceCodeByUserCode = `-- name: FindDeviceCodeByUserCode :one
SELECT device_code FROM device_codes
WHERE user_code = $1 AND NOT completed AND expires_at > now()
LIMIT 1
`

func (q *Queries) FindDeviceCodeByUserCode(ctx context.Context, userCode string) (string, error) {
	row := q.db.QueryRow(ctx, findDeviceCodeByUserCode, userCode)
	var device_code string
	err := row.Scan(&device_code)
	return device_code, err
}

const getDeviceCode = `-- name: GetDeviceCode :one
SELECT completed, expires_at, last_polled_at, interval_secs
FROM device_codes WHERE device_code = $1
`

type GetDeviceCodeRow struct {
	Completed    bool       `json:"completed"`
	ExpiresAt    time.Time  `json:"expires_at"`
	LastPolledAt *time.Time `json:"last_polled_at"`
	IntervalSecs int32      `json:"interval_secs"`
}

func (q *Queries) GetDeviceCode(ctx context.Context, deviceCode string) (GetDeviceCodeRow, error) {
	row := q.db.QueryRow(ctx, getDeviceCode, deviceCode)
	var i GetDeviceCodeRow
	err := row.Scan(
		&i.Completed,
		&i.ExpiresAt,
		&i.LastPolledAt,
		&i.IntervalSecs,
	)
	return i, err
}

const getDeviceCodeCodeVerifier = `-- name: GetDeviceCodeCodeVerifier :one
SELECT code_verifier FROM device_codes WHERE device_code = $1
`

func (q *Queries) GetDeviceCodeCodeVerifier(ctx context.Context, deviceCode string) (*string, error) {
	row := q.db.QueryRow(ctx, getDeviceCodeCodeVerifier, deviceCode)
	var code_verifier *string
	err := row.Scan(&code_verifier)
	return code_verifier, err
}

const getDeviceCodeNonce = `-- name: GetDeviceCodeNonce :one
SELECT nonce FROM device_codes WHERE device_code = $1
`

func (q *Queries) GetDeviceCodeNonce(ctx context.Context, deviceCode string) (*string, error) {
	row := q.db.QueryRow(ctx, getDeviceCodeNonce, deviceCode)
	var nonce *string
	err := row.Scan(&nonce)
	return nonce, err
}

const getDeviceCodeRefreshToken = `-- name: GetDeviceCodeRefreshToken :one
SELECT refresh_token FROM device_codes WHERE device_code = $1
`

func (q *Queries) GetDeviceCodeRefreshToken(ctx context.Context, deviceCode string) (*string, error) {
	row := q.db.QueryRow(ctx, getDeviceCodeRefreshToken, deviceCode)
	var refresh_token *string
	err := row.Scan(&refresh_token)
	return refresh_token, err
}

const getDeviceCodeSAMLRequestID = `-- name: GetDeviceCodeSAMLRequestID :one
SELECT saml_request_id FROM device_codes WHERE device_code = $1
`

func (q *Queries) GetDeviceCodeSAMLRequestID(ctx context.Context, deviceCode string) (*string, error) {
	row := q.db.QueryRow(ctx, getDeviceCodeSAMLRequestID, deviceCode)
	var saml_request_id *string
	err := row.Scan(&saml_request_id)
	return saml_request_id, err
}

const getMFAPendingToken = `-- name: GetMFAPendingToken :one
SELECT user_id, email, org_id, attempts, purpose FROM mfa_pending_tokens
WHERE token = $1 AND expires_at > now()
`

type GetMFAPendingTokenRow struct {
	UserID   string `json:"user_id"`
	Email    string `json:"email"`
	OrgID    string `json:"org_id"`
	Attempts int32  `json:"attempts"`
	Purpose  string `json:"purpose"`
}

func (q *Queries) GetMFAPendingToken(ctx context.Context, token string) (GetMFAPendingTokenRow, error) {
	row := q.db.QueryRow(ctx, getMFAPendingToken, token)
	var i GetMFAPendingTokenRow
	err := row.Scan(
		&i.UserID,
		&i.Email,
		&i.OrgID,
		&i.Attempts,
		&i.Purpose,
	)
	return i, err
}

const insertDeviceCode = `-- name: InsertDeviceCode :exec

INSERT INTO device_codes (device_code, user_code, expires_at, interval_secs)
VALUES ($1, $2, $3, $4)
`

type InsertDeviceCodeParams struct {
	DeviceCode   string    `json:"device_code"`
	UserCode     string    `json:"user_code"`
	ExpiresAt    time.Time `json:"expires_at"`
	IntervalSecs int32     `json:"interval_secs"`
}

// Device authorization flow (DB-backed; replaces the in-memory map).
func (q *Queries) InsertDeviceCode(ctx context.Context, arg InsertDeviceCodeParams) error {
	_, err := q.db.Exec(ctx, insertDeviceCode,
		arg.DeviceCode,
		arg.UserCode,
		arg.ExpiresAt,
		arg.IntervalSecs,
	)
	return err
}

const insertMFAPendingToken = `-- name: InsertMFAPendingToken :exec

INSERT INTO mfa_pending_tokens (token, user_id, email, org_id, expires_at, purpose)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertMFAPendingTokenParams struct {
	Token     string    `json:"token"`
	UserID    string    `json:"user_id"`
	Email     string    `json:"email"`
	OrgID     string    `json:"org_id"`
	ExpiresAt time.Time `json:"expires_at"`
	Purpose   string    `json:"purpose"`
}

// MFA pending tokens (DB-backed; replaces the in-memory map).
func (q *Queries) InsertMFAPendingToken(ctx context.Context, arg InsertMFAPendingTokenParams) error {
	_, err := q.db.Exec(ctx, insertMFAPendingToken,
		arg.Token,
		arg.UserID,
		arg.Email,
		arg.OrgID,
		arg.ExpiresAt,
		arg.Purpose,
	)
	return err
}

const markSAMLAssertionUsed = `-- name: MarkSAMLAssertionUsed :execrows
INSERT INTO saml_used_assertions (assertion_id, expires_at)
VALUES ($1, $2) ON CONFLICT (assertion_id) DO NOTHING
`

type MarkSAMLAssertionUsedParams struct {
	AssertionID string    `json:"assertion_id"`
	ExpiresAt   time.Time `json:"expires_at"`
}

// One-time-use guard: succeeds (1 row) the first time an assertion ID is seen,
// and returns 0 rows on replay. Bounded by the assertion's own validity window.
func (q *Queries) MarkSAMLAssertionUsed(ctx context.Context, arg MarkSAMLAssertionUsedParams) (int64, error) {
	result, err := q.db.Exec(ctx, markSAMLAssertionUsed, arg.AssertionID, arg.ExpiresAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const recordMFAAttemptFailure = `-- name: RecordMFAAttemptFailure :one
UPDATE mfa_pending_tokens SET attempts = attempts + 1
WHERE token = $1
RETURNING attempts
`

// Count a failed second-factor guess and report the running total, so the
// caller can retire the token once guessing has clearly started. Atomic, so
// concurrent guesses cannot each read a stale count.
func (q *Queries) RecordMFAAttemptFailure(ctx context.Context, token string) (int32, error) {
	row := q.db.QueryRow(ctx, recordMFAAttemptFailure, token)
	var attempts int32
	err := row.Scan(&attempts)
	return attempts, err
}

const recordTOTPUse = `-- name: RecordTOTPUse :one

UPDATE users SET mfa_last_used_period = $2
WHERE id = $1 AND (mfa_last_used_period IS NULL OR mfa_last_used_period < $2)
RETURNING id
`

type RecordTOTPUseParams struct {
	ID                string      `json:"id"`
	MfaLastUsedPeriod pgtype.Int8 `json:"mfa_last_used_period"`
}

// TOTP replay protection.
// Advance the user's last-used TOTP period atomically. Returns a row only when
// the new period is strictly greater than the stored one; no row means the code
// was already used (replay) and must be rejected.
func (q *Queries) RecordTOTPUse(ctx context.Context, arg RecordTOTPUseParams) (string, error) {
	row := q.db.QueryRow(ctx, recordTOTPUse, arg.ID, arg.MfaLastUsedPeriod)
	var id string
	err := row.Scan(&id)
	return id, err
}

const setDeviceCodeOAuthState = `-- name: SetDeviceCodeOAuthState :exec
UPDATE device_codes SET oauth_state = $2, nonce = $3, code_verifier = $4 WHERE device_code = $1
`

type SetDeviceCodeOAuthStateParams struct {
	DeviceCode   string  `json:"device_code"`
	OauthState   *string `json:"oauth_state"`
	Nonce        *string `json:"nonce"`
	CodeVerifier *string `json:"code_verifier"`
}

func (q *Queries) SetDeviceCodeOAuthState(ctx context.Context, arg SetDeviceCodeOAuthStateParams) error {
	_, err := q.db.Exec(ctx, setDeviceCodeOAuthState,
		arg.DeviceCode,
		arg.OauthState,
		arg.Nonce,
		arg.CodeVerifier,
	)
	return err
}

const setDeviceCodeSAMLRequestID = `-- name: SetDeviceCodeSAMLRequestID :exec
UPDATE device_codes SET saml_request_id = $2 WHERE device_code = $1
`

type SetDeviceCodeSAMLRequestIDParams struct {
	DeviceCode    string  `json:"device_code"`
	SamlRequestID *string `json:"saml_request_id"`
}

func (q *Queries) SetDeviceCodeSAMLRequestID(ctx context.Context, arg SetDeviceCodeSAMLRequestIDParams) error {
	_, err := q.db.Exec(ctx, setDeviceCodeSAMLRequestID, arg.DeviceCode, arg.SamlRequestID)
	return err
}

const touchDeviceCodePoll = `-- name: TouchDeviceCodePoll :exec
UPDATE device_codes SET last_polled_at = now() WHERE device_code = $1
`

func (q *Queries) TouchDeviceCodePoll(ctx context.Context, deviceCode string) error {
	_, err := q.db.Exec(ctx, touchDeviceCodePoll, deviceCode)
	return err
}
