// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth_provider_config.sql

package db

import (
	"context"
)

const deleteAuthProviderConfig = `-- name: DeleteAuthProviderConfig :execrows
DELETE FROM auth_provider_config WHERE provider_type = $1
`

func (q *Queries) DeleteAuthProviderConfig(ctx context.Context, providerType string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAuthProviderConfig, providerType)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getAuthProviderConfig = `-- name: GetAuthProviderConfig :one
SELECT id, provider_type, display_name, config_enc, created_at, updated_at
FROM auth_provider_config WHERE provider_type = $1
`

func (q *Queries) GetAuthProviderConfig(ctx context.Context, providerType string) (AuthProviderConfig, error) {
	row := q.db.QueryRow(ctx, getAuthProviderConfig, providerType)
	var i AuthProviderConfig
	err := row.Scan(
		&i.ID,
		&i.ProviderType,
		&i.DisplayName,
		&i.ConfigEnc,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAuthProviderConfigNames = `-- name: ListAuthProviderConfigNames :many
SELECT id, display_name, provider_type FROM auth_provider_config
`

type ListAuthProviderConfigNamesRow struct {
	ID           string `json:"id"`
	DisplayName  string `json:"display_name"`
	ProviderType string `json:"provider_type"`
}

func (q *Queries) ListAuthProviderConfigNames(ctx context.Context) ([]ListAuthProviderConfigNamesRow, error) {
	rows, err := q.db.Query(ctx, listAuthProviderConfigNames)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAuthProviderConfigNamesRow{}
	for rows.Next() {
		var i ListAuthProviderConfigNamesRow
		if err := rows.Scan(&i.ID, &i.DisplayName, &i.ProviderType); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertAuthProviderConfig = `-- name: UpsertAuthProviderConfig :one
INSERT INTO auth_provider_config (provider_type, display_name, config_enc)
VALUES ($1, $2, $3)
ON CONFLICT (provider_type) DO UPDATE SET
    display_name = EXCLUDED.display_name,
    config_enc = EXCLUDED.config_enc,
    updated_at = now()
RETURNING id
`

type UpsertAuthProviderConfigParams struct {
	ProviderType string `json:"provider_type"`
	DisplayName  string `json:"display_name"`
	ConfigEnc    []byte `json:"config_enc"`
}

func (q *Queries) UpsertAuthProviderConfig(ctx context.Context, arg UpsertAuthProviderConfigParams) (string, error) {
	row := q.db.QueryRow(ctx, upsertAuthProviderConfig, arg.ProviderType, arg.DisplayName, arg.ConfigEnc)
	var id string
	err := row.Scan(&id)
	return id, err
}
