// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: compute_providers.sql

package db

import (
	"context"
)

const deleteComputeProvider = `-- name: DeleteComputeProvider :exec
DELETE FROM compute_providers WHERE id = $1
`

func (q *Queries) DeleteComputeProvider(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteComputeProvider, id)
	return err
}

const getComputeProvider = `-- name: GetComputeProvider :one
SELECT id, name, provider_type, config, credentials_enc, created_at, updated_at FROM compute_providers WHERE name = $1
`

func (q *Queries) GetComputeProvider(ctx context.Context, name string) (ComputeProvider, error) {
	row := q.db.QueryRow(ctx, getComputeProvider, name)
	var i ComputeProvider
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ProviderType,
		&i.Config,
		&i.CredentialsEnc,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listComputeProviders = `-- name: ListComputeProviders :many
SELECT id, name, provider_type, config, credentials_enc, created_at, updated_at FROM compute_providers ORDER BY name
`

func (q *Queries) ListComputeProviders(ctx context.Context) ([]ComputeProvider, error) {
	rows, err := q.db.Query(ctx, listComputeProviders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ComputeProvider{}
	for rows.Next() {
		var i ComputeProvider
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ProviderType,
			&i.Config,
			&i.CredentialsEnc,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertComputeProvider = `-- name: UpsertComputeProvider :one
INSERT INTO compute_providers (name, provider_type, config, credentials_enc)
VALUES ($1, $2, $3, $4)
ON CONFLICT (name) DO UPDATE SET
    provider_type = EXCLUDED.provider_type,
    config = EXCLUDED.config,
    credentials_enc = COALESCE(EXCLUDED.credentials_enc, compute_providers.credentials_enc),
    updated_at = now()
RETURNING id
`

type UpsertComputeProviderParams struct {
	Name           string `json:"name"`
	ProviderType   string `json:"provider_type"`
	Config         []byte `json:"config"`
	CredentialsEnc []byte `json:"credentials_enc"`
}

// Also the config-file bootstrap path: a providers: block in config upserts by
// name at startup so IaC/first-boot installs stay one-file; DB is source of truth.
func (q *Queries) UpsertComputeProvider(ctx context.Context, arg UpsertComputeProviderParams) (string, error) {
	row := q.db.QueryRow(ctx, upsertComputeProvider,
		arg.Name,
		arg.ProviderType,
		arg.Config,
		arg.CredentialsEnc,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}
