// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: engine_events.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const cleanupOldEngineEvents = `-- name: CleanupOldEngineEvents :exec
DELETE FROM engine_events WHERE id IN (
    SELECT id FROM engine_events
    WHERE created_at < now() - interval '30 days'
    LIMIT 5000
)
`

// Prune transition history older than 30 days so the table stays bounded.
// Batched (one batch per sweep) so a long-lived install's backlog can't stall
// a sweep tick with one giant DELETE.
func (q *Queries) CleanupOldEngineEvents(ctx context.Context) error {
	_, err := q.db.Exec(ctx, cleanupOldEngineEvents)
	return err
}

const insertEngineEvent = `-- name: InsertEngineEvent :exec
INSERT INTO engine_events (
    workflow_id, step_name, attempt, event_type,
    from_status, to_status, actor, reason, metadata
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type InsertEngineEventParams struct {
	WorkflowID string      `json:"workflow_id"`
	StepName   *string     `json:"step_name"`
	Attempt    pgtype.Int4 `json:"attempt"`
	EventType  string      `json:"event_type"`
	FromStatus *string     `json:"from_status"`
	ToStatus   *string     `json:"to_status"`
	Actor      string      `json:"actor"`
	Reason     *string     `json:"reason"`
	Metadata   []byte      `json:"metadata"`
}

// Append one transition to the durable history log. Written in the same tx as the
// state change it records (see internal/core/engine/transition.go). Append-only:
// rows are never updated.
func (q *Queries) InsertEngineEvent(ctx context.Context, arg InsertEngineEventParams) error {
	_, err := q.db.Exec(ctx, insertEngineEvent,
		arg.WorkflowID,
		arg.StepName,
		arg.Attempt,
		arg.EventType,
		arg.FromStatus,
		arg.ToStatus,
		arg.Actor,
		arg.Reason,
		arg.Metadata,
	)
	return err
}

const listEngineEventsByStep = `-- name: ListEngineEventsByStep :many
SELECT id, workflow_id, step_name, attempt, event_type,
    from_status, to_status, actor, reason, metadata, created_at
FROM engine_events
WHERE workflow_id = $1 AND step_name = $2
ORDER BY created_at ASC, id ASC
`

type ListEngineEventsByStepParams struct {
	WorkflowID string  `json:"workflow_id"`
	StepName   *string `json:"step_name"`
}

// Transition history for a single step across all attempts.
func (q *Queries) ListEngineEventsByStep(ctx context.Context, arg ListEngineEventsByStepParams) ([]EngineEvent, error) {
	rows, err := q.db.Query(ctx, listEngineEventsByStep, arg.WorkflowID, arg.StepName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EngineEvent{}
	for rows.Next() {
		var i EngineEvent
		if err := rows.Scan(
			&i.ID,
			&i.WorkflowID,
			&i.StepName,
			&i.Attempt,
			&i.EventType,
			&i.FromStatus,
			&i.ToStatus,
			&i.Actor,
			&i.Reason,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEngineEventsByWorkflow = `-- name: ListEngineEventsByWorkflow :many
SELECT id, workflow_id, step_name, attempt, event_type,
    from_status, to_status, actor, reason, metadata, created_at
FROM engine_events
WHERE workflow_id = $1
ORDER BY created_at ASC, id ASC
`

// Full transition timeline for a workflow (run), oldest first. Powers the run
// timeline / step history UI.
func (q *Queries) ListEngineEventsByWorkflow(ctx context.Context, workflowID string) ([]EngineEvent, error) {
	rows, err := q.db.Query(ctx, listEngineEventsByWorkflow, workflowID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EngineEvent{}
	for rows.Next() {
		var i EngineEvent
		if err := rows.Scan(
			&i.ID,
			&i.WorkflowID,
			&i.StepName,
			&i.Attempt,
			&i.EventType,
			&i.FromStatus,
			&i.ToStatus,
			&i.Actor,
			&i.Reason,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
