// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: fleet_decisions.sql

package db

import (
	"context"
	"time"
)

const cleanupOldFleetDecisions = `-- name: CleanupOldFleetDecisions :exec
DELETE FROM fleet_decisions WHERE id IN (
    SELECT id FROM fleet_decisions
    WHERE created_at < now() - interval '90 days'
    LIMIT 2000
)
`

// The economics ledger is retained long (90 days) so decisions stay auditable,
// but not forever. Batched, like the other retention sweeps.
func (q *Queries) CleanupOldFleetDecisions(ctx context.Context) error {
	_, err := q.db.Exec(ctx, cleanupOldFleetDecisions)
	return err
}

const insertFleetDecision = `-- name: InsertFleetDecision :one
INSERT INTO fleet_decisions (pool_id, machine_id, decision_type, inputs, chosen, alternatives)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id
`

type InsertFleetDecisionParams struct {
	PoolID       *string `json:"pool_id"`
	MachineID    *string `json:"machine_id"`
	DecisionType string  `json:"decision_type"`
	Inputs       []byte  `json:"inputs"`
	Chosen       []byte  `json:"chosen"`
	Alternatives []byte  `json:"alternatives"`
}

// Written in the same tx as the action it records (e.g. the machines insert for a
// provision decision) so ledger and state can never disagree.
func (q *Queries) InsertFleetDecision(ctx context.Context, arg InsertFleetDecisionParams) (string, error) {
	row := q.db.QueryRow(ctx, insertFleetDecision,
		arg.PoolID,
		arg.MachineID,
		arg.DecisionType,
		arg.Inputs,
		arg.Chosen,
		arg.Alternatives,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}

const lastNoCapacityDecision = `-- name: LastNoCapacityDecision :one
SELECT created_at FROM fleet_decisions
WHERE pool_id = $1 AND decision_type = 'no_capacity'
ORDER BY created_at DESC LIMIT 1
`

// Debounce input: no_capacity is recorded at most once per pool per window.
func (q *Queries) LastNoCapacityDecision(ctx context.Context, poolID *string) (time.Time, error) {
	row := q.db.QueryRow(ctx, lastNoCapacityDecision, poolID)
	var created_at time.Time
	err := row.Scan(&created_at)
	return created_at, err
}

const listFleetDecisions = `-- name: ListFleetDecisions :many
SELECT id, pool_id, machine_id, decision_type, inputs, chosen, alternatives, outcome, outcome_metadata, outcome_at, created_at FROM fleet_decisions
WHERE ($3::uuid IS NULL OR pool_id = $3)
  AND ($4::text IS NULL OR decision_type = $4)
ORDER BY created_at DESC LIMIT $1 OFFSET $2
`

type ListFleetDecisionsParams struct {
	Limit        int32   `json:"limit"`
	Offset       int32   `json:"offset"`
	PoolID       *string `json:"pool_id"`
	DecisionType *string `json:"decision_type"`
}

func (q *Queries) ListFleetDecisions(ctx context.Context, arg ListFleetDecisionsParams) ([]FleetDecision, error) {
	rows, err := q.db.Query(ctx, listFleetDecisions,
		arg.Limit,
		arg.Offset,
		arg.PoolID,
		arg.DecisionType,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FleetDecision{}
	for rows.Next() {
		var i FleetDecision
		if err := rows.Scan(
			&i.ID,
			&i.PoolID,
			&i.MachineID,
			&i.DecisionType,
			&i.Inputs,
			&i.Chosen,
			&i.Alternatives,
			&i.Outcome,
			&i.OutcomeMetadata,
			&i.OutcomeAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resolveFleetDecisionByMachine = `-- name: ResolveFleetDecisionByMachine :exec
UPDATE fleet_decisions SET
    outcome = $1, outcome_metadata = $2, outcome_at = now()
WHERE machine_id = $3 AND decision_type = $4 AND outcome IS NULL
`

type ResolveFleetDecisionByMachineParams struct {
	Outcome         *string `json:"outcome"`
	OutcomeMetadata []byte  `json:"outcome_metadata"`
	MachineID       *string `json:"machine_id"`
	DecisionType    string  `json:"decision_type"`
}

// Backfills the outcome once known (boot_ok + boot seconds at registration,
// boot_timeout from the sweep, terminated from scale-down/reconcile).
func (q *Queries) ResolveFleetDecisionByMachine(ctx context.Context, arg ResolveFleetDecisionByMachineParams) error {
	_, err := q.db.Exec(ctx, resolveFleetDecisionByMachine,
		arg.Outcome,
		arg.OutcomeMetadata,
		arg.MachineID,
		arg.DecisionType,
	)
	return err
}
