// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: login_attempts.sql

package db

import (
	"context"
	"net/netip"
)

const cleanupOldLoginAttempts = `-- name: CleanupOldLoginAttempts :exec
DELETE FROM login_attempts WHERE created_at < now() - interval '24 hours'
`

func (q *Queries) CleanupOldLoginAttempts(ctx context.Context) error {
	_, err := q.db.Exec(ctx, cleanupOldLoginAttempts)
	return err
}

const countRecentFailuresByEmail = `-- name: CountRecentFailuresByEmail :one
SELECT COUNT(*) FROM login_attempts
WHERE email = $1 AND success = false
  AND created_at > now() - interval '15 minutes'
`

func (q *Queries) CountRecentFailuresByEmail(ctx context.Context, email string) (int64, error) {
	row := q.db.QueryRow(ctx, countRecentFailuresByEmail, email)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countRecentFailuresByIP = `-- name: CountRecentFailuresByIP :one
SELECT COUNT(*) FROM login_attempts
WHERE ip_address = $1::inet AND success = false
  AND created_at > now() - interval '15 minutes'
`

func (q *Queries) CountRecentFailuresByIP(ctx context.Context, ipAddress netip.Addr) (int64, error) {
	row := q.db.QueryRow(ctx, countRecentFailuresByIP, ipAddress)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const recordLoginAttempt = `-- name: RecordLoginAttempt :exec
INSERT INTO login_attempts (email, ip_address, success)
VALUES ($1, $2::inet, $3)
`

type RecordLoginAttemptParams struct {
	Email     string     `json:"email"`
	IpAddress netip.Addr `json:"ip_address"`
	Success   bool       `json:"success"`
}

func (q *Queries) RecordLoginAttempt(ctx context.Context, arg RecordLoginAttemptParams) error {
	_, err := q.db.Exec(ctx, recordLoginAttempt, arg.Email, arg.IpAddress, arg.Success)
	return err
}
