// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: machines.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimExpiredBootDeadlines = `-- name: ClaimExpiredBootDeadlines :many
SELECT id, pool_id, provider, provider_ref, status FROM machines
WHERE boot_deadline_at < now() AND status IN ('requested', 'provisioning')
FOR UPDATE SKIP LOCKED
`

type ClaimExpiredBootDeadlinesRow struct {
	ID          string  `json:"id"`
	PoolID      string  `json:"pool_id"`
	Provider    string  `json:"provider"`
	ProviderRef *string `json:"provider_ref"`
	Status      string  `json:"status"`
}

// Sweep: machines that never registered before their boot deadline.
func (q *Queries) ClaimExpiredBootDeadlines(ctx context.Context) ([]ClaimExpiredBootDeadlinesRow, error) {
	rows, err := q.db.Query(ctx, claimExpiredBootDeadlines)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ClaimExpiredBootDeadlinesRow{}
	for rows.Next() {
		var i ClaimExpiredBootDeadlinesRow
		if err := rows.Scan(
			&i.ID,
			&i.PoolID,
			&i.Provider,
			&i.ProviderRef,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const claimExpiredHeartbeats = `-- name: ClaimExpiredHeartbeats :many
SELECT id, pool_id, provider, provider_ref, status FROM machines
WHERE heartbeat_expires_at < now() AND status IN ('idle', 'busy', 'draining')
FOR UPDATE SKIP LOCKED
`

type ClaimExpiredHeartbeatsRow struct {
	ID          string  `json:"id"`
	PoolID      string  `json:"pool_id"`
	Provider    string  `json:"provider"`
	ProviderRef *string `json:"provider_ref"`
	Status      string  `json:"status"`
}

// Sweep: machines whose heartbeat lease lapsed → lost.
func (q *Queries) ClaimExpiredHeartbeats(ctx context.Context) ([]ClaimExpiredHeartbeatsRow, error) {
	rows, err := q.db.Query(ctx, claimExpiredHeartbeats)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ClaimExpiredHeartbeatsRow{}
	for rows.Next() {
		var i ClaimExpiredHeartbeatsRow
		if err := rows.Scan(
			&i.ID,
			&i.PoolID,
			&i.Provider,
			&i.ProviderRef,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const claimIdleMachinesPastTTL = `-- name: ClaimIdleMachinesPastTTL :many
SELECT m.id, m.pool_id FROM machines m
JOIN machine_pools p ON p.id = m.pool_id
WHERE m.status = 'idle'
  AND m.idle_since < now() - make_interval(secs := p.idle_ttl_seconds)
  AND NOT EXISTS (
    SELECT 1 FROM step_assignments a
    WHERE a.machine_id = m.id AND a.status IN ('assigned', 'running')
  )
FOR UPDATE OF m SKIP LOCKED
`

type ClaimIdleMachinesPastTTLRow struct {
	ID     string `json:"id"`
	PoolID string `json:"pool_id"`
}

// Scale-down candidates: idle beyond the pool TTL. The provisioner re-checks
// min_warm before draining. The NOT EXISTS guard is essential: a machine can be
// status='idle' yet still hold a live assignment (busy/idle accounting can drift,
// or work was bound just after it went idle) — terminating it would kill running
// work, so those are never candidates.
func (q *Queries) ClaimIdleMachinesPastTTL(ctx context.Context) ([]ClaimIdleMachinesPastTTLRow, error) {
	rows, err := q.db.Query(ctx, claimIdleMachinesPastTTL)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ClaimIdleMachinesPastTTLRow{}
	for rows.Next() {
		var i ClaimIdleMachinesPastTTLRow
		if err := rows.Scan(&i.ID, &i.PoolID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const cleanupOldMachineEvents = `-- name: CleanupOldMachineEvents :exec
DELETE FROM machine_events WHERE id IN (
    SELECT id FROM machine_events
    WHERE created_at < now() - interval '30 days'
    LIMIT 5000
)
`

// Prune machine transition history older than 30 days (mirrors engine_events).
// Heartbeat-driven busy⇄idle churn makes this high-volume on a live fleet.
// Batched so a backlog can't stall a sweep with one giant DELETE.
func (q *Queries) CleanupOldMachineEvents(ctx context.Context) error {
	_, err := q.db.Exec(ctx, cleanupOldMachineEvents)
	return err
}

const completeMachineRegistration = `-- name: CompleteMachineRegistration :exec
UPDATE machines SET
    bootstrap_token_hash = NULL,
    agent_token_hash = $1,
    cpu_millis = $2, memory_mb = $3, disk_gb = $4,
    arch = $5, os = $6, labels = $7, hostname = $8,
    agent_version = $9,
    last_heartbeat_at = now(), heartbeat_expires_at = $10,
    registered_at = now(), boot_deadline_at = NULL,
    updated_at = now()
WHERE id = $11
`

type CompleteMachineRegistrationParams struct {
	AgentTokenHash     *string    `json:"agent_token_hash"`
	CpuMillis          int64      `json:"cpu_millis"`
	MemoryMb           int64      `json:"memory_mb"`
	DiskGb             int64      `json:"disk_gb"`
	Arch               string     `json:"arch"`
	Os                 string     `json:"os"`
	Labels             []byte     `json:"labels"`
	Hostname           *string    `json:"hostname"`
	AgentVersion       *string    `json:"agent_version"`
	HeartbeatExpiresAt *time.Time `json:"heartbeat_expires_at"`
	ID                 string     `json:"id"`
}

// provisioning → idle: consume the bootstrap token, mint the agent token, record
// the agent's self-reported identity/capacity. The status transition itself goes
// through the fleet transition chokepoint in the same tx.
func (q *Queries) CompleteMachineRegistration(ctx context.Context, arg CompleteMachineRegistrationParams) error {
	_, err := q.db.Exec(ctx, completeMachineRegistration,
		arg.AgentTokenHash,
		arg.CpuMillis,
		arg.MemoryMb,
		arg.DiskGb,
		arg.Arch,
		arg.Os,
		arg.Labels,
		arg.Hostname,
		arg.AgentVersion,
		arg.HeartbeatExpiresAt,
		arg.ID,
	)
	return err
}

const countPoolMachinesByStatus = `-- name: CountPoolMachinesByStatus :many
SELECT status, count(*) AS n FROM machines
WHERE pool_id = $1 AND status IN ('requested', 'provisioning', 'idle', 'busy', 'draining')
GROUP BY status
`

type CountPoolMachinesByStatusRow struct {
	Status string `json:"status"`
	N      int64  `json:"n"`
}

// Fleet provisioner input: live machine counts per status for one pool.
func (q *Queries) CountPoolMachinesByStatus(ctx context.Context, poolID string) ([]CountPoolMachinesByStatusRow, error) {
	rows, err := q.db.Query(ctx, countPoolMachinesByStatus, poolID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountPoolMachinesByStatusRow{}
	for rows.Next() {
		var i CountPoolMachinesByStatusRow
		if err := rows.Scan(&i.Status, &i.N); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMachine = `-- name: GetMachine :one
SELECT id, pool_id, status, provider, provider_ref, instance_type, region, zone, capacity_type, price_per_hour_usd, accepted_offer, cpu_millis, memory_mb, disk_gb, arch, os, labels, hostname, agent_version, bootstrap_token_hash, agent_token_hash, boot_deadline_at, heartbeat_interval_seconds, last_heartbeat_at, heartbeat_expires_at, steps_completed, idle_since, drain_reason, requested_at, provisioned_at, registered_at, terminated_at, updated_at FROM machines WHERE id = $1
`

func (q *Queries) GetMachine(ctx context.Context, id string) (Machine, error) {
	row := q.db.QueryRow(ctx, getMachine, id)
	var i Machine
	err := row.Scan(
		&i.ID,
		&i.PoolID,
		&i.Status,
		&i.Provider,
		&i.ProviderRef,
		&i.InstanceType,
		&i.Region,
		&i.Zone,
		&i.CapacityType,
		&i.PricePerHourUsd,
		&i.AcceptedOffer,
		&i.CpuMillis,
		&i.MemoryMb,
		&i.DiskGb,
		&i.Arch,
		&i.Os,
		&i.Labels,
		&i.Hostname,
		&i.AgentVersion,
		&i.BootstrapTokenHash,
		&i.AgentTokenHash,
		&i.BootDeadlineAt,
		&i.HeartbeatIntervalSeconds,
		&i.LastHeartbeatAt,
		&i.HeartbeatExpiresAt,
		&i.StepsCompleted,
		&i.IdleSince,
		&i.DrainReason,
		&i.RequestedAt,
		&i.ProvisionedAt,
		&i.RegisteredAt,
		&i.TerminatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMachineByAgentTokenHash = `-- name: GetMachineByAgentTokenHash :one
SELECT id, pool_id, status, provider, provider_ref, instance_type, region, zone, capacity_type, price_per_hour_usd, accepted_offer, cpu_millis, memory_mb, disk_gb, arch, os, labels, hostname, agent_version, bootstrap_token_hash, agent_token_hash, boot_deadline_at, heartbeat_interval_seconds, last_heartbeat_at, heartbeat_expires_at, steps_completed, idle_since, drain_reason, requested_at, provisioned_at, registered_at, terminated_at, updated_at FROM machines
WHERE agent_token_hash = $1
  AND status NOT IN ('terminated', 'failed')
`

// Auth interceptor lookup for all post-registration agent calls.
func (q *Queries) GetMachineByAgentTokenHash(ctx context.Context, agentTokenHash *string) (Machine, error) {
	row := q.db.QueryRow(ctx, getMachineByAgentTokenHash, agentTokenHash)
	var i Machine
	err := row.Scan(
		&i.ID,
		&i.PoolID,
		&i.Status,
		&i.Provider,
		&i.ProviderRef,
		&i.InstanceType,
		&i.Region,
		&i.Zone,
		&i.CapacityType,
		&i.PricePerHourUsd,
		&i.AcceptedOffer,
		&i.CpuMillis,
		&i.MemoryMb,
		&i.DiskGb,
		&i.Arch,
		&i.Os,
		&i.Labels,
		&i.Hostname,
		&i.AgentVersion,
		&i.BootstrapTokenHash,
		&i.AgentTokenHash,
		&i.BootDeadlineAt,
		&i.HeartbeatIntervalSeconds,
		&i.LastHeartbeatAt,
		&i.HeartbeatExpiresAt,
		&i.StepsCompleted,
		&i.IdleSince,
		&i.DrainReason,
		&i.RequestedAt,
		&i.ProvisionedAt,
		&i.RegisteredAt,
		&i.TerminatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMachineByBootstrapTokenHash = `-- name: GetMachineByBootstrapTokenHash :one
SELECT id, pool_id, status, provider, provider_ref, instance_type, region, zone, capacity_type, price_per_hour_usd, accepted_offer, cpu_millis, memory_mb, disk_gb, arch, os, labels, hostname, agent_version, bootstrap_token_hash, agent_token_hash, boot_deadline_at, heartbeat_interval_seconds, last_heartbeat_at, heartbeat_expires_at, steps_completed, idle_since, drain_reason, requested_at, provisioned_at, registered_at, terminated_at, updated_at FROM machines WHERE bootstrap_token_hash = $1
  AND status IN ('requested', 'provisioning')
`

// Elastic registration: single-use — the caller clears the hash in the same tx.
// 'requested' is included because provider.Create returns before the
// requested → provisioning transition commits, and a very fast instance could
// register in that window.
func (q *Queries) GetMachineByBootstrapTokenHash(ctx context.Context, bootstrapTokenHash *string) (Machine, error) {
	row := q.db.QueryRow(ctx, getMachineByBootstrapTokenHash, bootstrapTokenHash)
	var i Machine
	err := row.Scan(
		&i.ID,
		&i.PoolID,
		&i.Status,
		&i.Provider,
		&i.ProviderRef,
		&i.InstanceType,
		&i.Region,
		&i.Zone,
		&i.CapacityType,
		&i.PricePerHourUsd,
		&i.AcceptedOffer,
		&i.CpuMillis,
		&i.MemoryMb,
		&i.DiskGb,
		&i.Arch,
		&i.Os,
		&i.Labels,
		&i.Hostname,
		&i.AgentVersion,
		&i.BootstrapTokenHash,
		&i.AgentTokenHash,
		&i.BootDeadlineAt,
		&i.HeartbeatIntervalSeconds,
		&i.LastHeartbeatAt,
		&i.HeartbeatExpiresAt,
		&i.StepsCompleted,
		&i.IdleSince,
		&i.DrainReason,
		&i.RequestedAt,
		&i.ProvisionedAt,
		&i.RegisteredAt,
		&i.TerminatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const incrementMachineStepsCompleted = `-- name: IncrementMachineStepsCompleted :exec
UPDATE machines SET steps_completed = steps_completed + 1, updated_at = now() WHERE id = $1
`

func (q *Queries) IncrementMachineStepsCompleted(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, incrementMachineStepsCompleted, id)
	return err
}

const insertMachine = `-- name: InsertMachine :one
INSERT INTO machines (
    pool_id, status, provider, instance_type, region, zone, capacity_type,
    price_per_hour_usd, accepted_offer, cpu_millis, memory_mb, disk_gb, arch,
    bootstrap_token_hash
) VALUES (
    $1, 'requested', $2, $3, $4, $5, $6,
    $7, $8, $9, $10, $11, $12,
    $13
) RETURNING id
`

type InsertMachineParams struct {
	PoolID             string         `json:"pool_id"`
	Provider           string         `json:"provider"`
	InstanceType       *string        `json:"instance_type"`
	Region             *string        `json:"region"`
	Zone               *string        `json:"zone"`
	CapacityType       *string        `json:"capacity_type"`
	PricePerHourUsd    pgtype.Numeric `json:"price_per_hour_usd"`
	AcceptedOffer      []byte         `json:"accepted_offer"`
	CpuMillis          int64          `json:"cpu_millis"`
	MemoryMb           int64          `json:"memory_mb"`
	DiskGb             int64          `json:"disk_gb"`
	Arch               string         `json:"arch"`
	BootstrapTokenHash *string        `json:"bootstrap_token_hash"`
}

// Elastic path: the fleet provisioner pre-allocates the row in 'requested' with a
// minted bootstrap token before calling provider.Create (Create is idempotent per
// machine id, so a crash between insert and Create is safe to retry).
func (q *Queries) InsertMachine(ctx context.Context, arg InsertMachineParams) (string, error) {
	row := q.db.QueryRow(ctx, insertMachine,
		arg.PoolID,
		arg.Provider,
		arg.InstanceType,
		arg.Region,
		arg.Zone,
		arg.CapacityType,
		arg.PricePerHourUsd,
		arg.AcceptedOffer,
		arg.CpuMillis,
		arg.MemoryMb,
		arg.DiskGb,
		arg.Arch,
		arg.BootstrapTokenHash,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}

const insertMachineEvent = `-- name: InsertMachineEvent :exec
INSERT INTO machine_events (machine_id, event_type, from_status, to_status, actor, reason, metadata)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type InsertMachineEventParams struct {
	MachineID  string  `json:"machine_id"`
	EventType  string  `json:"event_type"`
	FromStatus *string `json:"from_status"`
	ToStatus   *string `json:"to_status"`
	Actor      string  `json:"actor"`
	Reason     *string `json:"reason"`
	Metadata   []byte  `json:"metadata"`
}

func (q *Queries) InsertMachineEvent(ctx context.Context, arg InsertMachineEventParams) error {
	_, err := q.db.Exec(ctx, insertMachineEvent,
		arg.MachineID,
		arg.EventType,
		arg.FromStatus,
		arg.ToStatus,
		arg.Actor,
		arg.Reason,
		arg.Metadata,
	)
	return err
}

const insertStaticMachine = `-- name: InsertStaticMachine :one
INSERT INTO machines (
    pool_id, status, provider, cpu_millis, memory_mb, disk_gb, arch, os,
    labels, hostname, agent_version, agent_token_hash,
    heartbeat_interval_seconds, last_heartbeat_at, heartbeat_expires_at,
    registered_at, idle_since
) VALUES (
    $1, 'idle', 'static', $2, $3, $4, $5, $6,
    $7, $8, $9, $10,
    $11, now(), $12,
    now(), now()
) RETURNING id
`

type InsertStaticMachineParams struct {
	PoolID                   string     `json:"pool_id"`
	CpuMillis                int64      `json:"cpu_millis"`
	MemoryMb                 int64      `json:"memory_mb"`
	DiskGb                   int64      `json:"disk_gb"`
	Arch                     string     `json:"arch"`
	Os                       string     `json:"os"`
	Labels                   []byte     `json:"labels"`
	Hostname                 *string    `json:"hostname"`
	AgentVersion             *string    `json:"agent_version"`
	AgentTokenHash           *string    `json:"agent_token_hash"`
	HeartbeatIntervalSeconds int32      `json:"heartbeat_interval_seconds"`
	HeartbeatExpiresAt       *time.Time `json:"heartbeat_expires_at"`
}

// Static path: RegisterMachine with a pool join token creates the machine directly
// in 'idle' with the agent's self-reported capacity.
func (q *Queries) InsertStaticMachine(ctx context.Context, arg InsertStaticMachineParams) (string, error) {
	row := q.db.QueryRow(ctx, insertStaticMachine,
		arg.PoolID,
		arg.CpuMillis,
		arg.MemoryMb,
		arg.DiskGb,
		arg.Arch,
		arg.Os,
		arg.Labels,
		arg.Hostname,
		arg.AgentVersion,
		arg.AgentTokenHash,
		arg.HeartbeatIntervalSeconds,
		arg.HeartbeatExpiresAt,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}

const listMachineEvents = `-- name: ListMachineEvents :many
SELECT id, machine_id, event_type, from_status, to_status, actor, reason, metadata, created_at FROM machine_events WHERE machine_id = $1 ORDER BY created_at DESC LIMIT $2
`

type ListMachineEventsParams struct {
	MachineID string `json:"machine_id"`
	Limit     int32  `json:"limit"`
}

func (q *Queries) ListMachineEvents(ctx context.Context, arg ListMachineEventsParams) ([]MachineEvent, error) {
	rows, err := q.db.Query(ctx, listMachineEvents, arg.MachineID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MachineEvent{}
	for rows.Next() {
		var i MachineEvent
		if err := rows.Scan(
			&i.ID,
			&i.MachineID,
			&i.EventType,
			&i.FromStatus,
			&i.ToStatus,
			&i.Actor,
			&i.Reason,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMachinesPaged = `-- name: ListMachinesPaged :many
SELECT id, pool_id, status, provider, provider_ref, instance_type, region, zone, capacity_type, price_per_hour_usd, accepted_offer, cpu_millis, memory_mb, disk_gb, arch, os, labels, hostname, agent_version, bootstrap_token_hash, agent_token_hash, boot_deadline_at, heartbeat_interval_seconds, last_heartbeat_at, heartbeat_expires_at, steps_completed, idle_since, drain_reason, requested_at, provisioned_at, registered_at, terminated_at, updated_at FROM machines
WHERE ($3::uuid IS NULL OR pool_id = $3)
  AND ($4::text IS NULL OR status = $4)
ORDER BY requested_at DESC LIMIT $1 OFFSET $2
`

type ListMachinesPagedParams struct {
	Limit  int32   `json:"limit"`
	Offset int32   `json:"offset"`
	PoolID *string `json:"pool_id"`
	Status *string `json:"status"`
}

func (q *Queries) ListMachinesPaged(ctx context.Context, arg ListMachinesPagedParams) ([]Machine, error) {
	rows, err := q.db.Query(ctx, listMachinesPaged,
		arg.Limit,
		arg.Offset,
		arg.PoolID,
		arg.Status,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Machine{}
	for rows.Next() {
		var i Machine
		if err := rows.Scan(
			&i.ID,
			&i.PoolID,
			&i.Status,
			&i.Provider,
			&i.ProviderRef,
			&i.InstanceType,
			&i.Region,
			&i.Zone,
			&i.CapacityType,
			&i.PricePerHourUsd,
			&i.AcceptedOffer,
			&i.CpuMillis,
			&i.MemoryMb,
			&i.DiskGb,
			&i.Arch,
			&i.Os,
			&i.Labels,
			&i.Hostname,
			&i.AgentVersion,
			&i.BootstrapTokenHash,
			&i.AgentTokenHash,
			&i.BootDeadlineAt,
			&i.HeartbeatIntervalSeconds,
			&i.LastHeartbeatAt,
			&i.HeartbeatExpiresAt,
			&i.StepsCompleted,
			&i.IdleSince,
			&i.DrainReason,
			&i.RequestedAt,
			&i.ProvisionedAt,
			&i.RegisteredAt,
			&i.TerminatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPoolMachines = `-- name: ListPoolMachines :many
SELECT id, pool_id, status, provider, provider_ref, instance_type, region, zone, capacity_type, price_per_hour_usd, accepted_offer, cpu_millis, memory_mb, disk_gb, arch, os, labels, hostname, agent_version, bootstrap_token_hash, agent_token_hash, boot_deadline_at, heartbeat_interval_seconds, last_heartbeat_at, heartbeat_expires_at, steps_completed, idle_since, drain_reason, requested_at, provisioned_at, registered_at, terminated_at, updated_at FROM machines WHERE pool_id = $1
  AND status NOT IN ('terminated', 'failed')
ORDER BY requested_at
`

func (q *Queries) ListPoolMachines(ctx context.Context, poolID string) ([]Machine, error) {
	rows, err := q.db.Query(ctx, listPoolMachines, poolID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Machine{}
	for rows.Next() {
		var i Machine
		if err := rows.Scan(
			&i.ID,
			&i.PoolID,
			&i.Status,
			&i.Provider,
			&i.ProviderRef,
			&i.InstanceType,
			&i.Region,
			&i.Zone,
			&i.CapacityType,
			&i.PricePerHourUsd,
			&i.AcceptedOffer,
			&i.CpuMillis,
			&i.MemoryMb,
			&i.DiskGb,
			&i.Arch,
			&i.Os,
			&i.Labels,
			&i.Hostname,
			&i.AgentVersion,
			&i.BootstrapTokenHash,
			&i.AgentTokenHash,
			&i.BootDeadlineAt,
			&i.HeartbeatIntervalSeconds,
			&i.LastHeartbeatAt,
			&i.HeartbeatExpiresAt,
			&i.StepsCompleted,
			&i.IdleSince,
			&i.DrainReason,
			&i.RequestedAt,
			&i.ProvisionedAt,
			&i.RegisteredAt,
			&i.TerminatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProviderMachines = `-- name: ListProviderMachines :many
SELECT id, pool_id, status, provider_ref FROM machines
WHERE provider = $1 AND status NOT IN ('terminated', 'failed')
`

type ListProviderMachinesRow struct {
	ID          string  `json:"id"`
	PoolID      string  `json:"pool_id"`
	Status      string  `json:"status"`
	ProviderRef *string `json:"provider_ref"`
}

// Reconciliation input: this provider's machines in every non-final state.
func (q *Queries) ListProviderMachines(ctx context.Context, provider string) ([]ListProviderMachinesRow, error) {
	rows, err := q.db.Query(ctx, listProviderMachines, provider)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProviderMachinesRow{}
	for rows.Next() {
		var i ListProviderMachinesRow
		if err := rows.Scan(
			&i.ID,
			&i.PoolID,
			&i.Status,
			&i.ProviderRef,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setMachineProviderRef = `-- name: SetMachineProviderRef :exec
UPDATE machines SET provider_ref = $2, provisioned_at = COALESCE(provisioned_at, now()), updated_at = now()
WHERE id = $1
`

type SetMachineProviderRefParams struct {
	ID          string  `json:"id"`
	ProviderRef *string `json:"provider_ref"`
}

// Records the provider instance id without touching status — used when the
// agent registered before the provisioning transition could commit.
func (q *Queries) SetMachineProviderRef(ctx context.Context, arg SetMachineProviderRefParams) error {
	_, err := q.db.Exec(ctx, setMachineProviderRef, arg.ID, arg.ProviderRef)
	return err
}

const touchMachineHeartbeat = `-- name: TouchMachineHeartbeat :exec
UPDATE machines SET
    last_heartbeat_at = now(),
    heartbeat_expires_at = $1,
    agent_version = $2,
    updated_at = now()
WHERE id = $3
`

type TouchMachineHeartbeatParams struct {
	HeartbeatExpiresAt *time.Time `json:"heartbeat_expires_at"`
	AgentVersion       *string    `json:"agent_version"`
	ID                 string     `json:"id"`
}

func (q *Queries) TouchMachineHeartbeat(ctx context.Context, arg TouchMachineHeartbeatParams) error {
	_, err := q.db.Exec(ctx, touchMachineHeartbeat, arg.HeartbeatExpiresAt, arg.AgentVersion, arg.ID)
	return err
}

const updateMachineStatus = `-- name: UpdateMachineStatus :execrows
UPDATE machines SET
    status = $1,
    drain_reason = COALESCE($2, drain_reason),
    provider_ref = COALESCE($3, provider_ref),
    boot_deadline_at = COALESCE($4, boot_deadline_at),
    provisioned_at = CASE WHEN $1 = 'provisioning' THEN now() ELSE provisioned_at END,
    idle_since     = CASE WHEN $1 = 'idle' THEN now() ELSE idle_since END,
    terminated_at  = CASE WHEN $1 IN ('terminated', 'failed') THEN now() ELSE terminated_at END,
    updated_at = now()
WHERE id = $5 AND status = $6
`

type UpdateMachineStatusParams struct {
	Status         string     `json:"status"`
	DrainReason    *string    `json:"drain_reason"`
	ProviderRef    *string    `json:"provider_ref"`
	BootDeadlineAt *time.Time `json:"boot_deadline_at"`
	ID             string     `json:"id"`
	FromStatus     string     `json:"from_status"`
}

// Used only by the fleet transition chokepoint after validating the edge; callers
// never update status directly. The `from` guard makes the transition optimistic:
// the row moves only if it's still in the expected state, so 0 rows affected means
// another actor already moved it (a lost race). The chokepoint surfaces that so the
// caller can skip or roll back, rather than clobbering a concurrent transition
// (last-writer-wins would corrupt busy/idle accounting under multi-replica load).
func (q *Queries) UpdateMachineStatus(ctx context.Context, arg UpdateMachineStatusParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateMachineStatus,
		arg.Status,
		arg.DrainReason,
		arg.ProviderRef,
		arg.BootDeadlineAt,
		arg.ID,
		arg.FromStatus,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
