// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: machine_pools.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const countDefaultMachinePools = `-- name: CountDefaultMachinePools :one
SELECT count(*) FROM machine_pools WHERE is_default = true
`

func (q *Queries) CountDefaultMachinePools(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countDefaultMachinePools)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteMachinePool = `-- name: DeleteMachinePool :exec
DELETE FROM machine_pools WHERE name = $1
`

func (q *Queries) DeleteMachinePool(ctx context.Context, name string) error {
	_, err := q.db.Exec(ctx, deleteMachinePool, name)
	return err
}

const getMachinePool = `-- name: GetMachinePool :one
SELECT id, name, description, provider, arch, cpu, memory, disk,
       gpu_vendor, gpu_model, gpu_count, instance_types, regions,
       capacity_type, objective, min_warm, max_machines, idle_ttl_seconds,
       overrides, hourly_cost, default_timeout, is_default
FROM machine_pools WHERE name = $1
`

type GetMachinePoolRow struct {
	ID             string         `json:"id"`
	Name           string         `json:"name"`
	Description    *string        `json:"description"`
	Provider       string         `json:"provider"`
	Arch           string         `json:"arch"`
	Cpu            string         `json:"cpu"`
	Memory         string         `json:"memory"`
	Disk           *string        `json:"disk"`
	GpuVendor      *string        `json:"gpu_vendor"`
	GpuModel       *string        `json:"gpu_model"`
	GpuCount       pgtype.Int4    `json:"gpu_count"`
	InstanceTypes  []string       `json:"instance_types"`
	Regions        []string       `json:"regions"`
	CapacityType   string         `json:"capacity_type"`
	Objective      string         `json:"objective"`
	MinWarm        int32          `json:"min_warm"`
	MaxMachines    int32          `json:"max_machines"`
	IdleTtlSeconds int32          `json:"idle_ttl_seconds"`
	Overrides      []byte         `json:"overrides"`
	HourlyCost     pgtype.Numeric `json:"hourly_cost"`
	DefaultTimeout *string        `json:"default_timeout"`
	IsDefault      bool           `json:"is_default"`
}

func (q *Queries) GetMachinePool(ctx context.Context, name string) (GetMachinePoolRow, error) {
	row := q.db.QueryRow(ctx, getMachinePool, name)
	var i GetMachinePoolRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Provider,
		&i.Arch,
		&i.Cpu,
		&i.Memory,
		&i.Disk,
		&i.GpuVendor,
		&i.GpuModel,
		&i.GpuCount,
		&i.InstanceTypes,
		&i.Regions,
		&i.CapacityType,
		&i.Objective,
		&i.MinWarm,
		&i.MaxMachines,
		&i.IdleTtlSeconds,
		&i.Overrides,
		&i.HourlyCost,
		&i.DefaultTimeout,
		&i.IsDefault,
	)
	return i, err
}

const getMachinePoolByID = `-- name: GetMachinePoolByID :one
SELECT id, name, provider, arch, idle_ttl_seconds, min_warm, max_machines
FROM machine_pools WHERE id = $1
`

type GetMachinePoolByIDRow struct {
	ID             string `json:"id"`
	Name           string `json:"name"`
	Provider       string `json:"provider"`
	Arch           string `json:"arch"`
	IdleTtlSeconds int32  `json:"idle_ttl_seconds"`
	MinWarm        int32  `json:"min_warm"`
	MaxMachines    int32  `json:"max_machines"`
}

func (q *Queries) GetMachinePoolByID(ctx context.Context, id string) (GetMachinePoolByIDRow, error) {
	row := q.db.QueryRow(ctx, getMachinePoolByID, id)
	var i GetMachinePoolByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Provider,
		&i.Arch,
		&i.IdleTtlSeconds,
		&i.MinWarm,
		&i.MaxMachines,
	)
	return i, err
}

const getPoolByJoinTokenHash = `-- name: GetPoolByJoinTokenHash :one
SELECT id, name, provider, arch FROM machine_pools
WHERE join_token_hash = $1 AND ready = true
`

type GetPoolByJoinTokenHashRow struct {
	ID       string `json:"id"`
	Name     string `json:"name"`
	Provider string `json:"provider"`
	Arch     string `json:"arch"`
}

// Registration path for static-pool agents presenting a join token.
func (q *Queries) GetPoolByJoinTokenHash(ctx context.Context, joinTokenHash *string) (GetPoolByJoinTokenHashRow, error) {
	row := q.db.QueryRow(ctx, getPoolByJoinTokenHash, joinTokenHash)
	var i GetPoolByJoinTokenHashRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Provider,
		&i.Arch,
	)
	return i, err
}

const listMachinePoolNames = `-- name: ListMachinePoolNames :many
SELECT name FROM machine_pools
`

func (q *Queries) ListMachinePoolNames(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, listMachinePoolNames)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMachinePools = `-- name: ListMachinePools :many
SELECT id, name, description, provider, arch, cpu, memory, disk,
       gpu_vendor, gpu_model, gpu_count, instance_types, regions,
       capacity_type, objective, min_warm, max_machines, idle_ttl_seconds,
       overrides, hourly_cost, default_timeout, is_default
FROM machine_pools WHERE ready = true ORDER BY name
`

type ListMachinePoolsRow struct {
	ID             string         `json:"id"`
	Name           string         `json:"name"`
	Description    *string        `json:"description"`
	Provider       string         `json:"provider"`
	Arch           string         `json:"arch"`
	Cpu            string         `json:"cpu"`
	Memory         string         `json:"memory"`
	Disk           *string        `json:"disk"`
	GpuVendor      *string        `json:"gpu_vendor"`
	GpuModel       *string        `json:"gpu_model"`
	GpuCount       pgtype.Int4    `json:"gpu_count"`
	InstanceTypes  []string       `json:"instance_types"`
	Regions        []string       `json:"regions"`
	CapacityType   string         `json:"capacity_type"`
	Objective      string         `json:"objective"`
	MinWarm        int32          `json:"min_warm"`
	MaxMachines    int32          `json:"max_machines"`
	IdleTtlSeconds int32          `json:"idle_ttl_seconds"`
	Overrides      []byte         `json:"overrides"`
	HourlyCost     pgtype.Numeric `json:"hourly_cost"`
	DefaultTimeout *string        `json:"default_timeout"`
	IsDefault      bool           `json:"is_default"`
}

// Full rows — used by the fleet pool registry loader, compile-time validation, and
// the pool catalog. Returns everything needed to reconstruct a PoolSpec.
func (q *Queries) ListMachinePools(ctx context.Context) ([]ListMachinePoolsRow, error) {
	rows, err := q.db.Query(ctx, listMachinePools)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMachinePoolsRow{}
	for rows.Next() {
		var i ListMachinePoolsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Provider,
			&i.Arch,
			&i.Cpu,
			&i.Memory,
			&i.Disk,
			&i.GpuVendor,
			&i.GpuModel,
			&i.GpuCount,
			&i.InstanceTypes,
			&i.Regions,
			&i.CapacityType,
			&i.Objective,
			&i.MinWarm,
			&i.MaxMachines,
			&i.IdleTtlSeconds,
			&i.Overrides,
			&i.HourlyCost,
			&i.DefaultTimeout,
			&i.IsDefault,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMachinePoolsPaged = `-- name: ListMachinePoolsPaged :many
SELECT id, name, description, provider, arch, cpu, memory, disk,
       gpu_vendor, gpu_model, gpu_count, instance_types, regions,
       capacity_type, objective, min_warm, max_machines, idle_ttl_seconds,
       overrides, hourly_cost, is_default, ready, created_at
FROM machine_pools ORDER BY name LIMIT $1 OFFSET $2
`

type ListMachinePoolsPagedParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListMachinePoolsPagedRow struct {
	ID             string         `json:"id"`
	Name           string         `json:"name"`
	Description    *string        `json:"description"`
	Provider       string         `json:"provider"`
	Arch           string         `json:"arch"`
	Cpu            string         `json:"cpu"`
	Memory         string         `json:"memory"`
	Disk           *string        `json:"disk"`
	GpuVendor      *string        `json:"gpu_vendor"`
	GpuModel       *string        `json:"gpu_model"`
	GpuCount       pgtype.Int4    `json:"gpu_count"`
	InstanceTypes  []string       `json:"instance_types"`
	Regions        []string       `json:"regions"`
	CapacityType   string         `json:"capacity_type"`
	Objective      string         `json:"objective"`
	MinWarm        int32          `json:"min_warm"`
	MaxMachines    int32          `json:"max_machines"`
	IdleTtlSeconds int32          `json:"idle_ttl_seconds"`
	Overrides      []byte         `json:"overrides"`
	HourlyCost     pgtype.Numeric `json:"hourly_cost"`
	IsDefault      bool           `json:"is_default"`
	Ready          bool           `json:"ready"`
	CreatedAt      time.Time      `json:"created_at"`
}

func (q *Queries) ListMachinePoolsPaged(ctx context.Context, arg ListMachinePoolsPagedParams) ([]ListMachinePoolsPagedRow, error) {
	rows, err := q.db.Query(ctx, listMachinePoolsPaged, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMachinePoolsPagedRow{}
	for rows.Next() {
		var i ListMachinePoolsPagedRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Provider,
			&i.Arch,
			&i.Cpu,
			&i.Memory,
			&i.Disk,
			&i.GpuVendor,
			&i.GpuModel,
			&i.GpuCount,
			&i.InstanceTypes,
			&i.Regions,
			&i.CapacityType,
			&i.Objective,
			&i.MinWarm,
			&i.MaxMachines,
			&i.IdleTtlSeconds,
			&i.Overrides,
			&i.HourlyCost,
			&i.IsDefault,
			&i.Ready,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setDefaultMachinePool = `-- name: SetDefaultMachinePool :exec
UPDATE machine_pools SET is_default = (name = $1), updated_at = now()
`

// Promotes one pool to default and demotes all others atomically.
func (q *Queries) SetDefaultMachinePool(ctx context.Context, name string) error {
	_, err := q.db.Exec(ctx, setDefaultMachinePool, name)
	return err
}

const setPoolJoinTokenHash = `-- name: SetPoolJoinTokenHash :exec
UPDATE machine_pools SET join_token_hash = $2, updated_at = now() WHERE name = $1
`

type SetPoolJoinTokenHashParams struct {
	Name          string  `json:"name"`
	JoinTokenHash *string `json:"join_token_hash"`
}

// Static pools: stores the sha256 of a newly minted (or rotated) agent join token.
func (q *Queries) SetPoolJoinTokenHash(ctx context.Context, arg SetPoolJoinTokenHashParams) error {
	_, err := q.db.Exec(ctx, setPoolJoinTokenHash, arg.Name, arg.JoinTokenHash)
	return err
}

const upsertMachinePool = `-- name: UpsertMachinePool :exec
INSERT INTO machine_pools (
    name, description, provider, arch, cpu, memory, disk,
    gpu_vendor, gpu_model, gpu_count, instance_types, regions,
    capacity_type, objective, min_warm, max_machines, idle_ttl_seconds,
    overrides, hourly_cost, default_timeout, ready, updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7,
    $8, $9, $10, $11, $12,
    $13, $14, $15, $16, $17,
    $18, $19, $20, true, now()
)
ON CONFLICT (name) DO UPDATE SET
    description = EXCLUDED.description,
    provider = EXCLUDED.provider,
    arch = EXCLUDED.arch,
    cpu = EXCLUDED.cpu,
    memory = EXCLUDED.memory,
    disk = EXCLUDED.disk,
    gpu_vendor = EXCLUDED.gpu_vendor,
    gpu_model = EXCLUDED.gpu_model,
    gpu_count = EXCLUDED.gpu_count,
    instance_types = EXCLUDED.instance_types,
    regions = EXCLUDED.regions,
    capacity_type = EXCLUDED.capacity_type,
    objective = EXCLUDED.objective,
    min_warm = EXCLUDED.min_warm,
    max_machines = EXCLUDED.max_machines,
    idle_ttl_seconds = EXCLUDED.idle_ttl_seconds,
    overrides = EXCLUDED.overrides,
    hourly_cost = EXCLUDED.hourly_cost,
    default_timeout = EXCLUDED.default_timeout,
    ready = true,
    updated_at = now()
`

type UpsertMachinePoolParams struct {
	Name           string         `json:"name"`
	Description    *string        `json:"description"`
	Provider       string         `json:"provider"`
	Arch           string         `json:"arch"`
	Cpu            string         `json:"cpu"`
	Memory         string         `json:"memory"`
	Disk           *string        `json:"disk"`
	GpuVendor      *string        `json:"gpu_vendor"`
	GpuModel       *string        `json:"gpu_model"`
	GpuCount       pgtype.Int4    `json:"gpu_count"`
	InstanceTypes  []string       `json:"instance_types"`
	Regions        []string       `json:"regions"`
	CapacityType   string         `json:"capacity_type"`
	Objective      string         `json:"objective"`
	MinWarm        int32          `json:"min_warm"`
	MaxMachines    int32          `json:"max_machines"`
	IdleTtlSeconds int32          `json:"idle_ttl_seconds"`
	Overrides      []byte         `json:"overrides"`
	HourlyCost     pgtype.Numeric `json:"hourly_cost"`
	DefaultTimeout *string        `json:"default_timeout"`
}

func (q *Queries) UpsertMachinePool(ctx context.Context, arg UpsertMachinePoolParams) error {
	_, err := q.db.Exec(ctx, upsertMachinePool,
		arg.Name,
		arg.Description,
		arg.Provider,
		arg.Arch,
		arg.Cpu,
		arg.Memory,
		arg.Disk,
		arg.GpuVendor,
		arg.GpuModel,
		arg.GpuCount,
		arg.InstanceTypes,
		arg.Regions,
		arg.CapacityType,
		arg.Objective,
		arg.MinWarm,
		arg.MaxMachines,
		arg.IdleTtlSeconds,
		arg.Overrides,
		arg.HourlyCost,
		arg.DefaultTimeout,
	)
	return err
}
