// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type ApiKey struct {
	ID         string     `json:"id"`
	OrgID      string     `json:"org_id"`
	UserID     *string    `json:"user_id"`
	Name       string     `json:"name"`
	KeyHash    string     `json:"key_hash"`
	Scopes     []string   `json:"scopes"`
	ExpiresAt  *time.Time `json:"expires_at"`
	LastUsedAt *time.Time `json:"last_used_at"`
	CreatedAt  time.Time  `json:"created_at"`
	RoleID     *string    `json:"role_id"`
}

type ApiKeyEnvironmentScope struct {
	ApiKeyID      string `json:"api_key_id"`
	EnvironmentID string `json:"environment_id"`
}

type ApiKeyWorkspaceScope struct {
	ApiKeyID    string `json:"api_key_id"`
	WorkspaceID string `json:"workspace_id"`
}

type AuditLog struct {
	ID           string    `json:"id"`
	OrgID        string    `json:"org_id"`
	UserID       *string   `json:"user_id"`
	Action       string    `json:"action"`
	ResourceType string    `json:"resource_type"`
	ResourceID   *string   `json:"resource_id"`
	Metadata     []byte    `json:"metadata"`
	IpAddress    *string   `json:"ip_address"`
	CreatedAt    time.Time `json:"created_at"`
}

type AuthProviderConfig struct {
	ID           string    `json:"id"`
	ProviderType string    `json:"provider_type"`
	DisplayName  string    `json:"display_name"`
	ConfigEnc    []byte    `json:"config_enc"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
}

type CasbinRule struct {
	ID    int64  `json:"id"`
	Ptype string `json:"ptype"`
	V0    string `json:"v0"`
	V1    string `json:"v1"`
	V2    string `json:"v2"`
	V3    string `json:"v3"`
	V4    string `json:"v4"`
	V5    string `json:"v5"`
}

type ComputeProvider struct {
	ID             string    `json:"id"`
	Name           string    `json:"name"`
	ProviderType   string    `json:"provider_type"`
	Config         []byte    `json:"config"`
	CredentialsEnc []byte    `json:"credentials_enc"`
	CreatedAt      time.Time `json:"created_at"`
	UpdatedAt      time.Time `json:"updated_at"`
}

type DeviceCode struct {
	DeviceCode    string     `json:"device_code"`
	UserCode      string     `json:"user_code"`
	OauthState    *string    `json:"oauth_state"`
	Nonce         *string    `json:"nonce"`
	CodeVerifier  *string    `json:"code_verifier"`
	SamlRequestID *string    `json:"saml_request_id"`
	Completed     bool       `json:"completed"`
	AccessToken   *string    `json:"access_token"`
	RefreshToken  *string    `json:"refresh_token"`
	UserID        *string    `json:"user_id"`
	IntervalSecs  int32      `json:"interval_secs"`
	LastPolledAt  *time.Time `json:"last_polled_at"`
	ExpiresAt     time.Time  `json:"expires_at"`
	CreatedAt     time.Time  `json:"created_at"`
}

type EngineEvent struct {
	ID         string      `json:"id"`
	WorkflowID string      `json:"workflow_id"`
	StepName   *string     `json:"step_name"`
	Attempt    pgtype.Int4 `json:"attempt"`
	EventType  string      `json:"event_type"`
	FromStatus *string     `json:"from_status"`
	ToStatus   *string     `json:"to_status"`
	Actor      string      `json:"actor"`
	Reason     *string     `json:"reason"`
	Metadata   []byte      `json:"metadata"`
	CreatedAt  time.Time   `json:"created_at"`
}

type EnvVariable struct {
	ID          string    `json:"id"`
	OrgID       string    `json:"org_id"`
	Name        string    `json:"name"`
	Description *string   `json:"description"`
	Scope       string    `json:"scope"`
	IsSecret    bool      `json:"is_secret"`
	CreatedAt   time.Time `json:"created_at"`
}

type EnvVariableValue struct {
	VariableID    string    `json:"variable_id"`
	EnvironmentID *string   `json:"environment_id"`
	Value         string    `json:"value"`
	ValueEnc      []byte    `json:"value_enc"`
	UpdatedAt     time.Time `json:"updated_at"`
}

type Environment struct {
	ID        string    `json:"id"`
	OrgID     string    `json:"org_id"`
	Name      string    `json:"name"`
	Slug      string    `json:"slug"`
	CreatedAt time.Time `json:"created_at"`
}

type FleetDecision struct {
	ID              string     `json:"id"`
	PoolID          *string    `json:"pool_id"`
	MachineID       *string    `json:"machine_id"`
	DecisionType    string     `json:"decision_type"`
	Inputs          []byte     `json:"inputs"`
	Chosen          []byte     `json:"chosen"`
	Alternatives    []byte     `json:"alternatives"`
	Outcome         *string    `json:"outcome"`
	OutcomeMetadata []byte     `json:"outcome_metadata"`
	OutcomeAt       *time.Time `json:"outcome_at"`
	CreatedAt       time.Time  `json:"created_at"`
}

type FlintOutbox struct {
	ID             string     `json:"id"`
	EventType      string     `json:"event_type"`
	Payload        []byte     `json:"payload"`
	Status         string     `json:"status"`
	Attempts       int32      `json:"attempts"`
	MaxAttempts    int32      `json:"max_attempts"`
	IdempotencyKey string     `json:"idempotency_key"`
	ProcessAfter   time.Time  `json:"process_after"`
	ClaimedAt      *time.Time `json:"claimed_at"`
	CreatedAt      time.Time  `json:"created_at"`
	ResolvedAt     *time.Time `json:"resolved_at"`
	LastError      *string    `json:"last_error"`
}

type ForgeConnection struct {
	ID             string    `json:"id"`
	OrgID          string    `json:"org_id"`
	ForgeType      string    `json:"forge_type"`
	DisplayName    string    `json:"display_name"`
	AppID          *string   `json:"app_id"`
	InstallationID *string   `json:"installation_id"`
	WebhookSecret  string    `json:"webhook_secret"`
	CredentialsEnc []byte    `json:"credentials_enc"`
	CreatedAt      time.Time `json:"created_at"`
}

type LoginAttempt struct {
	ID        string    `json:"id"`
	Email     string    `json:"email"`
	IpAddress *string   `json:"ip_address"`
	Success   bool      `json:"success"`
	CreatedAt time.Time `json:"created_at"`
}

type Machine struct {
	ID                       string         `json:"id"`
	PoolID                   string         `json:"pool_id"`
	Status                   string         `json:"status"`
	Provider                 string         `json:"provider"`
	ProviderRef              *string        `json:"provider_ref"`
	InstanceType             *string        `json:"instance_type"`
	Region                   *string        `json:"region"`
	Zone                     *string        `json:"zone"`
	CapacityType             *string        `json:"capacity_type"`
	PricePerHourUsd          pgtype.Numeric `json:"price_per_hour_usd"`
	AcceptedOffer            []byte         `json:"accepted_offer"`
	CpuMillis                int64          `json:"cpu_millis"`
	MemoryMb                 int64          `json:"memory_mb"`
	DiskGb                   int64          `json:"disk_gb"`
	Arch                     string         `json:"arch"`
	Os                       string         `json:"os"`
	Labels                   []byte         `json:"labels"`
	Hostname                 *string        `json:"hostname"`
	AgentVersion             *string        `json:"agent_version"`
	BootstrapTokenHash       *string        `json:"bootstrap_token_hash"`
	AgentTokenHash           *string        `json:"agent_token_hash"`
	BootDeadlineAt           *time.Time     `json:"boot_deadline_at"`
	HeartbeatIntervalSeconds int32          `json:"heartbeat_interval_seconds"`
	LastHeartbeatAt          *time.Time     `json:"last_heartbeat_at"`
	HeartbeatExpiresAt       *time.Time     `json:"heartbeat_expires_at"`
	StepsCompleted           int32          `json:"steps_completed"`
	IdleSince                *time.Time     `json:"idle_since"`
	DrainReason              *string        `json:"drain_reason"`
	RequestedAt              time.Time      `json:"requested_at"`
	ProvisionedAt            *time.Time     `json:"provisioned_at"`
	RegisteredAt             *time.Time     `json:"registered_at"`
	TerminatedAt             *time.Time     `json:"terminated_at"`
	UpdatedAt                time.Time      `json:"updated_at"`
}

type MachineEvent struct {
	ID         string    `json:"id"`
	MachineID  string    `json:"machine_id"`
	EventType  string    `json:"event_type"`
	FromStatus *string   `json:"from_status"`
	ToStatus   *string   `json:"to_status"`
	Actor      string    `json:"actor"`
	Reason     *string   `json:"reason"`
	Metadata   []byte    `json:"metadata"`
	CreatedAt  time.Time `json:"created_at"`
}

type MachinePool struct {
	ID             string         `json:"id"`
	Name           string         `json:"name"`
	Description    *string        `json:"description"`
	Provider       string         `json:"provider"`
	IsDefault      bool           `json:"is_default"`
	Arch           string         `json:"arch"`
	Cpu            string         `json:"cpu"`
	Memory         string         `json:"memory"`
	Disk           *string        `json:"disk"`
	GpuVendor      *string        `json:"gpu_vendor"`
	GpuModel       *string        `json:"gpu_model"`
	GpuCount       pgtype.Int4    `json:"gpu_count"`
	InstanceTypes  []string       `json:"instance_types"`
	Regions        []string       `json:"regions"`
	CapacityType   string         `json:"capacity_type"`
	Objective      string         `json:"objective"`
	MinWarm        int32          `json:"min_warm"`
	MaxMachines    int32          `json:"max_machines"`
	IdleTtlSeconds int32          `json:"idle_ttl_seconds"`
	Overrides      []byte         `json:"overrides"`
	HourlyCost     pgtype.Numeric `json:"hourly_cost"`
	DefaultTimeout *string        `json:"default_timeout"`
	JoinTokenHash  *string        `json:"join_token_hash"`
	Ready          bool           `json:"ready"`
	CreatedAt      time.Time      `json:"created_at"`
	UpdatedAt      time.Time      `json:"updated_at"`
}

type MfaPendingToken struct {
	Token     string    `json:"token"`
	UserID    string    `json:"user_id"`
	Email     string    `json:"email"`
	OrgID     string    `json:"org_id"`
	Attempts  int32     `json:"attempts"`
	Purpose   string    `json:"purpose"`
	ExpiresAt time.Time `json:"expires_at"`
	CreatedAt time.Time `json:"created_at"`
}

type Org struct {
	ID                      string    `json:"id"`
	Name                    string    `json:"name"`
	Slug                    string    `json:"slug"`
	CreatedAt               time.Time `json:"created_at"`
	ConcurrencyLimit        int32     `json:"concurrency_limit"`
	RequireProjectWorkspace bool      `json:"require_project_workspace"`
	SsoStrictGroups         bool      `json:"sso_strict_groups"`
	RequireSso              bool      `json:"require_sso"`
}

type PersonalToken struct {
	ID         string     `json:"id"`
	UserID     string     `json:"user_id"`
	Name       string     `json:"name"`
	TokenHash  string     `json:"token_hash"`
	ExpiresAt  *time.Time `json:"expires_at"`
	LastUsedAt *time.Time `json:"last_used_at"`
	CreatedAt  time.Time  `json:"created_at"`
}

type PipelineModule struct {
	ID            string    `json:"id"`
	OrgID         *string   `json:"org_id"`
	Name          string    `json:"name"`
	Description   *string   `json:"description"`
	OciRef        string    `json:"oci_ref"`
	SchemaVersion string    `json:"schema_version"`
	InputsSchema  []byte    `json:"inputs_schema"`
	OutputsSchema []byte    `json:"outputs_schema"`
	CreatedAt     time.Time `json:"created_at"`
}

type PipelineRun struct {
	ID               string      `json:"id"`
	ProjectID        *string     `json:"project_id"`
	OrgID            string      `json:"org_id"`
	WorkflowFile     *string     `json:"workflow_file"`
	TriggerType      string      `json:"trigger_type"`
	TriggerRef       *string     `json:"trigger_ref"`
	CommitSha        *string     `json:"commit_sha"`
	CommitMessage    *string     `json:"commit_message"`
	TriggeredBy      *string     `json:"triggered_by"`
	Status           string      `json:"status"`
	StartedAt        time.Time   `json:"started_at"`
	FinishedAt       *time.Time  `json:"finished_at"`
	DurationMs       pgtype.Int4 `json:"duration_ms"`
	CreatedAt        time.Time   `json:"created_at"`
	WorkflowID       *string     `json:"workflow_id"`
	Branch           *string     `json:"branch"`
	Repo             *string     `json:"repo"`
	Environment      *string     `json:"environment"`
	ErrorMessage     *string     `json:"error_message"`
	Kind             string      `json:"kind"`
	CleanedAt        *time.Time  `json:"cleaned_at"`
	ConcurrencyGroup *string     `json:"concurrency_group"`
}

type Project struct {
	ID                string    `json:"id"`
	OrgID             string    `json:"org_id"`
	ForgeID           string    `json:"forge_id"`
	RepoPath          string    `json:"repo_path"`
	RepoUrl           string    `json:"repo_url"`
	DisplayName       *string   `json:"display_name"`
	Description       *string   `json:"description"`
	Colour            string    `json:"colour"`
	Icon              *string   `json:"icon"`
	Tags              []string  `json:"tags"`
	DefaultBranch     string    `json:"default_branch"`
	PipelineSource    []byte    `json:"pipeline_source"`
	IsArchived        bool      `json:"is_archived"`
	CreatedAt         time.Time `json:"created_at"`
	UpdatedAt         time.Time `json:"updated_at"`
	WorkspaceID       string    `json:"workspace_id"`
	WorkspaceInferred bool      `json:"workspace_inferred"`
	ForgeWebhookID    *string   `json:"forge_webhook_id"`
}

type ProjectFavourite struct {
	UserID    string `json:"user_id"`
	ProjectID string `json:"project_id"`
}

type ProtectedEnvironment struct {
	ID             string    `json:"id"`
	OrgID          string    `json:"org_id"`
	Name           string    `json:"name"`
	MinRole        string    `json:"min_role"`
	Approvers      []string  `json:"approvers"`
	DeployBranches []string  `json:"deploy_branches"`
	DeployWindow   []byte    `json:"deploy_window"`
	CreatedAt      time.Time `json:"created_at"`
}

type Role struct {
	ID          string    `json:"id"`
	OrgID       string    `json:"org_id"`
	Name        string    `json:"name"`
	Slug        string    `json:"slug"`
	Description *string   `json:"description"`
	IsSystem    bool      `json:"is_system"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
	RequireMfa  bool      `json:"require_mfa"`
}

type RoleAssignment struct {
	Subject   string    `json:"subject"`
	RoleID    string    `json:"role_id"`
	CreatedAt time.Time `json:"created_at"`
	Source    string    `json:"source"`
}

type RoleEnvironmentScope struct {
	RoleID        string `json:"role_id"`
	EnvironmentID string `json:"environment_id"`
}

type RolePermission struct {
	RoleID string `json:"role_id"`
	Object string `json:"object"`
	Action string `json:"action"`
}

type RoleWorkspaceScope struct {
	RoleID      string `json:"role_id"`
	WorkspaceID string `json:"workspace_id"`
}

type SamlUsedAssertion struct {
	AssertionID string    `json:"assertion_id"`
	ExpiresAt   time.Time `json:"expires_at"`
}

type SavedView struct {
	ID          string    `json:"id"`
	OrgID       string    `json:"org_id"`
	OwnerUserID string    `json:"owner_user_id"`
	Name        string    `json:"name"`
	Route       string    `json:"route"`
	Selector    []byte    `json:"selector"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

type ScimToken struct {
	ID         string     `json:"id"`
	OrgID      string     `json:"org_id"`
	TokenHash  string     `json:"token_hash"`
	CreatedAt  time.Time  `json:"created_at"`
	LastUsedAt *time.Time `json:"last_used_at"`
}

type Secret struct {
	ID             string    `json:"id"`
	OrgID          string    `json:"org_id"`
	ProjectID      *string   `json:"project_id"`
	Name           string    `json:"name"`
	EncryptedValue []byte    `json:"encrypted_value"`
	CreatedBy      *string   `json:"created_by"`
	CreatedAt      time.Time `json:"created_at"`
	UpdatedAt      time.Time `json:"updated_at"`
	Environment    *string   `json:"environment"`
}

type Session struct {
	ID             string     `json:"id"`
	UserID         string     `json:"user_id"`
	TokenHash      string     `json:"token_hash"`
	IdpTokenEnc    []byte     `json:"idp_token_enc"`
	LogoutStateEnc []byte     `json:"logout_state_enc"`
	IpAddress      *string    `json:"ip_address"`
	UserAgent      *string    `json:"user_agent"`
	CreatedAt      time.Time  `json:"created_at"`
	LastActivity   time.Time  `json:"last_activity"`
	LastSyncedAt   *time.Time `json:"last_synced_at"`
	ExpiresAt      time.Time  `json:"expires_at"`
	IdleExpiresAt  time.Time  `json:"idle_expires_at"`
	RevokedAt      *time.Time `json:"revoked_at"`
}

type Signal struct {
	ID         string    `json:"id"`
	WorkflowID string    `json:"workflow_id"`
	SignalName string    `json:"signal_name"`
	Payload    []byte    `json:"payload"`
	Consumed   bool      `json:"consumed"`
	CreatedAt  time.Time `json:"created_at"`
}

type SsoGroupRoleMapping struct {
	ID        string    `json:"id"`
	OrgID     string    `json:"org_id"`
	GroupName string    `json:"group_name"`
	RoleID    string    `json:"role_id"`
	CreatedAt time.Time `json:"created_at"`
}

type Step struct {
	ID                   string     `json:"id"`
	WorkflowID           string     `json:"workflow_id"`
	Name                 string     `json:"name"`
	ExecType             string     `json:"exec_type"`
	Status               string     `json:"status"`
	Wave                 int32      `json:"wave"`
	Attempt              int32      `json:"attempt"`
	MaxAttempts          int32      `json:"max_attempts"`
	StepDef              []byte     `json:"step_def"`
	Result               []byte     `json:"result"`
	DispatchHandle       *string    `json:"dispatch_handle"`
	TaskToken            *string    `json:"task_token"`
	OnFailure            string     `json:"on_failure"`
	TimeoutSeconds       int32      `json:"timeout_seconds"`
	RetryBackoff         string     `json:"retry_backoff"`
	RetryIntervalSeconds int32      `json:"retry_interval_seconds"`
	CreatedAt            time.Time  `json:"created_at"`
	QueuedAt             *time.Time `json:"queued_at"`
	StartedAt            *time.Time `json:"started_at"`
	FinishedAt           *time.Time `json:"finished_at"`
	DeadlineAt           *time.Time `json:"deadline_at"`
	DispatchedAt         *time.Time `json:"dispatched_at"`
}

type StepAssignment struct {
	ID              string     `json:"id"`
	StepID          string     `json:"step_id"`
	WorkflowID      string     `json:"workflow_id"`
	RunID           string     `json:"run_id"`
	StepName        string     `json:"step_name"`
	Attempt         int32      `json:"attempt"`
	PoolID          string     `json:"pool_id"`
	MachineID       *string    `json:"machine_id"`
	Status          string     `json:"status"`
	CpuMillis       int64      `json:"cpu_millis"`
	MemoryMb        int64      `json:"memory_mb"`
	DiskGb          int64      `json:"disk_gb"`
	Payload         []byte     `json:"payload"`
	CancelRequested bool       `json:"cancel_requested"`
	Error           *string    `json:"error"`
	CreatedAt       time.Time  `json:"created_at"`
	AssignedAt      *time.Time `json:"assigned_at"`
	ClaimDeadlineAt *time.Time `json:"claim_deadline_at"`
	StartedAt       *time.Time `json:"started_at"`
	FinishedAt      *time.Time `json:"finished_at"`
}

type TagKey struct {
	ID            string    `json:"id"`
	OrgID         string    `json:"org_id"`
	Key           string    `json:"key"`
	Label         string    `json:"label"`
	AllowedValues []string  `json:"allowed_values"`
	Color         string    `json:"color"`
	CreatedAt     time.Time `json:"created_at"`
}

type Team struct {
	ID       string  `json:"id"`
	OrgID    string  `json:"org_id"`
	Name     string  `json:"name"`
	Slug     string  `json:"slug"`
	Source   string  `json:"source"`
	IdpGroup *string `json:"idp_group"`
}

type TeamMember struct {
	TeamID string `json:"team_id"`
	UserID string `json:"user_id"`
}

type Timer struct {
	ID         string    `json:"id"`
	WorkflowID string    `json:"workflow_id"`
	StepName   string    `json:"step_name"`
	TimerType  string    `json:"timer_type"`
	FiresAt    time.Time `json:"fires_at"`
	Fired      bool      `json:"fired"`
	CreatedAt  time.Time `json:"created_at"`
}

type User struct {
	ID                  string      `json:"id"`
	OrgID               string      `json:"org_id"`
	Email               string      `json:"email"`
	ExternalID          string      `json:"external_id"`
	Name                *string     `json:"name"`
	AvatarUrl           *string     `json:"avatar_url"`
	CreatedAt           time.Time   `json:"created_at"`
	IsActive            bool        `json:"is_active"`
	PasswordHash        *string     `json:"password_hash"`
	TotpSecretEnc       []byte      `json:"totp_secret_enc"`
	TotpVerified        bool        `json:"totp_verified"`
	MfaRequiredOverride pgtype.Bool `json:"mfa_required_override"`
	PasswordChangedAt   *time.Time  `json:"password_changed_at"`
	RecoveryCodes       []string    `json:"recovery_codes"`
	ForcePasswordChange bool        `json:"force_password_change"`
	MfaLastUsedPeriod   pgtype.Int8 `json:"mfa_last_used_period"`
	ThemeMode           *string     `json:"theme_mode"`
	ColorTheme          *string     `json:"color_theme"`
}

type Webhook struct {
	ID        string    `json:"id"`
	ProjectID string    `json:"project_id"`
	Url       string    `json:"url"`
	Secret    string    `json:"secret"`
	Events    []byte    `json:"events"`
	IsActive  bool      `json:"is_active"`
	CreatedAt time.Time `json:"created_at"`
}

type Workflow struct {
	ID           string     `json:"id"`
	RunID        string     `json:"run_id"`
	ParentID     *string    `json:"parent_id"`
	ParentStep   *string    `json:"parent_step"`
	Status       string     `json:"status"`
	Input        []byte     `json:"input"`
	Output       []byte     `json:"output"`
	PipelineYaml []byte     `json:"pipeline_yaml"`
	PipelineDef  []byte     `json:"pipeline_def"`
	DagWaves     []byte     `json:"dag_waves"`
	StepOutputs  []byte     `json:"step_outputs"`
	CreatedAt    time.Time  `json:"created_at"`
	StartedAt    *time.Time `json:"started_at"`
	FinishedAt   *time.Time `json:"finished_at"`
	CancelledAt  *time.Time `json:"cancelled_at"`
}

type WorkflowSchedule struct {
	ID         string     `json:"id"`
	OrgID      string     `json:"org_id"`
	Name       string     `json:"name"`
	Cron       string     `json:"cron"`
	Definition string     `json:"definition"`
	Enabled    bool       `json:"enabled"`
	NextRunAt  time.Time  `json:"next_run_at"`
	LastRunAt  *time.Time `json:"last_run_at"`
	CreatedAt  time.Time  `json:"created_at"`
	UpdatedAt  time.Time  `json:"updated_at"`
}

type Workspace struct {
	ID          string    `json:"id"`
	OrgID       string    `json:"org_id"`
	Name        string    `json:"name"`
	Slug        string    `json:"slug"`
	Description *string   `json:"description"`
	IsDefault   bool      `json:"is_default"`
	CreatedAt   time.Time `json:"created_at"`
}
