// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: outbox.sql

package db

import (
	"context"
)

const claimOutboxBatch = `-- name: ClaimOutboxBatch :many
UPDATE flint_outbox SET status = 'processing', attempts = attempts + 1, claimed_at = now()
WHERE id IN (
    SELECT id FROM flint_outbox
    WHERE status = 'pending' AND process_after <= now()
    ORDER BY created_at
    LIMIT $1
    FOR UPDATE SKIP LOCKED
)
RETURNING id, event_type, payload, attempts, max_attempts
`

type ClaimOutboxBatchRow struct {
	ID          string `json:"id"`
	EventType   string `json:"event_type"`
	Payload     []byte `json:"payload"`
	Attempts    int32  `json:"attempts"`
	MaxAttempts int32  `json:"max_attempts"`
}

// claimed_at stamps when the event entered 'processing' so RecoverStaleOutboxEvents
// can detect events stranded by a worker crash mid-delivery.
func (q *Queries) ClaimOutboxBatch(ctx context.Context, limit int32) ([]ClaimOutboxBatchRow, error) {
	rows, err := q.db.Query(ctx, claimOutboxBatch, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ClaimOutboxBatchRow{}
	for rows.Next() {
		var i ClaimOutboxBatchRow
		if err := rows.Scan(
			&i.ID,
			&i.EventType,
			&i.Payload,
			&i.Attempts,
			&i.MaxAttempts,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const cleanFailedOutbox = `-- name: CleanFailedOutbox :exec
DELETE FROM flint_outbox WHERE status = 'failed' AND created_at < now() - interval '30 days'
`

// Terminally-failed events are kept for a window so an operator can see what
// stopped delivering, then pruned. Without this they are the one outbox status
// that accumulates forever — CleanResolvedOutbox only prunes successes.
func (q *Queries) CleanFailedOutbox(ctx context.Context) error {
	_, err := q.db.Exec(ctx, cleanFailedOutbox)
	return err
}

const cleanResolvedOutbox = `-- name: CleanResolvedOutbox :exec
DELETE FROM flint_outbox WHERE status = 'resolved' AND resolved_at < now() - interval '7 days'
`

func (q *Queries) CleanResolvedOutbox(ctx context.Context) error {
	_, err := q.db.Exec(ctx, cleanResolvedOutbox)
	return err
}

const failOutboxEvent = `-- name: FailOutboxEvent :exec
UPDATE flint_outbox SET
    status = CASE WHEN attempts >= max_attempts THEN 'failed' ELSE 'pending' END,
    last_error = $2,
    process_after = now() + make_interval(secs := power(2, attempts) * 5 * (0.8 + random() * 0.4))
WHERE id = $1
`

type FailOutboxEventParams struct {
	ID        string  `json:"id"`
	LastError *string `json:"last_error"`
}

// Exponential backoff with ±20% jitter (0.8–1.2×) to avoid a thundering herd of
// webhook retries all firing in lockstep when an endpoint recovers. Mirrors the
// step-retry jitter in backoffDuration.
func (q *Queries) FailOutboxEvent(ctx context.Context, arg FailOutboxEventParams) error {
	_, err := q.db.Exec(ctx, failOutboxEvent, arg.ID, arg.LastError)
	return err
}

const insertOutboxEvent = `-- name: InsertOutboxEvent :exec
INSERT INTO flint_outbox (event_type, payload, idempotency_key, max_attempts)
VALUES ($1, $2, $3, $4)
ON CONFLICT (idempotency_key) DO NOTHING
`

type InsertOutboxEventParams struct {
	EventType      string `json:"event_type"`
	Payload        []byte `json:"payload"`
	IdempotencyKey string `json:"idempotency_key"`
	MaxAttempts    int32  `json:"max_attempts"`
}

func (q *Queries) InsertOutboxEvent(ctx context.Context, arg InsertOutboxEventParams) error {
	_, err := q.db.Exec(ctx, insertOutboxEvent,
		arg.EventType,
		arg.Payload,
		arg.IdempotencyKey,
		arg.MaxAttempts,
	)
	return err
}

const recoverStaleOutboxEvents = `-- name: RecoverStaleOutboxEvents :execrows
UPDATE flint_outbox SET
    status = CASE WHEN attempts >= max_attempts THEN 'failed' ELSE 'pending' END,
    last_error = COALESCE(last_error, 'delivery stranded in processing')
WHERE status = 'processing' AND claimed_at < now() - interval '5 minutes'
`

// Returns events stranded in 'processing' (worker crashed between claim and
// resolve/fail) back to 'pending' for redelivery.
//
// The attempt budget is enforced HERE as well as in FailOutboxEvent. attempts is
// incremented at claim, but only FailOutboxEvent converts an exhausted budget
// into 'failed' — and an event whose delivery reliably strands the worker never
// reaches it. Returning such an event to 'pending' unconditionally retried it
// every five minutes forever: the one delivery that can hang a worker, retried
// indefinitely, which is precisely the case the budget exists to stop.
func (q *Queries) RecoverStaleOutboxEvents(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, recoverStaleOutboxEvents)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const resolveOutboxEvent = `-- name: ResolveOutboxEvent :exec
UPDATE flint_outbox SET status = 'resolved', resolved_at = now()
WHERE id = $1
`

func (q *Queries) ResolveOutboxEvent(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, resolveOutboxEvent, id)
	return err
}
