// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: pipeline_runs.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const failRunWithError = `-- name: FailRunWithError :exec
UPDATE pipeline_runs SET status = 'failed', error_message = $2,
    finished_at = now(), duration_ms = EXTRACT(EPOCH FROM (now() - started_at)) * 1000
WHERE id = $1
`

type FailRunWithErrorParams struct {
	ID           string  `json:"id"`
	ErrorMessage *string `json:"error_message"`
}

func (q *Queries) FailRunWithError(ctx context.Context, arg FailRunWithErrorParams) error {
	_, err := q.db.Exec(ctx, failRunWithError, arg.ID, arg.ErrorMessage)
	return err
}

const finishRun = `-- name: FinishRun :exec
UPDATE pipeline_runs SET status = $2, finished_at = now(),
    duration_ms = EXTRACT(EPOCH FROM (now() - started_at)) * 1000
WHERE workflow_id = $1
`

type FinishRunParams struct {
	WorkflowID *string `json:"workflow_id"`
	Status     string  `json:"status"`
}

func (q *Queries) FinishRun(ctx context.Context, arg FinishRunParams) error {
	_, err := q.db.Exec(ctx, finishRun, arg.WorkflowID, arg.Status)
	return err
}

const getOriginalRunParams = `-- name: GetOriginalRunParams :one
SELECT project_id, org_id, workflow_file, trigger_ref, commit_sha, environment
FROM pipeline_runs WHERE id = $1
`

type GetOriginalRunParamsRow struct {
	ProjectID    *string `json:"project_id"`
	OrgID        string  `json:"org_id"`
	WorkflowFile *string `json:"workflow_file"`
	TriggerRef   *string `json:"trigger_ref"`
	CommitSha    *string `json:"commit_sha"`
	Environment  *string `json:"environment"`
}

func (q *Queries) GetOriginalRunParams(ctx context.Context, id string) (GetOriginalRunParamsRow, error) {
	row := q.db.QueryRow(ctx, getOriginalRunParams, id)
	var i GetOriginalRunParamsRow
	err := row.Scan(
		&i.ProjectID,
		&i.OrgID,
		&i.WorkflowFile,
		&i.TriggerRef,
		&i.CommitSha,
		&i.Environment,
	)
	return i, err
}

const getRun = `-- name: GetRun :one
SELECT id, project_id, workflow_file, trigger_type, trigger_ref, commit_sha,
       commit_message, triggered_by, status, started_at, finished_at, duration_ms,
       workflow_id, environment, error_message
FROM pipeline_runs
WHERE id = $1
`

type GetRunRow struct {
	ID            string      `json:"id"`
	ProjectID     *string     `json:"project_id"`
	WorkflowFile  *string     `json:"workflow_file"`
	TriggerType   string      `json:"trigger_type"`
	TriggerRef    *string     `json:"trigger_ref"`
	CommitSha     *string     `json:"commit_sha"`
	CommitMessage *string     `json:"commit_message"`
	TriggeredBy   *string     `json:"triggered_by"`
	Status        string      `json:"status"`
	StartedAt     time.Time   `json:"started_at"`
	FinishedAt    *time.Time  `json:"finished_at"`
	DurationMs    pgtype.Int4 `json:"duration_ms"`
	WorkflowID    *string     `json:"workflow_id"`
	Environment   *string     `json:"environment"`
	ErrorMessage  *string     `json:"error_message"`
}

func (q *Queries) GetRun(ctx context.Context, id string) (GetRunRow, error) {
	row := q.db.QueryRow(ctx, getRun, id)
	var i GetRunRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.WorkflowFile,
		&i.TriggerType,
		&i.TriggerRef,
		&i.CommitSha,
		&i.CommitMessage,
		&i.TriggeredBy,
		&i.Status,
		&i.StartedAt,
		&i.FinishedAt,
		&i.DurationMs,
		&i.WorkflowID,
		&i.Environment,
		&i.ErrorMessage,
	)
	return i, err
}

const getRunDetail = `-- name: GetRunDetail :one
SELECT pr.id, pr.status, pr.started_at, pr.finished_at, pr.duration_ms,
       pr.workflow_file, pr.trigger_ref AS branch, pr.trigger_type,
       pr.commit_sha, pr.commit_message, pr.triggered_by, pr.environment,
       pr.error_message,
       p.display_name AS project_name, p.id AS project_id,
       p.colour AS project_colour, p.repo_path,
       COALESCE((
         SELECT json_agg(json_build_object('name', s.name, 'status', s.status) ORDER BY s.wave, s.name)
         FROM steps s WHERE s.workflow_id = pr.workflow_id
       ), '[]')::jsonb AS steps
FROM pipeline_runs pr
JOIN projects p ON p.id = pr.project_id
WHERE pr.id = $1
`

type GetRunDetailRow struct {
	ID            string      `json:"id"`
	Status        string      `json:"status"`
	StartedAt     time.Time   `json:"started_at"`
	FinishedAt    *time.Time  `json:"finished_at"`
	DurationMs    pgtype.Int4 `json:"duration_ms"`
	WorkflowFile  *string     `json:"workflow_file"`
	Branch        *string     `json:"branch"`
	TriggerType   string      `json:"trigger_type"`
	CommitSha     *string     `json:"commit_sha"`
	CommitMessage *string     `json:"commit_message"`
	TriggeredBy   *string     `json:"triggered_by"`
	Environment   *string     `json:"environment"`
	ErrorMessage  *string     `json:"error_message"`
	ProjectName   *string     `json:"project_name"`
	ProjectID     string      `json:"project_id"`
	ProjectColour string      `json:"project_colour"`
	RepoPath      string      `json:"repo_path"`
	Steps         []byte      `json:"steps"`
}

// Single CI run with project display fields + the per-step summary, for
// GET /api/v1/runs/:id.
func (q *Queries) GetRunDetail(ctx context.Context, id string) (GetRunDetailRow, error) {
	row := q.db.QueryRow(ctx, getRunDetail, id)
	var i GetRunDetailRow
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.StartedAt,
		&i.FinishedAt,
		&i.DurationMs,
		&i.WorkflowFile,
		&i.Branch,
		&i.TriggerType,
		&i.CommitSha,
		&i.CommitMessage,
		&i.TriggeredBy,
		&i.Environment,
		&i.ErrorMessage,
		&i.ProjectName,
		&i.ProjectID,
		&i.ProjectColour,
		&i.RepoPath,
		&i.Steps,
	)
	return i, err
}

const getRunOrgID = `-- name: GetRunOrgID :one
SELECT org_id FROM pipeline_runs WHERE id = $1
`

func (q *Queries) GetRunOrgID(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRow(ctx, getRunOrgID, id)
	var org_id string
	err := row.Scan(&org_id)
	return org_id, err
}

const getRunScope = `-- name: GetRunScope :one
SELECT COALESCE(w.slug, '')::text AS workspace_slug,
       COALESCE(pr.environment, '')::text AS environment
FROM pipeline_runs pr
LEFT JOIN projects p ON p.id = pr.project_id
LEFT JOIN workspaces w ON w.id = p.workspace_id
WHERE pr.id = $1
`

type GetRunScopeRow struct {
	WorkspaceSlug string `json:"workspace_slug"`
	Environment   string `json:"environment"`
}

// Resolves the RBAC scope (workspace slug + environment) for a run, used by the
// authorization middleware. Workflow runs have no project, so both fall back to
// the empty string (the caller treats "" as the global "*" scope).
func (q *Queries) GetRunScope(ctx context.Context, id string) (GetRunScopeRow, error) {
	row := q.db.QueryRow(ctx, getRunScope, id)
	var i GetRunScopeRow
	err := row.Scan(&i.WorkspaceSlug, &i.Environment)
	return i, err
}

const getRunWorkflowID = `-- name: GetRunWorkflowID :one
SELECT workflow_id FROM pipeline_runs WHERE id = $1
`

func (q *Queries) GetRunWorkflowID(ctx context.Context, id string) (*string, error) {
	row := q.db.QueryRow(ctx, getRunWorkflowID, id)
	var workflow_id *string
	err := row.Scan(&workflow_id)
	return workflow_id, err
}

const insertManualRun = `-- name: InsertManualRun :exec
INSERT INTO pipeline_runs (id, project_id, org_id, workflow_file,
    trigger_type, trigger_ref, triggered_by, environment, status)
VALUES ($1, $2, $3, $4, 'manual', $5, 'api', $6, 'pending')
`

type InsertManualRunParams struct {
	ID           string  `json:"id"`
	ProjectID    *string `json:"project_id"`
	OrgID        string  `json:"org_id"`
	WorkflowFile *string `json:"workflow_file"`
	TriggerRef   *string `json:"trigger_ref"`
	Environment  *string `json:"environment"`
}

func (q *Queries) InsertManualRun(ctx context.Context, arg InsertManualRunParams) error {
	_, err := q.db.Exec(ctx, insertManualRun,
		arg.ID,
		arg.ProjectID,
		arg.OrgID,
		arg.WorkflowFile,
		arg.TriggerRef,
		arg.Environment,
	)
	return err
}

const insertPipelineRun = `-- name: InsertPipelineRun :exec
INSERT INTO pipeline_runs (id, project_id, org_id, workflow_file,
    trigger_type, trigger_ref, commit_sha, commit_message, triggered_by,
    environment, status)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, 'pending')
`

type InsertPipelineRunParams struct {
	ID            string  `json:"id"`
	ProjectID     *string `json:"project_id"`
	OrgID         string  `json:"org_id"`
	WorkflowFile  *string `json:"workflow_file"`
	TriggerType   string  `json:"trigger_type"`
	TriggerRef    *string `json:"trigger_ref"`
	CommitSha     *string `json:"commit_sha"`
	CommitMessage *string `json:"commit_message"`
	TriggeredBy   *string `json:"triggered_by"`
	Environment   *string `json:"environment"`
}

func (q *Queries) InsertPipelineRun(ctx context.Context, arg InsertPipelineRunParams) error {
	_, err := q.db.Exec(ctx, insertPipelineRun,
		arg.ID,
		arg.ProjectID,
		arg.OrgID,
		arg.WorkflowFile,
		arg.TriggerType,
		arg.TriggerRef,
		arg.CommitSha,
		arg.CommitMessage,
		arg.TriggeredBy,
		arg.Environment,
	)
	return err
}

const insertRetryRun = `-- name: InsertRetryRun :exec
INSERT INTO pipeline_runs (id, project_id, org_id, workflow_file,
    trigger_type, trigger_ref, commit_sha, triggered_by, environment, status)
VALUES ($1, $2, $3, $4, 'retry', $5, $6, 'api', $7, 'pending')
`

type InsertRetryRunParams struct {
	ID           string  `json:"id"`
	ProjectID    *string `json:"project_id"`
	OrgID        string  `json:"org_id"`
	WorkflowFile *string `json:"workflow_file"`
	TriggerRef   *string `json:"trigger_ref"`
	CommitSha    *string `json:"commit_sha"`
	Environment  *string `json:"environment"`
}

func (q *Queries) InsertRetryRun(ctx context.Context, arg InsertRetryRunParams) error {
	_, err := q.db.Exec(ctx, insertRetryRun,
		arg.ID,
		arg.ProjectID,
		arg.OrgID,
		arg.WorkflowFile,
		arg.TriggerRef,
		arg.CommitSha,
		arg.Environment,
	)
	return err
}

const insertWorkflowRun = `-- name: InsertWorkflowRun :exec
INSERT INTO pipeline_runs (id, org_id, kind, trigger_type, triggered_by, status)
VALUES ($1, $2, 'workflow', $3, $4, 'pending')
`

type InsertWorkflowRunParams struct {
	ID          string  `json:"id"`
	OrgID       string  `json:"org_id"`
	TriggerType string  `json:"trigger_type"`
	TriggeredBy *string `json:"triggered_by"`
}

// A non-CI workflow run: no project, no pipeline file. kind marks it 'workflow'.
func (q *Queries) InsertWorkflowRun(ctx context.Context, arg InsertWorkflowRunParams) error {
	_, err := q.db.Exec(ctx, insertWorkflowRun,
		arg.ID,
		arg.OrgID,
		arg.TriggerType,
		arg.TriggeredBy,
	)
	return err
}

const listRunsAll = `-- name: ListRunsAll :many
SELECT pr.id, pr.project_id, p.display_name AS project_name, p.colour AS project_colour,
       pr.status, pr.trigger_type, pr.trigger_ref, pr.commit_sha,
       pr.triggered_by, pr.started_at, pr.duration_ms, pr.error_message
FROM pipeline_runs pr
JOIN projects p ON pr.project_id = p.id
ORDER BY pr.started_at DESC
LIMIT $1
`

type ListRunsAllRow struct {
	ID            string      `json:"id"`
	ProjectID     *string     `json:"project_id"`
	ProjectName   *string     `json:"project_name"`
	ProjectColour string      `json:"project_colour"`
	Status        string      `json:"status"`
	TriggerType   string      `json:"trigger_type"`
	TriggerRef    *string     `json:"trigger_ref"`
	CommitSha     *string     `json:"commit_sha"`
	TriggeredBy   *string     `json:"triggered_by"`
	StartedAt     time.Time   `json:"started_at"`
	DurationMs    pgtype.Int4 `json:"duration_ms"`
	ErrorMessage  *string     `json:"error_message"`
}

func (q *Queries) ListRunsAll(ctx context.Context, limit int32) ([]ListRunsAllRow, error) {
	rows, err := q.db.Query(ctx, listRunsAll, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRunsAllRow{}
	for rows.Next() {
		var i ListRunsAllRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.ProjectName,
			&i.ProjectColour,
			&i.Status,
			&i.TriggerType,
			&i.TriggerRef,
			&i.CommitSha,
			&i.TriggeredBy,
			&i.StartedAt,
			&i.DurationMs,
			&i.ErrorMessage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRunsByProject = `-- name: ListRunsByProject :many
SELECT id, workflow_file, trigger_type, trigger_ref, commit_sha,
       commit_message, triggered_by, status, started_at, finished_at, duration_ms,
       error_message
FROM pipeline_runs
WHERE project_id = $1
ORDER BY started_at DESC
LIMIT $2
`

type ListRunsByProjectParams struct {
	ProjectID *string `json:"project_id"`
	Limit     int32   `json:"limit"`
}

type ListRunsByProjectRow struct {
	ID            string      `json:"id"`
	WorkflowFile  *string     `json:"workflow_file"`
	TriggerType   string      `json:"trigger_type"`
	TriggerRef    *string     `json:"trigger_ref"`
	CommitSha     *string     `json:"commit_sha"`
	CommitMessage *string     `json:"commit_message"`
	TriggeredBy   *string     `json:"triggered_by"`
	Status        string      `json:"status"`
	StartedAt     time.Time   `json:"started_at"`
	FinishedAt    *time.Time  `json:"finished_at"`
	DurationMs    pgtype.Int4 `json:"duration_ms"`
	ErrorMessage  *string     `json:"error_message"`
}

func (q *Queries) ListRunsByProject(ctx context.Context, arg ListRunsByProjectParams) ([]ListRunsByProjectRow, error) {
	rows, err := q.db.Query(ctx, listRunsByProject, arg.ProjectID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRunsByProjectRow{}
	for rows.Next() {
		var i ListRunsByProjectRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkflowFile,
			&i.TriggerType,
			&i.TriggerRef,
			&i.CommitSha,
			&i.CommitMessage,
			&i.TriggeredBy,
			&i.Status,
			&i.StartedAt,
			&i.FinishedAt,
			&i.DurationMs,
			&i.ErrorMessage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRunsFiltered = `-- name: ListRunsFiltered :many
SELECT pr.id, pr.status, pr.started_at, pr.finished_at, pr.duration_ms,
       pr.workflow_file, pr.trigger_ref AS branch, pr.trigger_type,
       pr.commit_sha, pr.commit_message, pr.triggered_by, pr.environment,
       pr.error_message,
       p.display_name AS project_name, p.id AS project_id,
       p.colour AS project_colour, p.repo_path,
       COALESCE((
         SELECT json_agg(json_build_object('name', s.name, 'status', s.status) ORDER BY s.wave, s.name)
         FROM steps s WHERE s.workflow_id = pr.workflow_id
       ), '[]')::jsonb AS steps
FROM pipeline_runs pr
JOIN projects p ON p.id = pr.project_id
WHERE ($1::text = '' OR pr.project_id::text = $1)
  AND ($2::text = '' OR pr.status = $2)
  AND (
    $3::text = ''
    -- NULLIF(...::text,'') keeps the param TEXT so pgx binds an empty first-page
    -- cursor without trying (and failing) to encode '' as a uuid.
    OR (pr.started_at, pr.id) < ($3::timestamptz, NULLIF($4::text, '')::uuid)
  )
ORDER BY pr.started_at DESC, pr.id DESC
LIMIT $5
`

type ListRunsFilteredParams struct {
	ProjectID string `json:"project_id"`
	Status    string `json:"status"`
	CursorTs  string `json:"cursor_ts"`
	CursorID  string `json:"cursor_id"`
	Lim       int32  `json:"lim"`
}

type ListRunsFilteredRow struct {
	ID            string      `json:"id"`
	Status        string      `json:"status"`
	StartedAt     time.Time   `json:"started_at"`
	FinishedAt    *time.Time  `json:"finished_at"`
	DurationMs    pgtype.Int4 `json:"duration_ms"`
	WorkflowFile  *string     `json:"workflow_file"`
	Branch        *string     `json:"branch"`
	TriggerType   string      `json:"trigger_type"`
	CommitSha     *string     `json:"commit_sha"`
	CommitMessage *string     `json:"commit_message"`
	TriggeredBy   *string     `json:"triggered_by"`
	Environment   *string     `json:"environment"`
	ErrorMessage  *string     `json:"error_message"`
	ProjectName   *string     `json:"project_name"`
	ProjectID     string      `json:"project_id"`
	ProjectColour string      `json:"project_colour"`
	RepoPath      string      `json:"repo_path"`
	Steps         []byte      `json:"steps"`
}

// Global CI run list with optional project/status filters, joined to the project
// for display, plus a compact per-step summary (name+status) the UI renders as
// stage pips. Powers GET /api/v1/runs.
func (q *Queries) ListRunsFiltered(ctx context.Context, arg ListRunsFilteredParams) ([]ListRunsFilteredRow, error) {
	rows, err := q.db.Query(ctx, listRunsFiltered,
		arg.ProjectID,
		arg.Status,
		arg.CursorTs,
		arg.CursorID,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRunsFilteredRow{}
	for rows.Next() {
		var i ListRunsFilteredRow
		if err := rows.Scan(
			&i.ID,
			&i.Status,
			&i.StartedAt,
			&i.FinishedAt,
			&i.DurationMs,
			&i.WorkflowFile,
			&i.Branch,
			&i.TriggerType,
			&i.CommitSha,
			&i.CommitMessage,
			&i.TriggeredBy,
			&i.Environment,
			&i.ErrorMessage,
			&i.ProjectName,
			&i.ProjectID,
			&i.ProjectColour,
			&i.RepoPath,
			&i.Steps,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkflowRuns = `-- name: ListWorkflowRuns :many
SELECT id, status, trigger_type, triggered_by, started_at, finished_at,
       duration_ms, error_message
FROM pipeline_runs
WHERE org_id = $1 AND kind = 'workflow'
  AND ( $2::text = ''
        OR started_at < $2::timestamptz
        -- NULLIF(...::text,'') keeps the param TEXT so an empty first-page cursor
        -- binds without pgx trying to encode '' as a uuid.
        OR (started_at = $2::timestamptz AND id < NULLIF($3::text, '')::uuid) )
ORDER BY started_at DESC, id DESC
LIMIT $4
`

type ListWorkflowRunsParams struct {
	OrgID    string `json:"org_id"`
	CursorTs string `json:"cursor_ts"`
	CursorID string `json:"cursor_id"`
	Lim      int32  `json:"lim"`
}

type ListWorkflowRunsRow struct {
	ID           string      `json:"id"`
	Status       string      `json:"status"`
	TriggerType  string      `json:"trigger_type"`
	TriggeredBy  *string     `json:"triggered_by"`
	StartedAt    time.Time   `json:"started_at"`
	FinishedAt   *time.Time  `json:"finished_at"`
	DurationMs   pgtype.Int4 `json:"duration_ms"`
	ErrorMessage *string     `json:"error_message"`
}

// Lists an org's workflow runs (kind = 'workflow'), newest first, with keyset
// pagination. The cursor is (started_at, id); an empty cursor returns the first
// page. Project-joining run queries can't serve these — workflow runs have no
// project.
func (q *Queries) ListWorkflowRuns(ctx context.Context, arg ListWorkflowRunsParams) ([]ListWorkflowRunsRow, error) {
	rows, err := q.db.Query(ctx, listWorkflowRuns,
		arg.OrgID,
		arg.CursorTs,
		arg.CursorID,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListWorkflowRunsRow{}
	for rows.Next() {
		var i ListWorkflowRunsRow
		if err := rows.Scan(
			&i.ID,
			&i.Status,
			&i.TriggerType,
			&i.TriggeredBy,
			&i.StartedAt,
			&i.FinishedAt,
			&i.DurationMs,
			&i.ErrorMessage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markRunCleaned = `-- name: MarkRunCleaned :exec
UPDATE pipeline_runs SET cleaned_at = now() WHERE id = $1
`

func (q *Queries) MarkRunCleaned(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, markRunCleaned, id)
	return err
}

const runExists = `-- name: RunExists :one
SELECT EXISTS(SELECT 1 FROM pipeline_runs WHERE id = $1)
`

func (q *Queries) RunExists(ctx context.Context, id string) (bool, error) {
	row := q.db.QueryRow(ctx, runExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const runsNeedingCleanup = `-- name: RunsNeedingCleanup :many
SELECT id FROM pipeline_runs
WHERE cleaned_at IS NULL AND status IN ('succeeded', 'failed', 'cancelled')
LIMIT $1
`

// Runs that reached a terminal state but whose executor resources (workspace
// pod, leftover Jobs) haven't been torn down yet. The loop claims these and
// calls each executor's CleanupRun, then marks them cleaned — exactly-once.
func (q *Queries) RunsNeedingCleanup(ctx context.Context, limit int32) ([]string, error) {
	rows, err := q.db.Query(ctx, runsNeedingCleanup, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchRuns = `-- name: SearchRuns :many
SELECT pr.id, pr.status, pr.trigger_ref AS branch, pr.commit_sha,
       COALESCE(p.display_name, p.repo_path)::text AS project_name,
       p.colour AS project_colour
FROM pipeline_runs pr
JOIN projects p ON p.id = pr.project_id
WHERE pr.org_id = $1
  AND (pr.trigger_ref ILIKE $2 OR pr.commit_sha ILIKE $2)
ORDER BY pr.started_at DESC
LIMIT 10
`

type SearchRunsParams struct {
	OrgID   string  `json:"org_id"`
	Pattern *string `json:"pattern"`
}

type SearchRunsRow struct {
	ID            string  `json:"id"`
	Status        string  `json:"status"`
	Branch        *string `json:"branch"`
	CommitSha     *string `json:"commit_sha"`
	ProjectName   string  `json:"project_name"`
	ProjectColour string  `json:"project_colour"`
}

// Run search by branch / commit SHA for the global ⌘K search.
func (q *Queries) SearchRuns(ctx context.Context, arg SearchRunsParams) ([]SearchRunsRow, error) {
	rows, err := q.db.Query(ctx, searchRuns, arg.OrgID, arg.Pattern)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchRunsRow{}
	for rows.Next() {
		var i SearchRunsRow
		if err := rows.Scan(
			&i.ID,
			&i.Status,
			&i.Branch,
			&i.CommitSha,
			&i.ProjectName,
			&i.ProjectColour,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRunStatus = `-- name: UpdateRunStatus :exec
UPDATE pipeline_runs SET status = $2 WHERE id = $1
`

type UpdateRunStatusParams struct {
	ID     string `json:"id"`
	Status string `json:"status"`
}

func (q *Queries) UpdateRunStatus(ctx context.Context, arg UpdateRunStatusParams) error {
	_, err := q.db.Exec(ctx, updateRunStatus, arg.ID, arg.Status)
	return err
}

const updateRunWorkflow = `-- name: UpdateRunWorkflow :execrows
UPDATE pipeline_runs SET workflow_id = $2, branch = $3, repo = $4, status = 'running' WHERE id = $1
`

type UpdateRunWorkflowParams struct {
	ID         string  `json:"id"`
	WorkflowID *string `json:"workflow_id"`
	Branch     *string `json:"branch"`
	Repo       *string `json:"repo"`
}

func (q *Queries) UpdateRunWorkflow(ctx context.Context, arg UpdateRunWorkflowParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateRunWorkflow,
		arg.ID,
		arg.WorkflowID,
		arg.Branch,
		arg.Repo,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
