// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: projects.sql

package db

import (
	"context"
	"time"
)

const archiveProject = `-- name: ArchiveProject :exec
UPDATE projects SET is_archived = true, updated_at = now() WHERE id = $1
`

func (q *Queries) ArchiveProject(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, archiveProject, id)
	return err
}

const getProject = `-- name: GetProject :one
SELECT id, repo_path, display_name, description, colour, tags, default_branch, is_archived, created_at
FROM projects
WHERE id = $1
`

type GetProjectRow struct {
	ID            string    `json:"id"`
	RepoPath      string    `json:"repo_path"`
	DisplayName   *string   `json:"display_name"`
	Description   *string   `json:"description"`
	Colour        string    `json:"colour"`
	Tags          []string  `json:"tags"`
	DefaultBranch string    `json:"default_branch"`
	IsArchived    bool      `json:"is_archived"`
	CreatedAt     time.Time `json:"created_at"`
}

func (q *Queries) GetProject(ctx context.Context, id string) (GetProjectRow, error) {
	row := q.db.QueryRow(ctx, getProject, id)
	var i GetProjectRow
	err := row.Scan(
		&i.ID,
		&i.RepoPath,
		&i.DisplayName,
		&i.Description,
		&i.Colour,
		&i.Tags,
		&i.DefaultBranch,
		&i.IsArchived,
		&i.CreatedAt,
	)
	return i, err
}

const getProjectByRepoPath = `-- name: GetProjectByRepoPath :one
SELECT p.id, p.org_id, p.pipeline_source->>'path' AS pipeline_path
FROM projects p
JOIN forge_connections fc ON p.forge_id = fc.id
WHERE p.repo_path = $1 AND p.is_archived = false
LIMIT 1
`

type GetProjectByRepoPathRow struct {
	ID           string      `json:"id"`
	OrgID        string      `json:"org_id"`
	PipelinePath interface{} `json:"pipeline_path"`
}

func (q *Queries) GetProjectByRepoPath(ctx context.Context, repoPath string) (GetProjectByRepoPathRow, error) {
	row := q.db.QueryRow(ctx, getProjectByRepoPath, repoPath)
	var i GetProjectByRepoPathRow
	err := row.Scan(&i.ID, &i.OrgID, &i.PipelinePath)
	return i, err
}

const getProjectOrgID = `-- name: GetProjectOrgID :one
SELECT org_id FROM projects WHERE id = $1
`

func (q *Queries) GetProjectOrgID(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRow(ctx, getProjectOrgID, id)
	var org_id string
	err := row.Scan(&org_id)
	return org_id, err
}

const getProjectRepoInfo = `-- name: GetProjectRepoInfo :one
SELECT repo_path, org_id, COALESCE(pipeline_source->>'path', '.flint/')::text AS pipeline_path
FROM projects WHERE id = $1
`

type GetProjectRepoInfoRow struct {
	RepoPath     string `json:"repo_path"`
	OrgID        string `json:"org_id"`
	PipelinePath string `json:"pipeline_path"`
}

func (q *Queries) GetProjectRepoInfo(ctx context.Context, id string) (GetProjectRepoInfoRow, error) {
	row := q.db.QueryRow(ctx, getProjectRepoInfo, id)
	var i GetProjectRepoInfoRow
	err := row.Scan(&i.RepoPath, &i.OrgID, &i.PipelinePath)
	return i, err
}

const listProjects = `-- name: ListProjects :many
SELECT id, repo_path, display_name, description, colour, tags, default_branch, is_archived, created_at
FROM projects
WHERE is_archived = false
ORDER BY display_name, repo_path
`

type ListProjectsRow struct {
	ID            string    `json:"id"`
	RepoPath      string    `json:"repo_path"`
	DisplayName   *string   `json:"display_name"`
	Description   *string   `json:"description"`
	Colour        string    `json:"colour"`
	Tags          []string  `json:"tags"`
	DefaultBranch string    `json:"default_branch"`
	IsArchived    bool      `json:"is_archived"`
	CreatedAt     time.Time `json:"created_at"`
}

func (q *Queries) ListProjects(ctx context.Context) ([]ListProjectsRow, error) {
	rows, err := q.db.Query(ctx, listProjects)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProjectsRow{}
	for rows.Next() {
		var i ListProjectsRow
		if err := rows.Scan(
			&i.ID,
			&i.RepoPath,
			&i.DisplayName,
			&i.Description,
			&i.Colour,
			&i.Tags,
			&i.DefaultBranch,
			&i.IsArchived,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertProject = `-- name: UpsertProject :one
INSERT INTO projects (
    org_id, forge_id, repo_path, repo_url, display_name, description,
    colour, icon, tags, default_branch, pipeline_source, is_archived, updated_at
)
SELECT
    fc.org_id, fc.id, $1, $2, $3, $4,
    $5, $6, $7, $8, $9::jsonb, false, now()
FROM forge_connections fc WHERE fc.display_name = $10
LIMIT 1
ON CONFLICT (forge_id, repo_path)
DO UPDATE SET
    display_name = EXCLUDED.display_name,
    description = EXCLUDED.description,
    colour = EXCLUDED.colour,
    icon = EXCLUDED.icon,
    tags = EXCLUDED.tags,
    default_branch = EXCLUDED.default_branch,
    pipeline_source = EXCLUDED.pipeline_source,
    is_archived = false,
    updated_at = now()
RETURNING id
`

type UpsertProjectParams struct {
	RepoPath       string   `json:"repo_path"`
	RepoUrl        string   `json:"repo_url"`
	DisplayName    *string  `json:"display_name"`
	Description    *string  `json:"description"`
	Colour         string   `json:"colour"`
	Icon           *string  `json:"icon"`
	Tags           []string `json:"tags"`
	DefaultBranch  string   `json:"default_branch"`
	PipelineSource []byte   `json:"pipeline_source"`
	ForgeRef       string   `json:"forge_ref"`
}

func (q *Queries) UpsertProject(ctx context.Context, arg UpsertProjectParams) (string, error) {
	row := q.db.QueryRow(ctx, upsertProject,
		arg.RepoPath,
		arg.RepoUrl,
		arg.DisplayName,
		arg.Description,
		arg.Colour,
		arg.Icon,
		arg.Tags,
		arg.DefaultBranch,
		arg.PipelineSource,
		arg.ForgeRef,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}
