// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: protected_environments.sql

package db

import (
	"context"
	"time"
)

const createProtectedEnvironment = `-- name: CreateProtectedEnvironment :one
INSERT INTO protected_environments (org_id, name, min_role, approvers, deploy_branches, deploy_window)
VALUES ($1, $2, $3, $4, $5, $6) RETURNING id
`

type CreateProtectedEnvironmentParams struct {
	OrgID          string   `json:"org_id"`
	Name           string   `json:"name"`
	MinRole        string   `json:"min_role"`
	Approvers      []string `json:"approvers"`
	DeployBranches []string `json:"deploy_branches"`
	DeployWindow   []byte   `json:"deploy_window"`
}

func (q *Queries) CreateProtectedEnvironment(ctx context.Context, arg CreateProtectedEnvironmentParams) (string, error) {
	row := q.db.QueryRow(ctx, createProtectedEnvironment,
		arg.OrgID,
		arg.Name,
		arg.MinRole,
		arg.Approvers,
		arg.DeployBranches,
		arg.DeployWindow,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}

const deleteProtectedEnvironment = `-- name: DeleteProtectedEnvironment :execrows
DELETE FROM protected_environments WHERE id = $1
`

func (q *Queries) DeleteProtectedEnvironment(ctx context.Context, id string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteProtectedEnvironment, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getProtectedEnvironment = `-- name: GetProtectedEnvironment :one
SELECT id, name, min_role, approvers, deploy_branches, deploy_window, created_at
FROM protected_environments WHERE org_id = $1 AND name = $2
`

type GetProtectedEnvironmentParams struct {
	OrgID string `json:"org_id"`
	Name  string `json:"name"`
}

type GetProtectedEnvironmentRow struct {
	ID             string    `json:"id"`
	Name           string    `json:"name"`
	MinRole        string    `json:"min_role"`
	Approvers      []string  `json:"approvers"`
	DeployBranches []string  `json:"deploy_branches"`
	DeployWindow   []byte    `json:"deploy_window"`
	CreatedAt      time.Time `json:"created_at"`
}

func (q *Queries) GetProtectedEnvironment(ctx context.Context, arg GetProtectedEnvironmentParams) (GetProtectedEnvironmentRow, error) {
	row := q.db.QueryRow(ctx, getProtectedEnvironment, arg.OrgID, arg.Name)
	var i GetProtectedEnvironmentRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.MinRole,
		&i.Approvers,
		&i.DeployBranches,
		&i.DeployWindow,
		&i.CreatedAt,
	)
	return i, err
}

const listProtectedEnvironments = `-- name: ListProtectedEnvironments :many
SELECT id, name, min_role, approvers, deploy_branches, deploy_window, created_at
FROM protected_environments WHERE org_id = $1 ORDER BY name
`

type ListProtectedEnvironmentsRow struct {
	ID             string    `json:"id"`
	Name           string    `json:"name"`
	MinRole        string    `json:"min_role"`
	Approvers      []string  `json:"approvers"`
	DeployBranches []string  `json:"deploy_branches"`
	DeployWindow   []byte    `json:"deploy_window"`
	CreatedAt      time.Time `json:"created_at"`
}

func (q *Queries) ListProtectedEnvironments(ctx context.Context, orgID string) ([]ListProtectedEnvironmentsRow, error) {
	rows, err := q.db.Query(ctx, listProtectedEnvironments, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProtectedEnvironmentsRow{}
	for rows.Next() {
		var i ListProtectedEnvironmentsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.MinRole,
			&i.Approvers,
			&i.DeployBranches,
			&i.DeployWindow,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProtectedEnvironment = `-- name: UpdateProtectedEnvironment :execrows
UPDATE protected_environments SET
    min_role = $2, approvers = $3, deploy_branches = $4, deploy_window = $5
WHERE id = $1
`

type UpdateProtectedEnvironmentParams struct {
	ID             string   `json:"id"`
	MinRole        string   `json:"min_role"`
	Approvers      []string `json:"approvers"`
	DeployBranches []string `json:"deploy_branches"`
	DeployWindow   []byte   `json:"deploy_window"`
}

func (q *Queries) UpdateProtectedEnvironment(ctx context.Context, arg UpdateProtectedEnvironmentParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateProtectedEnvironment,
		arg.ID,
		arg.MinRole,
		arg.Approvers,
		arg.DeployBranches,
		arg.DeployWindow,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
