// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
	"net/netip"
)

type Querier interface {
	AddTeamMember(ctx context.Context, arg AddTeamMemberParams) error
	ArchiveProject(ctx context.Context, id string) error
	CancelAllWorkflowTimers(ctx context.Context, workflowID string) error
	CancelChildWorkflows(ctx context.Context, parentID *string) error
	CancelPendingSteps(ctx context.Context, workflowID string) error
	CancelTimer(ctx context.Context, arg CancelTimerParams) error
	CancelWorkflow(ctx context.Context, id string) error
	CheckMFARequiredForUser(ctx context.Context, subject string) (bool, error)
	ClaimOutboxBatch(ctx context.Context, limit int32) ([]ClaimOutboxBatchRow, error)
	ClaimQueuedSteps(ctx context.Context, limit int32) ([]ClaimQueuedStepsRow, error)
	CleanResolvedOutbox(ctx context.Context) error
	CleanupFiredTimers(ctx context.Context) error
	CleanupOldLoginAttempts(ctx context.Context) error
	ClearForcePasswordChange(ctx context.Context, id string) error
	ClearUserTOTP(ctx context.Context, id string) error
	CompleteParentInvokeStep(ctx context.Context, arg CompleteParentInvokeStepParams) error
	ConsumeSignal(ctx context.Context, id string) error
	ConsumeStepResultSignals(ctx context.Context, workflowID string) ([][]byte, error)
	CountActiveProjects(ctx context.Context) (int64, error)
	CountPendingGates(ctx context.Context) (int64, error)
	CountRecentFailuresByEmail(ctx context.Context, email string) (int64, error)
	CountRecentFailuresByIP(ctx context.Context, ipAddress netip.Addr) (int64, error)
	CountRoleAssignments(ctx context.Context, subject string) (int64, error)
	CountRunningPipelines(ctx context.Context) (int64, error)
	CountRunningStepsByOrg(ctx context.Context, orgID string) (int64, error)
	CountUsers(ctx context.Context, orgID string) (int64, error)
	CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) (string, error)
	CreateEnvVariable(ctx context.Context, arg CreateEnvVariableParams) (string, error)
	CreateEnvironment(ctx context.Context, arg CreateEnvironmentParams) (string, error)
	CreateLocalUser(ctx context.Context, arg CreateLocalUserParams) (string, error)
	CreateProtectedEnvironment(ctx context.Context, arg CreateProtectedEnvironmentParams) (string, error)
	CreateRetryStep(ctx context.Context, arg CreateRetryStepParams) error
	CreateRole(ctx context.Context, arg CreateRoleParams) (string, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (string, error)
	CreateTeam(ctx context.Context, arg CreateTeamParams) (string, error)
	CreateTimer(ctx context.Context, arg CreateTimerParams) error
	CreateWebhook(ctx context.Context, arg CreateWebhookParams) (string, error)
	CreateWorkspace(ctx context.Context, arg CreateWorkspaceParams) (string, error)
	DeleteAPIKey(ctx context.Context, id string) (int64, error)
	DeleteAPIKeyEnvironmentScopes(ctx context.Context, apiKeyID string) error
	DeleteAPIKeyWorkspaceScopes(ctx context.Context, apiKeyID string) error
	DeleteAuthProviderConfig(ctx context.Context, providerType string) (int64, error)
	DeleteEnvVariable(ctx context.Context, id string) error
	DeleteEnvVariableValue(ctx context.Context, arg DeleteEnvVariableValueParams) error
	DeleteEnvironment(ctx context.Context, id string) error
	DeleteExpiredSessions(ctx context.Context) error
	DeleteForgeConnection(ctx context.Context, id string) (int64, error)
	DeleteForgeConnectionByID(ctx context.Context, id string) error
	DeleteProtectedEnvironment(ctx context.Context, id string) (int64, error)
	DeleteRole(ctx context.Context, id string) (int64, error)
	DeleteRoleAssignment(ctx context.Context, arg DeleteRoleAssignmentParams) error
	DeleteRoleEnvironmentScopes(ctx context.Context, roleID string) error
	DeleteRolePermissions(ctx context.Context, roleID string) error
	DeleteRoleWorkspaceScopes(ctx context.Context, roleID string) error
	DeleteRunnerPool(ctx context.Context, name string) error
	DeleteSecret(ctx context.Context, arg DeleteSecretParams) (int64, error)
	DeleteTeam(ctx context.Context, id string) (int64, error)
	DeleteWebhook(ctx context.Context, arg DeleteWebhookParams) error
	DeleteWorkspace(ctx context.Context, id string) (int64, error)
	FailGateByTimeout(ctx context.Context, arg FailGateByTimeoutParams) error
	FailOutboxEvent(ctx context.Context, arg FailOutboxEventParams) error
	FailRunWithError(ctx context.Context, arg FailRunWithErrorParams) error
	FailStepByTimeout(ctx context.Context, arg FailStepByTimeoutParams) error
	FinishRun(ctx context.Context, arg FinishRunParams) error
	FinishWorkflow(ctx context.Context, arg FinishWorkflowParams) error
	FireDueTimers(ctx context.Context) ([]FireDueTimersRow, error)
	GetActiveWebhooksForEvent(ctx context.Context, arg GetActiveWebhooksForEventParams) ([]GetActiveWebhooksForEventRow, error)
	GetAuthProviderConfig(ctx context.Context, providerType string) (AuthProviderConfig, error)
	GetCloneCredentials(ctx context.Context, repoPath string) (GetCloneCredentialsRow, error)
	GetDashboardActivity(ctx context.Context, limit int32) ([]GetDashboardActivityRow, error)
	GetDashboardSummary(ctx context.Context) ([]GetDashboardSummaryRow, error)
	GetEnvVariable(ctx context.Context, id string) (GetEnvVariableRow, error)
	GetEnvironment(ctx context.Context, id string) (GetEnvironmentRow, error)
	GetExistingWorkflow(ctx context.Context, runID string) (string, error)
	GetGlobalVariableValue(ctx context.Context, variableID string) (string, error)
	GetModuleByName(ctx context.Context, name string) (GetModuleByNameRow, error)
	GetOrCreateDefaultOrg(ctx context.Context) (string, error)
	GetOrCreateTeamBySlug(ctx context.Context, arg GetOrCreateTeamBySlugParams) (string, error)
	GetOrg(ctx context.Context) (GetOrgRow, error)
	GetOrgConcurrencyLimit(ctx context.Context, id string) (int32, error)
	GetOriginalRunParams(ctx context.Context, id string) (GetOriginalRunParamsRow, error)
	GetProject(ctx context.Context, id string) (GetProjectRow, error)
	GetProjectByRepoPath(ctx context.Context, repoPath string) (GetProjectByRepoPathRow, error)
	GetProjectOrgID(ctx context.Context, id string) (string, error)
	GetProjectRepoInfo(ctx context.Context, id string) (GetProjectRepoInfoRow, error)
	GetProjectWorkspaceSlug(ctx context.Context, id string) (string, error)
	GetProtectedEnvironment(ctx context.Context, arg GetProtectedEnvironmentParams) (GetProtectedEnvironmentRow, error)
	GetRoleBySlug(ctx context.Context, arg GetRoleBySlugParams) (GetRoleBySlugRow, error)
	GetRun(ctx context.Context, id string) (GetRunRow, error)
	GetRunOrgID(ctx context.Context, id string) (string, error)
	GetRunWorkflowID(ctx context.Context, id string) (*string, error)
	GetSecret(ctx context.Context, arg GetSecretParams) ([]byte, error)
	GetSecretByEnvironment(ctx context.Context, arg GetSecretByEnvironmentParams) (GetSecretByEnvironmentRow, error)
	GetSessionByTokenHash(ctx context.Context, tokenHash string) (GetSessionByTokenHashRow, error)
	GetStepByWorkflowAndName(ctx context.Context, arg GetStepByWorkflowAndNameParams) (GetStepByWorkflowAndNameRow, error)
	GetStepStatus(ctx context.Context, arg GetStepStatusParams) (string, error)
	GetUserByEmail(ctx context.Context, arg GetUserByEmailParams) (GetUserByEmailRow, error)
	GetUserByID(ctx context.Context, id string) (GetUserByIDRow, error)
	GetUserForAuth(ctx context.Context, arg GetUserForAuthParams) (GetUserForAuthRow, error)
	GetUserRecoveryCodes(ctx context.Context, id string) ([]string, error)
	GetWebhookSecret(ctx context.Context, forgeType string) (string, error)
	GetWebhookSecretByName(ctx context.Context, displayName string) (string, error)
	GetWorkflowDAGWaves(ctx context.Context, id string) ([]byte, error)
	GetWorkflowInput(ctx context.Context, id string) ([]byte, error)
	GetWorkflowParent(ctx context.Context, id string) (GetWorkflowParentRow, error)
	GetWorkflowStatus(ctx context.Context, id string) (GetWorkflowStatusRow, error)
	GetWorkspaceByID(ctx context.Context, id string) (GetWorkspaceByIDRow, error)
	GetWorkspaceBySlug(ctx context.Context, arg GetWorkspaceBySlugParams) (GetWorkspaceBySlugRow, error)
	GlobalVariableValueExists(ctx context.Context, variableID string) (bool, error)
	InsertAPIKeyEnvironmentScope(ctx context.Context, arg InsertAPIKeyEnvironmentScopeParams) error
	InsertAPIKeyWorkspaceScope(ctx context.Context, arg InsertAPIKeyWorkspaceScopeParams) error
	InsertAuditEntry(ctx context.Context, arg InsertAuditEntryParams) error
	InsertForgeConnection(ctx context.Context, arg InsertForgeConnectionParams) (string, error)
	InsertManualRun(ctx context.Context, arg InsertManualRunParams) error
	InsertOutboxEvent(ctx context.Context, arg InsertOutboxEventParams) error
	InsertPipelineRun(ctx context.Context, arg InsertPipelineRunParams) error
	InsertRetryRun(ctx context.Context, arg InsertRetryRunParams) error
	InsertRoleAssignment(ctx context.Context, arg InsertRoleAssignmentParams) error
	InsertRoleEnvironmentScope(ctx context.Context, arg InsertRoleEnvironmentScopeParams) error
	InsertRolePermission(ctx context.Context, arg InsertRolePermissionParams) error
	InsertRoleWorkspaceScope(ctx context.Context, arg InsertRoleWorkspaceScopeParams) error
	InsertSignal(ctx context.Context, arg InsertSignalParams) error
	InsertStep(ctx context.Context, arg InsertStepParams) error
	InsertWorkflow(ctx context.Context, arg InsertWorkflowParams) (string, error)
	IsEnvVariableSecret(ctx context.Context, id string) (bool, error)
	IsUserInTeamBySlug(ctx context.Context, arg IsUserInTeamBySlugParams) (bool, error)
	LatestStepsByWorkflow(ctx context.Context, workflowID string) ([]LatestStepsByWorkflowRow, error)
	// ────────────────────────────────────────────────────────────
	// API key environment scope
	// ────────────────────────────────────────────────────────────
	ListAPIKeyEnvironmentSlugs(ctx context.Context, apiKeyID string) ([]string, error)
	// ────────────────────────────────────────────────────────────
	// API key workspace scope
	// ────────────────────────────────────────────────────────────
	ListAPIKeyWorkspaceSlugs(ctx context.Context, apiKeyID string) ([]string, error)
	ListAPIKeys(ctx context.Context, orgID string) ([]ListAPIKeysRow, error)
	// ────────────────────────────────────────────────────────────
	// Role assignments
	// ────────────────────────────────────────────────────────────
	ListAllRoleAssignments(ctx context.Context) ([]ListAllRoleAssignmentsRow, error)
	ListAllSecrets(ctx context.Context) ([]ListAllSecretsRow, error)
	ListAuditLog(ctx context.Context, arg ListAuditLogParams) ([]ListAuditLogRow, error)
	ListAuthProviderConfigNames(ctx context.Context) ([]ListAuthProviderConfigNamesRow, error)
	ListEnvVariableValues(ctx context.Context, orgID string) ([]ListEnvVariableValuesRow, error)
	ListEnvVariables(ctx context.Context, orgID string) ([]ListEnvVariablesRow, error)
	ListEnvironments(ctx context.Context, orgID string) ([]ListEnvironmentsRow, error)
	ListForgeConnectionNames(ctx context.Context) ([]ListForgeConnectionNamesRow, error)
	ListForgeConnections(ctx context.Context, orgID string) ([]ListForgeConnectionsRow, error)
	ListModules(ctx context.Context) ([]ListModulesRow, error)
	ListOrgSecrets(ctx context.Context, orgID string) ([]ListOrgSecretsRow, error)
	ListPendingGates(ctx context.Context) ([]ListPendingGatesRow, error)
	ListProjectSecrets(ctx context.Context, projectID *string) ([]ListProjectSecretsRow, error)
	ListProjectWebhooks(ctx context.Context, projectID string) ([]Webhook, error)
	ListProjects(ctx context.Context) ([]ListProjectsRow, error)
	ListProtectedEnvironments(ctx context.Context, orgID string) ([]ListProtectedEnvironmentsRow, error)
	ListRoleAssignmentsByRole(ctx context.Context, roleID string) ([]ListRoleAssignmentsByRoleRow, error)
	ListRoleAssignmentsBySubject(ctx context.Context, subject string) ([]ListRoleAssignmentsBySubjectRow, error)
	// ────────────────────────────────────────────────────────────
	// Role environment scope
	// ────────────────────────────────────────────────────────────
	ListRoleEnvironmentNames(ctx context.Context, roleID string) ([]string, error)
	// ────────────────────────────────────────────────────────────
	// Role permissions
	// ────────────────────────────────────────────────────────────
	ListRolePermissions(ctx context.Context, roleID string) ([]ListRolePermissionsRow, error)
	// ────────────────────────────────────────────────────────────
	// Role workspace scope
	// ────────────────────────────────────────────────────────────
	ListRoleWorkspaceSlugs(ctx context.Context, roleID string) ([]string, error)
	ListRoles(ctx context.Context, orgID string) ([]ListRolesRow, error)
	ListRunnerPoolNames(ctx context.Context) ([]string, error)
	ListRunnerPools(ctx context.Context) ([]ListRunnerPoolsRow, error)
	ListRunsAll(ctx context.Context, limit int32) ([]ListRunsAllRow, error)
	ListRunsByProject(ctx context.Context, arg ListRunsByProjectParams) ([]ListRunsByProjectRow, error)
	ListSecrets(ctx context.Context, arg ListSecretsParams) ([]ListSecretsRow, error)
	ListSessionsForSync(ctx context.Context, arg ListSessionsForSyncParams) ([]ListSessionsForSyncRow, error)
	ListStepsByWorkflow(ctx context.Context, workflowID string) ([]ListStepsByWorkflowRow, error)
	ListTeamMembers(ctx context.Context, teamID string) ([]ListTeamMembersRow, error)
	ListTeams(ctx context.Context) ([]ListTeamsRow, error)
	ListUserIdpTeams(ctx context.Context, userID string) ([]ListUserIdpTeamsRow, error)
	ListUserSessions(ctx context.Context, userID string) ([]ListUserSessionsRow, error)
	ListUserTeamIDs(ctx context.Context, userID string) ([]string, error)
	ListUserTeams(ctx context.Context, userID string) ([]ListUserTeamsRow, error)
	ListUsers(ctx context.Context, orgID string) ([]ListUsersRow, error)
	ListValidAPIKeys(ctx context.Context) ([]ListValidAPIKeysRow, error)
	ListWaitingGatesWithRejectSignals(ctx context.Context) ([]ListWaitingGatesWithRejectSignalsRow, error)
	ListWaitingGatesWithSignals(ctx context.Context) ([]ListWaitingGatesWithSignalsRow, error)
	ListWorkspaces(ctx context.Context, orgID string) ([]ListWorkspacesRow, error)
	LockStep(ctx context.Context, arg LockStepParams) (LockStepRow, error)
	LockWorkflow(ctx context.Context, id string) (LockWorkflowRow, error)
	NotifyEngine(ctx context.Context, pgNotify string) error
	RecentlyFailedWorkflowIDs(ctx context.Context) ([]string, error)
	RecentlyFinishedRunIDs(ctx context.Context) ([]string, error)
	RecordLoginAttempt(ctx context.Context, arg RecordLoginAttemptParams) error
	RemoveTeamMember(ctx context.Context, arg RemoveTeamMemberParams) (int64, error)
	RemoveUserFromAllTeams(ctx context.Context, userID string) (int64, error)
	RequeueRetryStep(ctx context.Context, arg RequeueRetryStepParams) error
	// Returns resolved env variable name/value pairs for a given org.
	// For global vars: returns the single value (environment_id IS NULL).
	// For environment-scoped vars: returns the value matching the env slug.
	// Excludes is_secret=true (those go through the agent secrets flow).
	ResolveEnvVars(ctx context.Context, arg ResolveEnvVarsParams) ([]ResolveEnvVarsRow, error)
	ResolveOutboxEvent(ctx context.Context, id string) error
	RevokeSession(ctx context.Context, id string) error
	RevokeSessionByHash(ctx context.Context, tokenHash string) error
	RevokeUserSessions(ctx context.Context, userID string) error
	RoleExists(ctx context.Context, arg RoleExistsParams) (bool, error)
	RotateSessionToken(ctx context.Context, arg RotateSessionTokenParams) error
	RunExists(ctx context.Context, id string) (bool, error)
	SearchUsers(ctx context.Context, arg SearchUsersParams) ([]SearchUsersRow, error)
	SetStepK8sJobName(ctx context.Context, arg SetStepK8sJobNameParams) error
	SetStepQueued(ctx context.Context, id string) error
	SetStepSkipped(ctx context.Context, id string) error
	SetStepStatus(ctx context.Context, arg SetStepStatusParams) error
	SetStepTaskToken(ctx context.Context, arg SetStepTaskTokenParams) error
	SetUserRecoveryCodes(ctx context.Context, arg SetUserRecoveryCodesParams) error
	SetUserTOTPSecret(ctx context.Context, arg SetUserTOTPSecretParams) error
	SweepStaleRunningSteps(ctx context.Context) (int64, error)
	SweepStaleWorkflows(ctx context.Context) error
	TouchAPIKey(ctx context.Context, id string) error
	UpdateForgeConnectionByName(ctx context.Context, arg UpdateForgeConnectionByNameParams) (string, error)
	UpdateProtectedEnvironment(ctx context.Context, arg UpdateProtectedEnvironmentParams) (int64, error)
	UpdateRunStatus(ctx context.Context, arg UpdateRunStatusParams) error
	UpdateRunWorkflow(ctx context.Context, arg UpdateRunWorkflowParams) (int64, error)
	UpdateSecretValue(ctx context.Context, arg UpdateSecretValueParams) error
	UpdateSessionIdpToken(ctx context.Context, arg UpdateSessionIdpTokenParams) error
	UpdateSessionSyncedAt(ctx context.Context, id string) error
	UpdateStepOutputs(ctx context.Context, arg UpdateStepOutputsParams) error
	UpdateStepResult(ctx context.Context, arg UpdateStepResultParams) error
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error
	UpdateWorkflowPipeline(ctx context.Context, arg UpdateWorkflowPipelineParams) error
	UpsertAuthProviderConfig(ctx context.Context, arg UpsertAuthProviderConfigParams) (string, error)
	UpsertEnvVariableValue(ctx context.Context, arg UpsertEnvVariableValueParams) error
	UpsertProject(ctx context.Context, arg UpsertProjectParams) (string, error)
	UpsertRunnerPool(ctx context.Context, arg UpsertRunnerPoolParams) error
	UpsertSecret(ctx context.Context, arg UpsertSecretParams) error
	UpsertTimer(ctx context.Context, arg UpsertTimerParams) error
	UpsertUser(ctx context.Context, arg UpsertUserParams) (string, error)
	VerifyUserTOTP(ctx context.Context, id string) error
}

var _ Querier = (*Queries)(nil)
