// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: role_scopes.sql

package db

import (
	"context"
)

const countRoleAssignments = `-- name: CountRoleAssignments :one
SELECT COUNT(*) FROM role_assignments WHERE subject = $1
`

func (q *Queries) CountRoleAssignments(ctx context.Context, subject string) (int64, error) {
	row := q.db.QueryRow(ctx, countRoleAssignments, subject)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteIdpRoleAssignment = `-- name: DeleteIdpRoleAssignment :exec
DELETE FROM role_assignments WHERE subject = $1 AND role_id = $2 AND source = 'idp'
`

type DeleteIdpRoleAssignmentParams struct {
	Subject string `json:"subject"`
	RoleID  string `json:"role_id"`
}

func (q *Queries) DeleteIdpRoleAssignment(ctx context.Context, arg DeleteIdpRoleAssignmentParams) error {
	_, err := q.db.Exec(ctx, deleteIdpRoleAssignment, arg.Subject, arg.RoleID)
	return err
}

const deleteRoleAssignment = `-- name: DeleteRoleAssignment :exec
DELETE FROM role_assignments WHERE subject = $1 AND role_id = $2
`

type DeleteRoleAssignmentParams struct {
	Subject string `json:"subject"`
	RoleID  string `json:"role_id"`
}

func (q *Queries) DeleteRoleAssignment(ctx context.Context, arg DeleteRoleAssignmentParams) error {
	_, err := q.db.Exec(ctx, deleteRoleAssignment, arg.Subject, arg.RoleID)
	return err
}

const deleteRoleEnvironmentScopes = `-- name: DeleteRoleEnvironmentScopes :exec
DELETE FROM role_environment_scope WHERE role_id = $1
`

func (q *Queries) DeleteRoleEnvironmentScopes(ctx context.Context, roleID string) error {
	_, err := q.db.Exec(ctx, deleteRoleEnvironmentScopes, roleID)
	return err
}

const deleteRolePermissions = `-- name: DeleteRolePermissions :exec
DELETE FROM role_permissions WHERE role_id = $1
`

func (q *Queries) DeleteRolePermissions(ctx context.Context, roleID string) error {
	_, err := q.db.Exec(ctx, deleteRolePermissions, roleID)
	return err
}

const deleteRoleWorkspaceScopes = `-- name: DeleteRoleWorkspaceScopes :exec
DELETE FROM role_workspace_scope WHERE role_id = $1
`

func (q *Queries) DeleteRoleWorkspaceScopes(ctx context.Context, roleID string) error {
	_, err := q.db.Exec(ctx, deleteRoleWorkspaceScopes, roleID)
	return err
}

const insertIdpRoleAssignment = `-- name: InsertIdpRoleAssignment :exec
INSERT INTO role_assignments (subject, role_id, source, created_at)
VALUES ($1, $2, 'idp', now())
ON CONFLICT (subject, role_id) DO NOTHING
`

type InsertIdpRoleAssignmentParams struct {
	Subject string `json:"subject"`
	RoleID  string `json:"role_id"`
}

// IdP-derived assignment from a group→role mapping. Never downgrades an existing
// (manual) 'internal' row.
func (q *Queries) InsertIdpRoleAssignment(ctx context.Context, arg InsertIdpRoleAssignmentParams) error {
	_, err := q.db.Exec(ctx, insertIdpRoleAssignment, arg.Subject, arg.RoleID)
	return err
}

const insertRoleAssignment = `-- name: InsertRoleAssignment :exec
INSERT INTO role_assignments (subject, role_id, source, created_at)
VALUES ($1, $2, 'internal', now())
ON CONFLICT (subject, role_id) DO UPDATE SET source = 'internal'
`

type InsertRoleAssignmentParams struct {
	Subject string `json:"subject"`
	RoleID  string `json:"role_id"`
}

// Manual/authoritative assignment. Marks the row source='internal' so SSO group
// sync will never remove it, even if an 'idp' row already existed.
func (q *Queries) InsertRoleAssignment(ctx context.Context, arg InsertRoleAssignmentParams) error {
	_, err := q.db.Exec(ctx, insertRoleAssignment, arg.Subject, arg.RoleID)
	return err
}

const insertRoleEnvironmentScope = `-- name: InsertRoleEnvironmentScope :exec
INSERT INTO role_environment_scope (role_id, environment_id)
SELECT $1, id FROM environments WHERE slug = $2
ON CONFLICT DO NOTHING
`

type InsertRoleEnvironmentScopeParams struct {
	RoleID string `json:"role_id"`
	Slug   string `json:"slug"`
}

func (q *Queries) InsertRoleEnvironmentScope(ctx context.Context, arg InsertRoleEnvironmentScopeParams) error {
	_, err := q.db.Exec(ctx, insertRoleEnvironmentScope, arg.RoleID, arg.Slug)
	return err
}

const insertRolePermission = `-- name: InsertRolePermission :exec
INSERT INTO role_permissions (role_id, object, action)
VALUES ($1, $2, $3)
ON CONFLICT DO NOTHING
`

type InsertRolePermissionParams struct {
	RoleID string `json:"role_id"`
	Object string `json:"object"`
	Action string `json:"action"`
}

func (q *Queries) InsertRolePermission(ctx context.Context, arg InsertRolePermissionParams) error {
	_, err := q.db.Exec(ctx, insertRolePermission, arg.RoleID, arg.Object, arg.Action)
	return err
}

const insertRoleWorkspaceScope = `-- name: InsertRoleWorkspaceScope :exec
INSERT INTO role_workspace_scope (role_id, workspace_id)
SELECT $1, id FROM workspaces WHERE slug = $2
ON CONFLICT DO NOTHING
`

type InsertRoleWorkspaceScopeParams struct {
	RoleID string `json:"role_id"`
	Slug   string `json:"slug"`
}

func (q *Queries) InsertRoleWorkspaceScope(ctx context.Context, arg InsertRoleWorkspaceScopeParams) error {
	_, err := q.db.Exec(ctx, insertRoleWorkspaceScope, arg.RoleID, arg.Slug)
	return err
}

const listAllRoleAssignments = `-- name: ListAllRoleAssignments :many

SELECT subject, role_id FROM role_assignments
`

type ListAllRoleAssignmentsRow struct {
	Subject string `json:"subject"`
	RoleID  string `json:"role_id"`
}

// ────────────────────────────────────────────────────────────
// Role assignments
// ────────────────────────────────────────────────────────────
func (q *Queries) ListAllRoleAssignments(ctx context.Context) ([]ListAllRoleAssignmentsRow, error) {
	rows, err := q.db.Query(ctx, listAllRoleAssignments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAllRoleAssignmentsRow{}
	for rows.Next() {
		var i ListAllRoleAssignmentsRow
		if err := rows.Scan(&i.Subject, &i.RoleID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllRoleAssignmentsWithRole = `-- name: ListAllRoleAssignmentsWithRole :many
SELECT ra.subject, r.slug AS role
FROM role_assignments ra
JOIN roles r ON r.id = ra.role_id
ORDER BY ra.subject
`

type ListAllRoleAssignmentsWithRoleRow struct {
	Subject string `json:"subject"`
	Role    string `json:"role"`
}

func (q *Queries) ListAllRoleAssignmentsWithRole(ctx context.Context) ([]ListAllRoleAssignmentsWithRoleRow, error) {
	rows, err := q.db.Query(ctx, listAllRoleAssignmentsWithRole)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAllRoleAssignmentsWithRoleRow{}
	for rows.Next() {
		var i ListAllRoleAssignmentsWithRoleRow
		if err := rows.Scan(&i.Subject, &i.Role); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIdpRoleAssignmentRoleIDs = `-- name: ListIdpRoleAssignmentRoleIDs :many
SELECT role_id FROM role_assignments WHERE subject = $1 AND source = 'idp'
`

func (q *Queries) ListIdpRoleAssignmentRoleIDs(ctx context.Context, subject string) ([]string, error) {
	rows, err := q.db.Query(ctx, listIdpRoleAssignmentRoleIDs, subject)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var role_id string
		if err := rows.Scan(&role_id); err != nil {
			return nil, err
		}
		items = append(items, role_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoleAssignmentsByRole = `-- name: ListRoleAssignmentsByRole :many
SELECT subject, role_id FROM role_assignments WHERE role_id = $1
`

type ListRoleAssignmentsByRoleRow struct {
	Subject string `json:"subject"`
	RoleID  string `json:"role_id"`
}

func (q *Queries) ListRoleAssignmentsByRole(ctx context.Context, roleID string) ([]ListRoleAssignmentsByRoleRow, error) {
	rows, err := q.db.Query(ctx, listRoleAssignmentsByRole, roleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRoleAssignmentsByRoleRow{}
	for rows.Next() {
		var i ListRoleAssignmentsByRoleRow
		if err := rows.Scan(&i.Subject, &i.RoleID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoleAssignmentsBySubject = `-- name: ListRoleAssignmentsBySubject :many
SELECT subject, role_id FROM role_assignments WHERE subject = $1
`

type ListRoleAssignmentsBySubjectRow struct {
	Subject string `json:"subject"`
	RoleID  string `json:"role_id"`
}

func (q *Queries) ListRoleAssignmentsBySubject(ctx context.Context, subject string) ([]ListRoleAssignmentsBySubjectRow, error) {
	rows, err := q.db.Query(ctx, listRoleAssignmentsBySubject, subject)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRoleAssignmentsBySubjectRow{}
	for rows.Next() {
		var i ListRoleAssignmentsBySubjectRow
		if err := rows.Scan(&i.Subject, &i.RoleID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoleEnvironmentNames = `-- name: ListRoleEnvironmentNames :many

SELECT e.name FROM role_environment_scope res
JOIN environments e ON e.id = res.environment_id
WHERE res.role_id = $1
`

// ────────────────────────────────────────────────────────────
// Role environment scope
// ────────────────────────────────────────────────────────────
func (q *Queries) ListRoleEnvironmentNames(ctx context.Context, roleID string) ([]string, error) {
	rows, err := q.db.Query(ctx, listRoleEnvironmentNames, roleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoleIDsForGroups = `-- name: ListRoleIDsForGroups :many
SELECT DISTINCT role_id FROM sso_group_role_mappings
WHERE org_id = $1 AND group_name = ANY($2::text[])
`

type ListRoleIDsForGroupsParams struct {
	OrgID  string   `json:"org_id"`
	Groups []string `json:"groups"`
}

func (q *Queries) ListRoleIDsForGroups(ctx context.Context, arg ListRoleIDsForGroupsParams) ([]string, error) {
	rows, err := q.db.Query(ctx, listRoleIDsForGroups, arg.OrgID, arg.Groups)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var role_id string
		if err := rows.Scan(&role_id); err != nil {
			return nil, err
		}
		items = append(items, role_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRolePermissions = `-- name: ListRolePermissions :many

SELECT object, action FROM role_permissions WHERE role_id = $1
`

type ListRolePermissionsRow struct {
	Object string `json:"object"`
	Action string `json:"action"`
}

// ────────────────────────────────────────────────────────────
// Role permissions
// ────────────────────────────────────────────────────────────
func (q *Queries) ListRolePermissions(ctx context.Context, roleID string) ([]ListRolePermissionsRow, error) {
	rows, err := q.db.Query(ctx, listRolePermissions, roleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRolePermissionsRow{}
	for rows.Next() {
		var i ListRolePermissionsRow
		if err := rows.Scan(&i.Object, &i.Action); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoleWorkspaceSlugs = `-- name: ListRoleWorkspaceSlugs :many

SELECT w.slug FROM role_workspace_scope rws
JOIN workspaces w ON w.id = rws.workspace_id
WHERE rws.role_id = $1
`

// ────────────────────────────────────────────────────────────
// Role workspace scope
// ────────────────────────────────────────────────────────────
func (q *Queries) ListRoleWorkspaceSlugs(ctx context.Context, roleID string) ([]string, error) {
	rows, err := q.db.Query(ctx, listRoleWorkspaceSlugs, roleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var slug string
		if err := rows.Scan(&slug); err != nil {
			return nil, err
		}
		items = append(items, slug)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
