// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: roles.sql

package db

import (
	"context"
	"time"
)

const createRole = `-- name: CreateRole :one
INSERT INTO roles (org_id, name, slug, description, is_system)
VALUES ($1, $2, $3, $4, $5) RETURNING id
`

type CreateRoleParams struct {
	OrgID       string  `json:"org_id"`
	Name        string  `json:"name"`
	Slug        string  `json:"slug"`
	Description *string `json:"description"`
	IsSystem    bool    `json:"is_system"`
}

func (q *Queries) CreateRole(ctx context.Context, arg CreateRoleParams) (string, error) {
	row := q.db.QueryRow(ctx, createRole,
		arg.OrgID,
		arg.Name,
		arg.Slug,
		arg.Description,
		arg.IsSystem,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}

const deleteRole = `-- name: DeleteRole :execrows
DELETE FROM roles WHERE id = $1 AND is_system = false
`

func (q *Queries) DeleteRole(ctx context.Context, id string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteRole, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getRoleByID = `-- name: GetRoleByID :one
SELECT id, name, slug, description, is_system, created_at
FROM roles WHERE id = $1
`

type GetRoleByIDRow struct {
	ID          string    `json:"id"`
	Name        string    `json:"name"`
	Slug        string    `json:"slug"`
	Description *string   `json:"description"`
	IsSystem    bool      `json:"is_system"`
	CreatedAt   time.Time `json:"created_at"`
}

func (q *Queries) GetRoleByID(ctx context.Context, id string) (GetRoleByIDRow, error) {
	row := q.db.QueryRow(ctx, getRoleByID, id)
	var i GetRoleByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.IsSystem,
		&i.CreatedAt,
	)
	return i, err
}

const getRoleBySlug = `-- name: GetRoleBySlug :one
SELECT id, name, slug, description, is_system, created_at
FROM roles WHERE org_id = $1 AND slug = $2
`

type GetRoleBySlugParams struct {
	OrgID string `json:"org_id"`
	Slug  string `json:"slug"`
}

type GetRoleBySlugRow struct {
	ID          string    `json:"id"`
	Name        string    `json:"name"`
	Slug        string    `json:"slug"`
	Description *string   `json:"description"`
	IsSystem    bool      `json:"is_system"`
	CreatedAt   time.Time `json:"created_at"`
}

func (q *Queries) GetRoleBySlug(ctx context.Context, arg GetRoleBySlugParams) (GetRoleBySlugRow, error) {
	row := q.db.QueryRow(ctx, getRoleBySlug, arg.OrgID, arg.Slug)
	var i GetRoleBySlugRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.IsSystem,
		&i.CreatedAt,
	)
	return i, err
}

const listRoles = `-- name: ListRoles :many
SELECT id, name, slug, description, is_system, created_at
FROM roles WHERE org_id = $1 ORDER BY is_system DESC, name
LIMIT $2 OFFSET $3
`

type ListRolesParams struct {
	OrgID  string `json:"org_id"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

type ListRolesRow struct {
	ID          string    `json:"id"`
	Name        string    `json:"name"`
	Slug        string    `json:"slug"`
	Description *string   `json:"description"`
	IsSystem    bool      `json:"is_system"`
	CreatedAt   time.Time `json:"created_at"`
}

func (q *Queries) ListRoles(ctx context.Context, arg ListRolesParams) ([]ListRolesRow, error) {
	rows, err := q.db.Query(ctx, listRoles, arg.OrgID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRolesRow{}
	for rows.Next() {
		var i ListRolesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.IsSystem,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const roleExists = `-- name: RoleExists :one
SELECT EXISTS(SELECT 1 FROM roles WHERE org_id = $1 AND slug = $2) AS role_exists
`

type RoleExistsParams struct {
	OrgID string `json:"org_id"`
	Slug  string `json:"slug"`
}

func (q *Queries) RoleExists(ctx context.Context, arg RoleExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, roleExists, arg.OrgID, arg.Slug)
	var role_exists bool
	err := row.Scan(&role_exists)
	return role_exists, err
}

const updateRole = `-- name: UpdateRole :execrows
UPDATE roles
SET name = COALESCE($1, name),
    description = COALESCE($2, description)
WHERE id = $3 AND is_system = false
`

type UpdateRoleParams struct {
	Name        *string `json:"name"`
	Description *string `json:"description"`
	ID          string  `json:"id"`
}

func (q *Queries) UpdateRole(ctx context.Context, arg UpdateRoleParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateRole, arg.Name, arg.Description, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
