// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: runner_pools.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteRunnerPool = `-- name: DeleteRunnerPool :exec
DELETE FROM runner_pools WHERE name = $1
`

func (q *Queries) DeleteRunnerPool(ctx context.Context, name string) error {
	_, err := q.db.Exec(ctx, deleteRunnerPool, name)
	return err
}

const listRunnerPoolNames = `-- name: ListRunnerPoolNames :many
SELECT name FROM runner_pools
`

func (q *Queries) ListRunnerPoolNames(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, listRunnerPoolNames)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRunnerPools = `-- name: ListRunnerPools :many
SELECT name, description, cpu, memory, gpu_vendor, gpu_model, gpu_count, arch, spot_preferred
FROM runner_pools WHERE ready = true ORDER BY name
`

type ListRunnerPoolsRow struct {
	Name          string      `json:"name"`
	Description   *string     `json:"description"`
	Cpu           string      `json:"cpu"`
	Memory        string      `json:"memory"`
	GpuVendor     *string     `json:"gpu_vendor"`
	GpuModel      *string     `json:"gpu_model"`
	GpuCount      pgtype.Int4 `json:"gpu_count"`
	Arch          string      `json:"arch"`
	SpotPreferred bool        `json:"spot_preferred"`
}

func (q *Queries) ListRunnerPools(ctx context.Context) ([]ListRunnerPoolsRow, error) {
	rows, err := q.db.Query(ctx, listRunnerPools)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRunnerPoolsRow{}
	for rows.Next() {
		var i ListRunnerPoolsRow
		if err := rows.Scan(
			&i.Name,
			&i.Description,
			&i.Cpu,
			&i.Memory,
			&i.GpuVendor,
			&i.GpuModel,
			&i.GpuCount,
			&i.Arch,
			&i.SpotPreferred,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRunnerPoolsPaged = `-- name: ListRunnerPoolsPaged :many
SELECT id, name, description, cpu, memory, arch, gpu_vendor, gpu_model, gpu_count, ready, created_at
FROM runner_pools ORDER BY name LIMIT $1 OFFSET $2
`

type ListRunnerPoolsPagedParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListRunnerPoolsPagedRow struct {
	ID          string      `json:"id"`
	Name        string      `json:"name"`
	Description *string     `json:"description"`
	Cpu         string      `json:"cpu"`
	Memory      string      `json:"memory"`
	Arch        string      `json:"arch"`
	GpuVendor   *string     `json:"gpu_vendor"`
	GpuModel    *string     `json:"gpu_model"`
	GpuCount    pgtype.Int4 `json:"gpu_count"`
	Ready       bool        `json:"ready"`
	CreatedAt   time.Time   `json:"created_at"`
}

func (q *Queries) ListRunnerPoolsPaged(ctx context.Context, arg ListRunnerPoolsPagedParams) ([]ListRunnerPoolsPagedRow, error) {
	rows, err := q.db.Query(ctx, listRunnerPoolsPaged, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRunnerPoolsPagedRow{}
	for rows.Next() {
		var i ListRunnerPoolsPagedRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Cpu,
			&i.Memory,
			&i.Arch,
			&i.GpuVendor,
			&i.GpuModel,
			&i.GpuCount,
			&i.Ready,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertRunnerPool = `-- name: UpsertRunnerPool :exec
INSERT INTO runner_pools (
    name, description, cpu, memory, gpu_vendor, gpu_model, gpu_count,
    arch, node_selector, tolerations, spot_preferred, spot_fallback,
    default_timeout, ready, updated_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, true, now())
ON CONFLICT (name) DO UPDATE SET
    description = EXCLUDED.description,
    cpu = EXCLUDED.cpu,
    memory = EXCLUDED.memory,
    gpu_vendor = EXCLUDED.gpu_vendor,
    gpu_model = EXCLUDED.gpu_model,
    gpu_count = EXCLUDED.gpu_count,
    arch = EXCLUDED.arch,
    node_selector = EXCLUDED.node_selector,
    tolerations = EXCLUDED.tolerations,
    spot_preferred = EXCLUDED.spot_preferred,
    spot_fallback = EXCLUDED.spot_fallback,
    default_timeout = EXCLUDED.default_timeout,
    ready = true,
    updated_at = now()
`

type UpsertRunnerPoolParams struct {
	Name           string      `json:"name"`
	Description    *string     `json:"description"`
	Cpu            string      `json:"cpu"`
	Memory         string      `json:"memory"`
	GpuVendor      *string     `json:"gpu_vendor"`
	GpuModel       *string     `json:"gpu_model"`
	GpuCount       pgtype.Int4 `json:"gpu_count"`
	Arch           string      `json:"arch"`
	NodeSelector   []byte      `json:"node_selector"`
	Tolerations    []byte      `json:"tolerations"`
	SpotPreferred  bool        `json:"spot_preferred"`
	SpotFallback   string      `json:"spot_fallback"`
	DefaultTimeout *string     `json:"default_timeout"`
}

func (q *Queries) UpsertRunnerPool(ctx context.Context, arg UpsertRunnerPoolParams) error {
	_, err := q.db.Exec(ctx, upsertRunnerPool,
		arg.Name,
		arg.Description,
		arg.Cpu,
		arg.Memory,
		arg.GpuVendor,
		arg.GpuModel,
		arg.GpuCount,
		arg.Arch,
		arg.NodeSelector,
		arg.Tolerations,
		arg.SpotPreferred,
		arg.SpotFallback,
		arg.DefaultTimeout,
	)
	return err
}
