// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: runner_pools.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const countDefaultRunnerPools = `-- name: CountDefaultRunnerPools :one
SELECT count(*) FROM runner_pools WHERE is_default = true
`

func (q *Queries) CountDefaultRunnerPools(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countDefaultRunnerPools)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteRunnerPool = `-- name: DeleteRunnerPool :exec
DELETE FROM runner_pools WHERE name = $1
`

func (q *Queries) DeleteRunnerPool(ctx context.Context, name string) error {
	_, err := q.db.Exec(ctx, deleteRunnerPool, name)
	return err
}

const getRunnerPool = `-- name: GetRunnerPool :one
SELECT name, description, cpu, memory, gpu_vendor, gpu_model, gpu_count, arch,
       node_selector, tolerations, default_timeout,
       service_account_name, workspace_mode, workspace_storage_class, workspace_size,
       run_as_non_root, mode, managed_spec, is_default
FROM runner_pools WHERE name = $1
`

type GetRunnerPoolRow struct {
	Name                  string      `json:"name"`
	Description           *string     `json:"description"`
	Cpu                   string      `json:"cpu"`
	Memory                string      `json:"memory"`
	GpuVendor             *string     `json:"gpu_vendor"`
	GpuModel              *string     `json:"gpu_model"`
	GpuCount              pgtype.Int4 `json:"gpu_count"`
	Arch                  string      `json:"arch"`
	NodeSelector          []byte      `json:"node_selector"`
	Tolerations           []byte      `json:"tolerations"`
	DefaultTimeout        *string     `json:"default_timeout"`
	ServiceAccountName    *string     `json:"service_account_name"`
	WorkspaceMode         string      `json:"workspace_mode"`
	WorkspaceStorageClass *string     `json:"workspace_storage_class"`
	WorkspaceSize         string      `json:"workspace_size"`
	RunAsNonRoot          bool        `json:"run_as_non_root"`
	Mode                  string      `json:"mode"`
	ManagedSpec           []byte      `json:"managed_spec"`
	IsDefault             bool        `json:"is_default"`
}

func (q *Queries) GetRunnerPool(ctx context.Context, name string) (GetRunnerPoolRow, error) {
	row := q.db.QueryRow(ctx, getRunnerPool, name)
	var i GetRunnerPoolRow
	err := row.Scan(
		&i.Name,
		&i.Description,
		&i.Cpu,
		&i.Memory,
		&i.GpuVendor,
		&i.GpuModel,
		&i.GpuCount,
		&i.Arch,
		&i.NodeSelector,
		&i.Tolerations,
		&i.DefaultTimeout,
		&i.ServiceAccountName,
		&i.WorkspaceMode,
		&i.WorkspaceStorageClass,
		&i.WorkspaceSize,
		&i.RunAsNonRoot,
		&i.Mode,
		&i.ManagedSpec,
		&i.IsDefault,
	)
	return i, err
}

const listRunnerPoolNames = `-- name: ListRunnerPoolNames :many
SELECT name FROM runner_pools
`

func (q *Queries) ListRunnerPoolNames(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, listRunnerPoolNames)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRunnerPools = `-- name: ListRunnerPools :many
SELECT name, description, cpu, memory, gpu_vendor, gpu_model, gpu_count, arch,
       node_selector, tolerations, default_timeout,
       service_account_name, workspace_mode, workspace_storage_class, workspace_size,
       run_as_non_root, mode, managed_spec, is_default
FROM runner_pools WHERE ready = true ORDER BY name
`

type ListRunnerPoolsRow struct {
	Name                  string      `json:"name"`
	Description           *string     `json:"description"`
	Cpu                   string      `json:"cpu"`
	Memory                string      `json:"memory"`
	GpuVendor             *string     `json:"gpu_vendor"`
	GpuModel              *string     `json:"gpu_model"`
	GpuCount              pgtype.Int4 `json:"gpu_count"`
	Arch                  string      `json:"arch"`
	NodeSelector          []byte      `json:"node_selector"`
	Tolerations           []byte      `json:"tolerations"`
	DefaultTimeout        *string     `json:"default_timeout"`
	ServiceAccountName    *string     `json:"service_account_name"`
	WorkspaceMode         string      `json:"workspace_mode"`
	WorkspaceStorageClass *string     `json:"workspace_storage_class"`
	WorkspaceSize         string      `json:"workspace_size"`
	RunAsNonRoot          bool        `json:"run_as_non_root"`
	Mode                  string      `json:"mode"`
	ManagedSpec           []byte      `json:"managed_spec"`
	IsDefault             bool        `json:"is_default"`
}

// Full rows — used by the worker registry loader, compile-time validation, and the
// pool catalog. Returns everything needed to reconstruct a PoolSpec.
func (q *Queries) ListRunnerPools(ctx context.Context) ([]ListRunnerPoolsRow, error) {
	rows, err := q.db.Query(ctx, listRunnerPools)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRunnerPoolsRow{}
	for rows.Next() {
		var i ListRunnerPoolsRow
		if err := rows.Scan(
			&i.Name,
			&i.Description,
			&i.Cpu,
			&i.Memory,
			&i.GpuVendor,
			&i.GpuModel,
			&i.GpuCount,
			&i.Arch,
			&i.NodeSelector,
			&i.Tolerations,
			&i.DefaultTimeout,
			&i.ServiceAccountName,
			&i.WorkspaceMode,
			&i.WorkspaceStorageClass,
			&i.WorkspaceSize,
			&i.RunAsNonRoot,
			&i.Mode,
			&i.ManagedSpec,
			&i.IsDefault,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRunnerPoolsPaged = `-- name: ListRunnerPoolsPaged :many
SELECT id, name, description, cpu, memory, arch, gpu_vendor, gpu_model, gpu_count,
       mode, managed_spec, node_selector, tolerations, is_default, ready, created_at
FROM runner_pools ORDER BY name LIMIT $1 OFFSET $2
`

type ListRunnerPoolsPagedParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListRunnerPoolsPagedRow struct {
	ID           string      `json:"id"`
	Name         string      `json:"name"`
	Description  *string     `json:"description"`
	Cpu          string      `json:"cpu"`
	Memory       string      `json:"memory"`
	Arch         string      `json:"arch"`
	GpuVendor    *string     `json:"gpu_vendor"`
	GpuModel     *string     `json:"gpu_model"`
	GpuCount     pgtype.Int4 `json:"gpu_count"`
	Mode         string      `json:"mode"`
	ManagedSpec  []byte      `json:"managed_spec"`
	NodeSelector []byte      `json:"node_selector"`
	Tolerations  []byte      `json:"tolerations"`
	IsDefault    bool        `json:"is_default"`
	Ready        bool        `json:"ready"`
	CreatedAt    time.Time   `json:"created_at"`
}

func (q *Queries) ListRunnerPoolsPaged(ctx context.Context, arg ListRunnerPoolsPagedParams) ([]ListRunnerPoolsPagedRow, error) {
	rows, err := q.db.Query(ctx, listRunnerPoolsPaged, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRunnerPoolsPagedRow{}
	for rows.Next() {
		var i ListRunnerPoolsPagedRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Cpu,
			&i.Memory,
			&i.Arch,
			&i.GpuVendor,
			&i.GpuModel,
			&i.GpuCount,
			&i.Mode,
			&i.ManagedSpec,
			&i.NodeSelector,
			&i.Tolerations,
			&i.IsDefault,
			&i.Ready,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setDefaultRunnerPool = `-- name: SetDefaultRunnerPool :exec
UPDATE runner_pools SET is_default = (name = $1), updated_at = now()
`

// Promotes one pool to default and demotes all others atomically.
func (q *Queries) SetDefaultRunnerPool(ctx context.Context, name string) error {
	_, err := q.db.Exec(ctx, setDefaultRunnerPool, name)
	return err
}

const upsertRunnerPool = `-- name: UpsertRunnerPool :exec
INSERT INTO runner_pools (
    name, description, cpu, memory, gpu_vendor, gpu_model, gpu_count,
    arch, node_selector, tolerations,
    default_timeout, service_account_name, workspace_mode, workspace_storage_class,
    workspace_size, run_as_non_root, mode, managed_spec, ready, updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7,
    $8, $9, $10,
    $11, $12, $13, $14,
    $15, $16, $17, $18, true, now()
)
ON CONFLICT (name) DO UPDATE SET
    description = EXCLUDED.description,
    cpu = EXCLUDED.cpu,
    memory = EXCLUDED.memory,
    gpu_vendor = EXCLUDED.gpu_vendor,
    gpu_model = EXCLUDED.gpu_model,
    gpu_count = EXCLUDED.gpu_count,
    arch = EXCLUDED.arch,
    node_selector = EXCLUDED.node_selector,
    tolerations = EXCLUDED.tolerations,
    default_timeout = EXCLUDED.default_timeout,
    service_account_name = EXCLUDED.service_account_name,
    workspace_mode = EXCLUDED.workspace_mode,
    workspace_storage_class = EXCLUDED.workspace_storage_class,
    workspace_size = EXCLUDED.workspace_size,
    run_as_non_root = EXCLUDED.run_as_non_root,
    mode = EXCLUDED.mode,
    managed_spec = EXCLUDED.managed_spec,
    ready = true,
    updated_at = now()
`

type UpsertRunnerPoolParams struct {
	Name                  string      `json:"name"`
	Description           *string     `json:"description"`
	Cpu                   string      `json:"cpu"`
	Memory                string      `json:"memory"`
	GpuVendor             *string     `json:"gpu_vendor"`
	GpuModel              *string     `json:"gpu_model"`
	GpuCount              pgtype.Int4 `json:"gpu_count"`
	Arch                  string      `json:"arch"`
	NodeSelector          []byte      `json:"node_selector"`
	Tolerations           []byte      `json:"tolerations"`
	DefaultTimeout        *string     `json:"default_timeout"`
	ServiceAccountName    *string     `json:"service_account_name"`
	WorkspaceMode         string      `json:"workspace_mode"`
	WorkspaceStorageClass *string     `json:"workspace_storage_class"`
	WorkspaceSize         string      `json:"workspace_size"`
	RunAsNonRoot          bool        `json:"run_as_non_root"`
	Mode                  string      `json:"mode"`
	ManagedSpec           []byte      `json:"managed_spec"`
}

func (q *Queries) UpsertRunnerPool(ctx context.Context, arg UpsertRunnerPoolParams) error {
	_, err := q.db.Exec(ctx, upsertRunnerPool,
		arg.Name,
		arg.Description,
		arg.Cpu,
		arg.Memory,
		arg.GpuVendor,
		arg.GpuModel,
		arg.GpuCount,
		arg.Arch,
		arg.NodeSelector,
		arg.Tolerations,
		arg.DefaultTimeout,
		arg.ServiceAccountName,
		arg.WorkspaceMode,
		arg.WorkspaceStorageClass,
		arg.WorkspaceSize,
		arg.RunAsNonRoot,
		arg.Mode,
		arg.ManagedSpec,
	)
	return err
}
