// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sessions.sql

package db

import (
	"context"
	"net/netip"
	"time"
)

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (user_id, token_hash, idp_token_enc, ip_address, user_agent,
    expires_at, idle_expires_at)
VALUES ($1, $2, $3, $4::inet, $5,
    now() + make_interval(secs := $6),
    now() + make_interval(secs := $7))
RETURNING id
`

type CreateSessionParams struct {
	UserID           string     `json:"user_id"`
	TokenHash        string     `json:"token_hash"`
	IdpTokenEnc      []byte     `json:"idp_token_enc"`
	Column4          netip.Addr `json:"column_4"`
	UserAgent        *string    `json:"user_agent"`
	AbsLifetimeSecs  float64    `json:"abs_lifetime_secs"`
	IdleLifetimeSecs float64    `json:"idle_lifetime_secs"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (string, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.UserID,
		arg.TokenHash,
		arg.IdpTokenEnc,
		arg.Column4,
		arg.UserAgent,
		arg.AbsLifetimeSecs,
		arg.IdleLifetimeSecs,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :exec
DELETE FROM sessions
WHERE (revoked_at IS NOT NULL AND revoked_at < now() - interval '7 days')
   OR (expires_at < now() - interval '7 days')
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredSessions)
	return err
}

const getSessionByTokenHash = `-- name: GetSessionByTokenHash :one
SELECT id, user_id, token_hash, idp_token_enc, logout_state_enc, ip_address, user_agent,
       created_at, last_activity, expires_at, idle_expires_at, revoked_at
FROM sessions
WHERE token_hash = $1
`

type GetSessionByTokenHashRow struct {
	ID             string     `json:"id"`
	UserID         string     `json:"user_id"`
	TokenHash      string     `json:"token_hash"`
	IdpTokenEnc    []byte     `json:"idp_token_enc"`
	LogoutStateEnc []byte     `json:"logout_state_enc"`
	IpAddress      *string    `json:"ip_address"`
	UserAgent      *string    `json:"user_agent"`
	CreatedAt      time.Time  `json:"created_at"`
	LastActivity   time.Time  `json:"last_activity"`
	ExpiresAt      time.Time  `json:"expires_at"`
	IdleExpiresAt  time.Time  `json:"idle_expires_at"`
	RevokedAt      *time.Time `json:"revoked_at"`
}

func (q *Queries) GetSessionByTokenHash(ctx context.Context, tokenHash string) (GetSessionByTokenHashRow, error) {
	row := q.db.QueryRow(ctx, getSessionByTokenHash, tokenHash)
	var i GetSessionByTokenHashRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.IdpTokenEnc,
		&i.LogoutStateEnc,
		&i.IpAddress,
		&i.UserAgent,
		&i.CreatedAt,
		&i.LastActivity,
		&i.ExpiresAt,
		&i.IdleExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const listSessionsForSync = `-- name: ListSessionsForSync :many
SELECT s.id, s.user_id, s.idp_token_enc, s.last_synced_at,
       u.email, u.org_id
FROM sessions s
JOIN users u ON u.id = s.user_id
WHERE s.revoked_at IS NULL
  AND s.expires_at > now()
  AND s.idle_expires_at > now()
  AND s.idp_token_enc IS NOT NULL
  AND (s.last_synced_at IS NULL OR s.last_synced_at < now() - make_interval(secs := $1))
ORDER BY s.last_synced_at NULLS FIRST
LIMIT $2
`

type ListSessionsForSyncParams struct {
	Secs  float64 `json:"secs"`
	Limit int32   `json:"limit"`
}

type ListSessionsForSyncRow struct {
	ID           string     `json:"id"`
	UserID       string     `json:"user_id"`
	IdpTokenEnc  []byte     `json:"idp_token_enc"`
	LastSyncedAt *time.Time `json:"last_synced_at"`
	Email        string     `json:"email"`
	OrgID        string     `json:"org_id"`
}

func (q *Queries) ListSessionsForSync(ctx context.Context, arg ListSessionsForSyncParams) ([]ListSessionsForSyncRow, error) {
	rows, err := q.db.Query(ctx, listSessionsForSync, arg.Secs, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSessionsForSyncRow{}
	for rows.Next() {
		var i ListSessionsForSyncRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.IdpTokenEnc,
			&i.LastSyncedAt,
			&i.Email,
			&i.OrgID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserSessions = `-- name: ListUserSessions :many
SELECT id, ip_address, user_agent, created_at, last_activity, expires_at
FROM sessions
WHERE user_id = $1 AND revoked_at IS NULL
  AND expires_at > now() AND idle_expires_at > now()
ORDER BY last_activity DESC
`

type ListUserSessionsRow struct {
	ID           string    `json:"id"`
	IpAddress    *string   `json:"ip_address"`
	UserAgent    *string   `json:"user_agent"`
	CreatedAt    time.Time `json:"created_at"`
	LastActivity time.Time `json:"last_activity"`
	ExpiresAt    time.Time `json:"expires_at"`
}

func (q *Queries) ListUserSessions(ctx context.Context, userID string) ([]ListUserSessionsRow, error) {
	rows, err := q.db.Query(ctx, listUserSessions, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUserSessionsRow{}
	for rows.Next() {
		var i ListUserSessionsRow
		if err := rows.Scan(
			&i.ID,
			&i.IpAddress,
			&i.UserAgent,
			&i.CreatedAt,
			&i.LastActivity,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeSession = `-- name: RevokeSession :exec
UPDATE sessions SET revoked_at = now() WHERE id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeSession(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, revokeSession, id)
	return err
}

const revokeSessionByHash = `-- name: RevokeSessionByHash :exec
UPDATE sessions SET revoked_at = now() WHERE token_hash = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeSessionByHash(ctx context.Context, tokenHash string) error {
	_, err := q.db.Exec(ctx, revokeSessionByHash, tokenHash)
	return err
}

const revokeSessionsForInactiveUsers = `-- name: RevokeSessionsForInactiveUsers :execrows
UPDATE sessions s SET revoked_at = now()
FROM users u
WHERE s.user_id = u.id AND u.is_active = false AND s.revoked_at IS NULL
`

// Provider-agnostic deprovisioning sweep: terminate every live session whose
// owner has been deactivated (is_active = false), regardless of OIDC/SAML. The
// safety net for SAML, which has no back-channel to detect IdP-side removal.
func (q *Queries) RevokeSessionsForInactiveUsers(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, revokeSessionsForInactiveUsers)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeUserSessions = `-- name: RevokeUserSessions :exec
UPDATE sessions SET revoked_at = now()
WHERE user_id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeUserSessions(ctx context.Context, userID string) error {
	_, err := q.db.Exec(ctx, revokeUserSessions, userID)
	return err
}

const rotateSessionToken = `-- name: RotateSessionToken :exec
UPDATE sessions
SET token_hash = $2,
    last_activity = now(),
    idle_expires_at = now() + make_interval(secs := $3)
WHERE id = $1 AND revoked_at IS NULL
`

type RotateSessionTokenParams struct {
	ID               string  `json:"id"`
	NewHash          string  `json:"new_hash"`
	IdleLifetimeSecs float64 `json:"idle_lifetime_secs"`
}

func (q *Queries) RotateSessionToken(ctx context.Context, arg RotateSessionTokenParams) error {
	_, err := q.db.Exec(ctx, rotateSessionToken, arg.ID, arg.NewHash, arg.IdleLifetimeSecs)
	return err
}

const updateSessionIdpToken = `-- name: UpdateSessionIdpToken :exec
UPDATE sessions SET idp_token_enc = $2 WHERE id = $1
`

type UpdateSessionIdpTokenParams struct {
	ID          string `json:"id"`
	IdpTokenEnc []byte `json:"idp_token_enc"`
}

func (q *Queries) UpdateSessionIdpToken(ctx context.Context, arg UpdateSessionIdpTokenParams) error {
	_, err := q.db.Exec(ctx, updateSessionIdpToken, arg.ID, arg.IdpTokenEnc)
	return err
}

const updateSessionLogoutState = `-- name: UpdateSessionLogoutState :exec
UPDATE sessions SET logout_state_enc = $2 WHERE id = $1
`

type UpdateSessionLogoutStateParams struct {
	ID             string `json:"id"`
	LogoutStateEnc []byte `json:"logout_state_enc"`
}

func (q *Queries) UpdateSessionLogoutState(ctx context.Context, arg UpdateSessionLogoutStateParams) error {
	_, err := q.db.Exec(ctx, updateSessionLogoutState, arg.ID, arg.LogoutStateEnc)
	return err
}

const updateSessionSyncedAt = `-- name: UpdateSessionSyncedAt :exec
UPDATE sessions SET last_synced_at = now() WHERE id = $1
`

func (q *Queries) UpdateSessionSyncedAt(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, updateSessionSyncedAt, id)
	return err
}
