// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: signals.sql

package db

import (
	"context"
)

const consumeSignal = `-- name: ConsumeSignal :exec
UPDATE signals SET consumed = true WHERE id = $1
`

func (q *Queries) ConsumeSignal(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, consumeSignal, id)
	return err
}

const consumeStepResultSignals = `-- name: ConsumeStepResultSignals :many
UPDATE signals SET consumed = true
WHERE workflow_id = $1 AND signal_name = 'step-result' AND consumed = false
RETURNING payload
`

func (q *Queries) ConsumeStepResultSignals(ctx context.Context, workflowID string) ([][]byte, error) {
	rows, err := q.db.Query(ctx, consumeStepResultSignals, workflowID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := [][]byte{}
	for rows.Next() {
		var payload []byte
		if err := rows.Scan(&payload); err != nil {
			return nil, err
		}
		items = append(items, payload)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteConsumedSignals = `-- name: DeleteConsumedSignals :exec
DELETE FROM signals WHERE consumed = true AND created_at < now() - interval '7 days'
`

// Prune consumed signals so the table doesn't grow unbounded. Keeps a 7-day
// window for debugging/audit. Called from the sweep.
func (q *Queries) DeleteConsumedSignals(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteConsumedSignals)
	return err
}

const insertSignal = `-- name: InsertSignal :exec
INSERT INTO signals (workflow_id, signal_name, payload) VALUES ($1, $2, $3)
`

type InsertSignalParams struct {
	WorkflowID string `json:"workflow_id"`
	SignalName string `json:"signal_name"`
	Payload    []byte `json:"payload"`
}

func (q *Queries) InsertSignal(ctx context.Context, arg InsertSignalParams) error {
	_, err := q.db.Exec(ctx, insertSignal, arg.WorkflowID, arg.SignalName, arg.Payload)
	return err
}

const notifyEngine = `-- name: NotifyEngine :exec
SELECT pg_notify('flint_engine', $1)
`

func (q *Queries) NotifyEngine(ctx context.Context, pgNotify string) error {
	_, err := q.db.Exec(ctx, notifyEngine, pgNotify)
	return err
}
