// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sso_group_mappings.sql

package db

import (
	"context"
)

const deleteAllSSOGroupRoleMappings = `-- name: DeleteAllSSOGroupRoleMappings :exec
DELETE FROM sso_group_role_mappings WHERE org_id = $1
`

func (q *Queries) DeleteAllSSOGroupRoleMappings(ctx context.Context, orgID string) error {
	_, err := q.db.Exec(ctx, deleteAllSSOGroupRoleMappings, orgID)
	return err
}

const insertSSOGroupRoleMapping = `-- name: InsertSSOGroupRoleMapping :exec
INSERT INTO sso_group_role_mappings (org_id, group_name, role_id)
VALUES ($1, $2, $3)
ON CONFLICT (org_id, group_name, role_id) DO NOTHING
`

type InsertSSOGroupRoleMappingParams struct {
	OrgID     string `json:"org_id"`
	GroupName string `json:"group_name"`
	RoleID    string `json:"role_id"`
}

func (q *Queries) InsertSSOGroupRoleMapping(ctx context.Context, arg InsertSSOGroupRoleMappingParams) error {
	_, err := q.db.Exec(ctx, insertSSOGroupRoleMapping, arg.OrgID, arg.GroupName, arg.RoleID)
	return err
}

const listSSOGroupRoleMappings = `-- name: ListSSOGroupRoleMappings :many
SELECT m.id, m.group_name, m.role_id, r.slug AS role_slug, r.name AS role_name
FROM sso_group_role_mappings m
JOIN roles r ON r.id = m.role_id
WHERE m.org_id = $1
ORDER BY m.group_name, r.name
`

type ListSSOGroupRoleMappingsRow struct {
	ID        string `json:"id"`
	GroupName string `json:"group_name"`
	RoleID    string `json:"role_id"`
	RoleSlug  string `json:"role_slug"`
	RoleName  string `json:"role_name"`
}

func (q *Queries) ListSSOGroupRoleMappings(ctx context.Context, orgID string) ([]ListSSOGroupRoleMappingsRow, error) {
	rows, err := q.db.Query(ctx, listSSOGroupRoleMappings, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSSOGroupRoleMappingsRow{}
	for rows.Next() {
		var i ListSSOGroupRoleMappingsRow
		if err := rows.Scan(
			&i.ID,
			&i.GroupName,
			&i.RoleID,
			&i.RoleSlug,
			&i.RoleName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
