// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: steps.sql

package db

import (
	"context"
	"time"
)

const cancelPendingSteps = `-- name: CancelPendingSteps :many
WITH affected AS (
    SELECT steps.id, steps.name, steps.attempt, steps.status AS old_status
    FROM steps
    WHERE steps.workflow_id = $1 AND steps.status NOT IN ('succeeded', 'failed', 'skipped', 'cancelled')
    FOR UPDATE
)
UPDATE steps SET status = 'cancelled', finished_at = now()
FROM affected
WHERE steps.id = affected.id
RETURNING affected.name, affected.attempt, affected.old_status
`

type CancelPendingStepsRow struct {
	Name      string `json:"name"`
	Attempt   int32  `json:"attempt"`
	OldStatus string `json:"old_status"`
}

// Cancels every non-terminal step of a workflow and returns each affected step's
// name, attempt, and prior status so the caller can record a per-step 'cancelled'
// history event. The CTE captures old_status before the UPDATE overwrites it.
func (q *Queries) CancelPendingSteps(ctx context.Context, workflowID string) ([]CancelPendingStepsRow, error) {
	rows, err := q.db.Query(ctx, cancelPendingSteps, workflowID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CancelPendingStepsRow{}
	for rows.Next() {
		var i CancelPendingStepsRow
		if err := rows.Scan(&i.Name, &i.Attempt, &i.OldStatus); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const claimQueuedSteps = `-- name: ClaimQueuedSteps :many
UPDATE steps SET
    status = CASE WHEN exec_type IN ('gate', 'wait') THEN 'waiting' ELSE 'running' END,
    started_at = now(),
    deadline_at = now() + make_interval(secs := timeout_seconds)
WHERE id IN (
    SELECT steps.id FROM steps
    JOIN workflows w ON w.id = steps.workflow_id AND w.status = 'running'
    WHERE steps.status = 'queued'
    ORDER BY steps.wave, steps.queued_at
    LIMIT $1
    FOR UPDATE OF steps SKIP LOCKED
)
RETURNING id, workflow_id, name, exec_type, attempt, step_def, status
`

type ClaimQueuedStepsRow struct {
	ID         string `json:"id"`
	WorkflowID string `json:"workflow_id"`
	Name       string `json:"name"`
	ExecType   string `json:"exec_type"`
	Attempt    int32  `json:"attempt"`
	StepDef    []byte `json:"step_def"`
	Status     string `json:"status"`
}

// Claims queued steps whose workflow is 'running' (a single predicate that also
// enforces pause: a paused workflow's steps are simply not claimable). FOR UPDATE
// OF steps locks only the step rows — never the workflow row — so claiming cannot
// contend with advanceWorkflow's FOR UPDATE on the workflow. The workflow status
// read is best-effort: a pause committing after this read may let one already-
// queued step dispatch, which is acceptable (pause halts new work, not in-flight).
func (q *Queries) ClaimQueuedSteps(ctx context.Context, limit int32) ([]ClaimQueuedStepsRow, error) {
	rows, err := q.db.Query(ctx, claimQueuedSteps, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ClaimQueuedStepsRow{}
	for rows.Next() {
		var i ClaimQueuedStepsRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkflowID,
			&i.Name,
			&i.ExecType,
			&i.Attempt,
			&i.StepDef,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const completeParentInvokeStep = `-- name: CompleteParentInvokeStep :exec
UPDATE steps SET status = $1, result = $2, finished_at = now()
WHERE workflow_id = $3 AND name = $4 AND status = 'running'
`

type CompleteParentInvokeStepParams struct {
	NewStatus  string `json:"new_status"`
	Result     []byte `json:"result"`
	WorkflowID string `json:"workflow_id"`
	StepName   string `json:"step_name"`
}

func (q *Queries) CompleteParentInvokeStep(ctx context.Context, arg CompleteParentInvokeStepParams) error {
	_, err := q.db.Exec(ctx, completeParentInvokeStep,
		arg.NewStatus,
		arg.Result,
		arg.WorkflowID,
		arg.StepName,
	)
	return err
}

const createRetryStep = `-- name: CreateRetryStep :exec
INSERT INTO steps (workflow_id, name, exec_type, status, wave, attempt,
    max_attempts, step_def, timeout_seconds, retry_backoff, retry_interval_seconds, on_failure)
SELECT s.workflow_id, s.name, s.exec_type, 'retry_wait', s.wave, $1,
    s.max_attempts, s.step_def, s.timeout_seconds, s.retry_backoff, s.retry_interval_seconds, s.on_failure
FROM steps s WHERE s.id = $2
`

type CreateRetryStepParams struct {
	NewAttempt   int32  `json:"new_attempt"`
	SourceStepID string `json:"source_step_id"`
}

// The retry attempt is parked in 'retry_wait', NOT 'pending'. A 'pending' row
// would be queued immediately by advanceWorkflow, bypassing the retry_backoff
// timer. Only the fired retry_backoff timer (RequeueRetryStep) promotes it to
// 'queued', so the backoff delay is actually honoured.
func (q *Queries) CreateRetryStep(ctx context.Context, arg CreateRetryStepParams) error {
	_, err := q.db.Exec(ctx, createRetryStep, arg.NewAttempt, arg.SourceStepID)
	return err
}

const failGateByTimeout = `-- name: FailGateByTimeout :exec
UPDATE steps SET status = 'failed', result = $1::jsonb, finished_at = now()
WHERE workflow_id = $2 AND name = $3 AND status = 'waiting'
`

type FailGateByTimeoutParams struct {
	Result     []byte `json:"result"`
	WorkflowID string `json:"workflow_id"`
	StepName   string `json:"step_name"`
}

func (q *Queries) FailGateByTimeout(ctx context.Context, arg FailGateByTimeoutParams) error {
	_, err := q.db.Exec(ctx, failGateByTimeout, arg.Result, arg.WorkflowID, arg.StepName)
	return err
}

const failOrphanedWaitingSteps = `-- name: FailOrphanedWaitingSteps :execrows
UPDATE steps SET status = 'failed',
    result = jsonb_build_object('stepName', name, 'success', false,
        'error', 'wait timed out (backstop)')::jsonb,
    finished_at = now()
WHERE status = 'waiting' AND exec_type IN ('gate', 'wait')
AND EXISTS (
    SELECT 1 FROM timers t
    WHERE t.workflow_id = steps.workflow_id AND t.step_name = steps.name
    AND t.timer_type IN ('gate_timeout', 'wait_timeout') AND t.fired = true
)
`

// Defense-in-depth backstop: a gate/wait step still 'waiting' although its timeout
// timer already fired (handler regression or crash) is forced to failed so the
// workflow can run onFailure steps / finish instead of wedging forever. With atomic
// timer handling (LockNextDueTimer) this should never fire; it exists so a future
// regression degrades to "recovered late" rather than "stuck".
func (q *Queries) FailOrphanedWaitingSteps(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, failOrphanedWaitingSteps)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const failStepByTimeout = `-- name: FailStepByTimeout :exec
UPDATE steps SET status = 'failed', result = $1::jsonb, finished_at = now()
WHERE workflow_id = $2 AND name = $3 AND status = 'running'
`

type FailStepByTimeoutParams struct {
	Result     []byte `json:"result"`
	WorkflowID string `json:"workflow_id"`
	StepName   string `json:"step_name"`
}

func (q *Queries) FailStepByTimeout(ctx context.Context, arg FailStepByTimeoutParams) error {
	_, err := q.db.Exec(ctx, failStepByTimeout, arg.Result, arg.WorkflowID, arg.StepName)
	return err
}

const getStepByWorkflowAndName = `-- name: GetStepByWorkflowAndName :one
SELECT id, workflow_id, name, exec_type, step_def FROM steps
WHERE workflow_id = $1 AND name = $2
ORDER BY attempt DESC LIMIT 1
`

type GetStepByWorkflowAndNameParams struct {
	WorkflowID string `json:"workflow_id"`
	Name       string `json:"name"`
}

type GetStepByWorkflowAndNameRow struct {
	ID         string `json:"id"`
	WorkflowID string `json:"workflow_id"`
	Name       string `json:"name"`
	ExecType   string `json:"exec_type"`
	StepDef    []byte `json:"step_def"`
}

func (q *Queries) GetStepByWorkflowAndName(ctx context.Context, arg GetStepByWorkflowAndNameParams) (GetStepByWorkflowAndNameRow, error) {
	row := q.db.QueryRow(ctx, getStepByWorkflowAndName, arg.WorkflowID, arg.Name)
	var i GetStepByWorkflowAndNameRow
	err := row.Scan(
		&i.ID,
		&i.WorkflowID,
		&i.Name,
		&i.ExecType,
		&i.StepDef,
	)
	return i, err
}

const getStepStatus = `-- name: GetStepStatus :one
SELECT s.status FROM steps s
JOIN workflows w ON s.workflow_id = w.id
JOIN pipeline_runs pr ON w.run_id = pr.id
WHERE pr.id = $1 AND s.name = $2
ORDER BY s.attempt DESC LIMIT 1
`

type GetStepStatusParams struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

func (q *Queries) GetStepStatus(ctx context.Context, arg GetStepStatusParams) (string, error) {
	row := q.db.QueryRow(ctx, getStepStatus, arg.ID, arg.Name)
	var status string
	err := row.Scan(&status)
	return status, err
}

const insertSeededStep = `-- name: InsertSeededStep :exec
INSERT INTO steps (workflow_id, name, exec_type, status, wave, max_attempts,
    step_def, timeout_seconds, retry_backoff, retry_interval_seconds, on_failure,
    result, queued_at, started_at, finished_at)
VALUES ($1, $2, $3, 'succeeded', $4, $5, $6, $7, $8, $9, $10, $11, now(), now(), now())
`

type InsertSeededStepParams struct {
	WorkflowID           string `json:"workflow_id"`
	Name                 string `json:"name"`
	ExecType             string `json:"exec_type"`
	Wave                 int32  `json:"wave"`
	MaxAttempts          int32  `json:"max_attempts"`
	StepDef              []byte `json:"step_def"`
	TimeoutSeconds       int32  `json:"timeout_seconds"`
	RetryBackoff         string `json:"retry_backoff"`
	RetryIntervalSeconds int32  `json:"retry_interval_seconds"`
	OnFailure            string `json:"on_failure"`
	Result               []byte `json:"result"`
}

// Inserts a step already in terminal 'succeeded' state, carrying a result copied
// from a prior run. Used by re-run-failed / retry-from-step to skip work that
// already succeeded while still satisfying downstream dependencies and expression
// context (steps.<name>.<output>).
func (q *Queries) InsertSeededStep(ctx context.Context, arg InsertSeededStepParams) error {
	_, err := q.db.Exec(ctx, insertSeededStep,
		arg.WorkflowID,
		arg.Name,
		arg.ExecType,
		arg.Wave,
		arg.MaxAttempts,
		arg.StepDef,
		arg.TimeoutSeconds,
		arg.RetryBackoff,
		arg.RetryIntervalSeconds,
		arg.OnFailure,
		arg.Result,
	)
	return err
}

const insertStep = `-- name: InsertStep :exec
INSERT INTO steps (workflow_id, name, exec_type, status, wave, max_attempts,
    step_def, timeout_seconds, retry_backoff, retry_interval_seconds, on_failure)
VALUES ($1, $2, $3, 'pending', $4, $5, $6, $7, $8, $9, $10)
`

type InsertStepParams struct {
	WorkflowID           string `json:"workflow_id"`
	Name                 string `json:"name"`
	ExecType             string `json:"exec_type"`
	Wave                 int32  `json:"wave"`
	MaxAttempts          int32  `json:"max_attempts"`
	StepDef              []byte `json:"step_def"`
	TimeoutSeconds       int32  `json:"timeout_seconds"`
	RetryBackoff         string `json:"retry_backoff"`
	RetryIntervalSeconds int32  `json:"retry_interval_seconds"`
	OnFailure            string `json:"on_failure"`
}

func (q *Queries) InsertStep(ctx context.Context, arg InsertStepParams) error {
	_, err := q.db.Exec(ctx, insertStep,
		arg.WorkflowID,
		arg.Name,
		arg.ExecType,
		arg.Wave,
		arg.MaxAttempts,
		arg.StepDef,
		arg.TimeoutSeconds,
		arg.RetryBackoff,
		arg.RetryIntervalSeconds,
		arg.OnFailure,
	)
	return err
}

const latestStepsByWorkflow = `-- name: LatestStepsByWorkflow :many
SELECT DISTINCT ON (name) id, name, status, attempt, on_failure,
    max_attempts, retry_backoff, retry_interval_seconds,
    step_def->>'if' AS if_condition,
    step_def->>'when' AS when_condition,
    step_def->'dependsOn' AS depends_on
FROM steps WHERE workflow_id = $1
ORDER BY name, attempt DESC
`

type LatestStepsByWorkflowRow struct {
	ID                   string      `json:"id"`
	Name                 string      `json:"name"`
	Status               string      `json:"status"`
	Attempt              int32       `json:"attempt"`
	OnFailure            string      `json:"on_failure"`
	MaxAttempts          int32       `json:"max_attempts"`
	RetryBackoff         string      `json:"retry_backoff"`
	RetryIntervalSeconds int32       `json:"retry_interval_seconds"`
	IfCondition          interface{} `json:"if_condition"`
	WhenCondition        interface{} `json:"when_condition"`
	DependsOn            interface{} `json:"depends_on"`
}

func (q *Queries) LatestStepsByWorkflow(ctx context.Context, workflowID string) ([]LatestStepsByWorkflowRow, error) {
	rows, err := q.db.Query(ctx, latestStepsByWorkflow, workflowID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LatestStepsByWorkflowRow{}
	for rows.Next() {
		var i LatestStepsByWorkflowRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Status,
			&i.Attempt,
			&i.OnFailure,
			&i.MaxAttempts,
			&i.RetryBackoff,
			&i.RetryIntervalSeconds,
			&i.IfCondition,
			&i.WhenCondition,
			&i.DependsOn,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGatesByStatus = `-- name: ListGatesByStatus :many
SELECT s.name AS step_name,
       COALESCE(s.step_def->'gate'->>'message', '')::text AS message,
       pr.id AS run_id, pr.trigger_ref AS branch, pr.triggered_by,
       p.display_name AS project_name, p.colour AS project_colour,
       COALESCE(w.slug, '')::text AS workspace,
       COALESCE(s.step_def->'gate'->>'environment', '')::text AS environment,
       s.status, s.created_at,
       s.result->>'approvedBy' AS reviewed_by,
       s.finished_at AS reviewed_at
FROM steps s
JOIN workflows wf ON s.workflow_id = wf.id
JOIN pipeline_runs pr ON wf.run_id = pr.id
JOIN projects p ON pr.project_id = p.id
LEFT JOIN workspaces w ON w.id = p.workspace_id
WHERE s.exec_type = 'gate' AND s.status = $1
ORDER BY s.created_at ASC LIMIT 50
`

type ListGatesByStatusRow struct {
	StepName      string      `json:"step_name"`
	Message       string      `json:"message"`
	RunID         string      `json:"run_id"`
	Branch        *string     `json:"branch"`
	TriggeredBy   *string     `json:"triggered_by"`
	ProjectName   *string     `json:"project_name"`
	ProjectColour string      `json:"project_colour"`
	Workspace     string      `json:"workspace"`
	Environment   string      `json:"environment"`
	Status        string      `json:"status"`
	CreatedAt     time.Time   `json:"created_at"`
	ReviewedBy    interface{} `json:"reviewed_by"`
	ReviewedAt    *time.Time  `json:"reviewed_at"`
}

// Gate steps enriched with run/project/workspace context, filtered by step status
// (the handler maps UI status names: pending→waiting, approved→succeeded,
// rejected→failed). Powers GET /api/v1/gates.
func (q *Queries) ListGatesByStatus(ctx context.Context, status string) ([]ListGatesByStatusRow, error) {
	rows, err := q.db.Query(ctx, listGatesByStatus, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGatesByStatusRow{}
	for rows.Next() {
		var i ListGatesByStatusRow
		if err := rows.Scan(
			&i.StepName,
			&i.Message,
			&i.RunID,
			&i.Branch,
			&i.TriggeredBy,
			&i.ProjectName,
			&i.ProjectColour,
			&i.Workspace,
			&i.Environment,
			&i.Status,
			&i.CreatedAt,
			&i.ReviewedBy,
			&i.ReviewedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingGates = `-- name: ListPendingGates :many
SELECT s.name AS step_name,
       s.step_def->'gate'->>'message' AS message,
       w.id AS workflow_id,
       pr.id AS run_id, pr.trigger_ref AS branch, pr.triggered_by,
       p.id AS project_id, p.display_name AS project_name, p.colour AS project_colour,
       s.created_at
FROM steps s
JOIN workflows w ON s.workflow_id = w.id
JOIN pipeline_runs pr ON w.run_id = pr.id
JOIN projects p ON pr.project_id = p.id
WHERE s.exec_type = 'gate' AND s.status = 'waiting'
ORDER BY s.created_at ASC
LIMIT 50
`

type ListPendingGatesRow struct {
	StepName      string      `json:"step_name"`
	Message       interface{} `json:"message"`
	WorkflowID    string      `json:"workflow_id"`
	RunID         string      `json:"run_id"`
	Branch        *string     `json:"branch"`
	TriggeredBy   *string     `json:"triggered_by"`
	ProjectID     string      `json:"project_id"`
	ProjectName   *string     `json:"project_name"`
	ProjectColour string      `json:"project_colour"`
	CreatedAt     time.Time   `json:"created_at"`
}

func (q *Queries) ListPendingGates(ctx context.Context) ([]ListPendingGatesRow, error) {
	rows, err := q.db.Query(ctx, listPendingGates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPendingGatesRow{}
	for rows.Next() {
		var i ListPendingGatesRow
		if err := rows.Scan(
			&i.StepName,
			&i.Message,
			&i.WorkflowID,
			&i.RunID,
			&i.Branch,
			&i.TriggeredBy,
			&i.ProjectID,
			&i.ProjectName,
			&i.ProjectColour,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStepsByWorkflow = `-- name: ListStepsByWorkflow :many
SELECT DISTINCT ON (name) name, status, wave, attempt, max_attempts, result,
    exec_type, queued_at, started_at, finished_at,
    step_def->'dependsOn' AS depends_on
FROM steps WHERE workflow_id = $1
ORDER BY name, attempt DESC
`

type ListStepsByWorkflowRow struct {
	Name        string      `json:"name"`
	Status      string      `json:"status"`
	Wave        int32       `json:"wave"`
	Attempt     int32       `json:"attempt"`
	MaxAttempts int32       `json:"max_attempts"`
	Result      []byte      `json:"result"`
	ExecType    string      `json:"exec_type"`
	QueuedAt    *time.Time  `json:"queued_at"`
	StartedAt   *time.Time  `json:"started_at"`
	FinishedAt  *time.Time  `json:"finished_at"`
	DependsOn   interface{} `json:"depends_on"`
}

func (q *Queries) ListStepsByWorkflow(ctx context.Context, workflowID string) ([]ListStepsByWorkflowRow, error) {
	rows, err := q.db.Query(ctx, listStepsByWorkflow, workflowID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListStepsByWorkflowRow{}
	for rows.Next() {
		var i ListStepsByWorkflowRow
		if err := rows.Scan(
			&i.Name,
			&i.Status,
			&i.Wave,
			&i.Attempt,
			&i.MaxAttempts,
			&i.Result,
			&i.ExecType,
			&i.QueuedAt,
			&i.StartedAt,
			&i.FinishedAt,
			&i.DependsOn,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockLatestStep = `-- name: LockLatestStep :one
SELECT id, status, attempt FROM steps
WHERE workflow_id = $1 AND name = $2
ORDER BY attempt DESC LIMIT 1
FOR UPDATE
`

type LockLatestStepParams struct {
	WorkflowID string `json:"workflow_id"`
	Name       string `json:"name"`
}

type LockLatestStepRow struct {
	ID      string `json:"id"`
	Status  string `json:"status"`
	Attempt int32  `json:"attempt"`
}

// Row-locks the latest attempt of a step for an operator override (manual resolve).
func (q *Queries) LockLatestStep(ctx context.Context, arg LockLatestStepParams) (LockLatestStepRow, error) {
	row := q.db.QueryRow(ctx, lockLatestStep, arg.WorkflowID, arg.Name)
	var i LockLatestStepRow
	err := row.Scan(&i.ID, &i.Status, &i.Attempt)
	return i, err
}

const lockNextApprovedGate = `-- name: LockNextApprovedGate :one
SELECT s.id AS step_id, s.workflow_id, s.name AS step_name, s.attempt, sig.id AS signal_id
FROM steps s
JOIN signals sig ON sig.workflow_id = s.workflow_id
    AND sig.signal_name = 'gate-' || s.name
    AND sig.consumed = false
WHERE s.status = 'waiting' AND s.exec_type = 'gate'
ORDER BY s.created_at
LIMIT 1
FOR UPDATE OF s SKIP LOCKED
`

type LockNextApprovedGateRow struct {
	StepID     string `json:"step_id"`
	WorkflowID string `json:"workflow_id"`
	StepName   string `json:"step_name"`
	Attempt    int32  `json:"attempt"`
	SignalID   string `json:"signal_id"`
}

// Claims one waiting gate that has an unconsumed approval signal, locking the step
// row (FOR UPDATE OF s SKIP LOCKED) so concurrent workers never process the same
// gate. The caller consumes the signal, transitions the step, and advances — all
// in the same transaction, so the effect is atomic and exactly-once. The
// status='waiting' predicate is first-writer-wins: once approved or rejected, the
// gate is no longer claimable here.
func (q *Queries) LockNextApprovedGate(ctx context.Context) (LockNextApprovedGateRow, error) {
	row := q.db.QueryRow(ctx, lockNextApprovedGate)
	var i LockNextApprovedGateRow
	err := row.Scan(
		&i.StepID,
		&i.WorkflowID,
		&i.StepName,
		&i.Attempt,
		&i.SignalID,
	)
	return i, err
}

const lockNextRejectedGate = `-- name: LockNextRejectedGate :one
SELECT s.id AS step_id, s.workflow_id, s.name AS step_name, s.attempt, sig.id AS signal_id, sig.payload
FROM steps s
JOIN signals sig ON sig.workflow_id = s.workflow_id
    AND sig.signal_name = 'gate-reject-' || s.name
    AND sig.consumed = false
WHERE s.status = 'waiting' AND s.exec_type = 'gate'
ORDER BY s.created_at
LIMIT 1
FOR UPDATE OF s SKIP LOCKED
`

type LockNextRejectedGateRow struct {
	StepID     string `json:"step_id"`
	WorkflowID string `json:"workflow_id"`
	StepName   string `json:"step_name"`
	Attempt    int32  `json:"attempt"`
	SignalID   string `json:"signal_id"`
	Payload    []byte `json:"payload"`
}

// Same as LockNextApprovedGate but for rejection signals. Returns the payload so
// the caller can surface the rejection reason.
func (q *Queries) LockNextRejectedGate(ctx context.Context) (LockNextRejectedGateRow, error) {
	row := q.db.QueryRow(ctx, lockNextRejectedGate)
	var i LockNextRejectedGateRow
	err := row.Scan(
		&i.StepID,
		&i.WorkflowID,
		&i.StepName,
		&i.Attempt,
		&i.SignalID,
		&i.Payload,
	)
	return i, err
}

const lockNextSignaledWaitStep = `-- name: LockNextSignaledWaitStep :one
SELECT s.id AS step_id, s.workflow_id, s.name AS step_name, s.attempt, sig.id AS signal_id, sig.payload
FROM steps s
JOIN signals sig ON sig.workflow_id = s.workflow_id
    AND sig.signal_name = COALESCE(NULLIF(s.step_def->'wait'->>'signal', ''), s.name)
    AND sig.consumed = false
WHERE s.status = 'waiting' AND s.exec_type = 'wait'
ORDER BY s.created_at
LIMIT 1
FOR UPDATE OF s SKIP LOCKED
`

type LockNextSignaledWaitStepRow struct {
	StepID     string `json:"step_id"`
	WorkflowID string `json:"workflow_id"`
	StepName   string `json:"step_name"`
	Attempt    int32  `json:"attempt"`
	SignalID   string `json:"signal_id"`
	Payload    []byte `json:"payload"`
}

// Claims one waiting 'wait' step whose configured external signal has arrived
// (step_def->'wait'->>'signal'). Same atomic lock-and-advance pattern as gates.
// Returns the signal payload, which the caller captures into the step outputs so
// downstream steps can reference steps.<name>.<key>.
func (q *Queries) LockNextSignaledWaitStep(ctx context.Context) (LockNextSignaledWaitStepRow, error) {
	row := q.db.QueryRow(ctx, lockNextSignaledWaitStep)
	var i LockNextSignaledWaitStepRow
	err := row.Scan(
		&i.StepID,
		&i.WorkflowID,
		&i.StepName,
		&i.Attempt,
		&i.SignalID,
		&i.Payload,
	)
	return i, err
}

const lockStep = `-- name: LockStep :one
SELECT id, status, max_attempts, retry_backoff, retry_interval_seconds
FROM steps
WHERE workflow_id = $1 AND name = $2 AND attempt = $3
FOR UPDATE
`

type LockStepParams struct {
	WorkflowID string `json:"workflow_id"`
	Name       string `json:"name"`
	Attempt    int32  `json:"attempt"`
}

type LockStepRow struct {
	ID                   string `json:"id"`
	Status               string `json:"status"`
	MaxAttempts          int32  `json:"max_attempts"`
	RetryBackoff         string `json:"retry_backoff"`
	RetryIntervalSeconds int32  `json:"retry_interval_seconds"`
}

func (q *Queries) LockStep(ctx context.Context, arg LockStepParams) (LockStepRow, error) {
	row := q.db.QueryRow(ctx, lockStep, arg.WorkflowID, arg.Name, arg.Attempt)
	var i LockStepRow
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.MaxAttempts,
		&i.RetryBackoff,
		&i.RetryIntervalSeconds,
	)
	return i, err
}

const markStepDispatched = `-- name: MarkStepDispatched :exec
UPDATE steps SET dispatched_at = now(), dispatch_handle = $2 WHERE id = $1
`

type MarkStepDispatchedParams struct {
	ID             string  `json:"id"`
	DispatchHandle *string `json:"dispatch_handle"`
}

// Records that a claimed step was successfully handed to an executor. dispatched_at
// distinguishes "running, dispatched" from "claimed but the worker died before
// dispatch" — the latter is recovered by RequeueUndispatchedSteps. dispatch_handle
// is the executor's opaque correlation id (machine executor: step_assignments.id).
func (q *Queries) MarkStepDispatched(ctx context.Context, arg MarkStepDispatchedParams) error {
	_, err := q.db.Exec(ctx, markStepDispatched, arg.ID, arg.DispatchHandle)
	return err
}

const queueStats = `-- name: QueueStats :one
SELECT
    count(*) FILTER (WHERE status = 'queued')  AS queued,
    count(*) FILTER (WHERE status = 'running') AS running,
    count(*) FILTER (WHERE status = 'waiting') AS waiting_gates,
    coalesce(EXTRACT(EPOCH FROM (now() - min(queued_at) FILTER (WHERE status = 'queued')))::bigint, 0) AS oldest_queued_secs
FROM steps
WHERE status IN ('queued', 'running', 'waiting')
`

type QueueStatsRow struct {
	Queued           int64       `json:"queued"`
	Running          int64       `json:"running"`
	WaitingGates     int64       `json:"waiting_gates"`
	OldestQueuedSecs interface{} `json:"oldest_queued_secs"`
}

// One-shot queue visibility: how much work is waiting, how long the oldest
// queued step has waited, and what's running/gated right now.
func (q *Queries) QueueStats(ctx context.Context) (QueueStatsRow, error) {
	row := q.db.QueryRow(ctx, queueStats)
	var i QueueStatsRow
	err := row.Scan(
		&i.Queued,
		&i.Running,
		&i.WaitingGates,
		&i.OldestQueuedSecs,
	)
	return i, err
}

const recentlyFailedWorkflowIDs = `-- name: RecentlyFailedWorkflowIDs :many
SELECT DISTINCT workflow_id FROM steps
WHERE status = 'failed' AND finished_at >= now() - interval '10 seconds'
`

func (q *Queries) RecentlyFailedWorkflowIDs(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, recentlyFailedWorkflowIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var workflow_id string
		if err := rows.Scan(&workflow_id); err != nil {
			return nil, err
		}
		items = append(items, workflow_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const requeueRetryStep = `-- name: RequeueRetryStep :exec
WITH latest AS (
    SELECT s.id FROM steps s
    WHERE s.workflow_id = $1 AND s.name = $2 AND s.status = 'retry_wait'
    ORDER BY s.attempt DESC LIMIT 1
)
UPDATE steps SET status = 'queued', queued_at = now()
FROM latest WHERE steps.id = latest.id
`

type RequeueRetryStepParams struct {
	WorkflowID string `json:"workflow_id"`
	Name       string `json:"name"`
}

// Promotes the parked retry attempt (retry_wait) to queued once its backoff timer
// fires. This is the ONLY path out of retry_wait.
func (q *Queries) RequeueRetryStep(ctx context.Context, arg RequeueRetryStepParams) error {
	_, err := q.db.Exec(ctx, requeueRetryStep, arg.WorkflowID, arg.Name)
	return err
}

const requeueUndispatchedSteps = `-- name: RequeueUndispatchedSteps :execrows
UPDATE steps SET status = 'queued', queued_at = now(),
    deadline_at = NULL, started_at = NULL, dispatched_at = NULL
WHERE status = 'running' AND dispatched_at IS NULL
    AND started_at < now() - make_interval(secs := $1::double precision)
`

// Recovers steps that were claimed (status='running') but never dispatched — e.g.
// the worker crashed between claiming and creating the Job. Re-queue (not fail):
// the step never executed, so it deserves a fresh dispatch rather than a failure.
func (q *Queries) RequeueUndispatchedSteps(ctx context.Context, graceSecs float64) (int64, error) {
	result, err := q.db.Exec(ctx, requeueUndispatchedSteps, graceSecs)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const runStepCosts = `-- name: RunStepCosts :many
SELECT DISTINCT ON (s.name) s.name, s.exec_type, s.started_at, s.finished_at,
    s.step_def->'resources' AS resources
FROM steps s
JOIN workflows w ON w.id = s.workflow_id
WHERE w.run_id = $1
ORDER BY s.name, s.attempt DESC
`

type RunStepCostsRow struct {
	Name       string      `json:"name"`
	ExecType   string      `json:"exec_type"`
	StartedAt  *time.Time  `json:"started_at"`
	FinishedAt *time.Time  `json:"finished_at"`
	Resources  interface{} `json:"resources"`
}

// Per-step timing + compute requests for the run cost breakdown.
func (q *Queries) RunStepCosts(ctx context.Context, runID string) ([]RunStepCostsRow, error) {
	rows, err := q.db.Query(ctx, runStepCosts, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RunStepCostsRow{}
	for rows.Next() {
		var i RunStepCostsRow
		if err := rows.Scan(
			&i.Name,
			&i.ExecType,
			&i.StartedAt,
			&i.FinishedAt,
			&i.Resources,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setStepDispatchHandle = `-- name: SetStepDispatchHandle :exec
UPDATE steps SET dispatch_handle = $2 WHERE id = $1
`

type SetStepDispatchHandleParams struct {
	ID             string  `json:"id"`
	DispatchHandle *string `json:"dispatch_handle"`
}

func (q *Queries) SetStepDispatchHandle(ctx context.Context, arg SetStepDispatchHandleParams) error {
	_, err := q.db.Exec(ctx, setStepDispatchHandle, arg.ID, arg.DispatchHandle)
	return err
}

const setStepQueued = `-- name: SetStepQueued :exec
UPDATE steps SET status = 'queued', queued_at = now(),
    deadline_at = NULL, started_at = NULL, dispatched_at = NULL
WHERE id = $1
`

// Clears execution timestamps so a re-queued step (throttled, undispatched, or
// first queue) starts with a clean slate. Critical: a stale deadline_at left over
// from an earlier claim would let the sweep time the step out prematurely.
func (q *Queries) SetStepQueued(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, setStepQueued, id)
	return err
}

const setStepSkipped = `-- name: SetStepSkipped :exec
UPDATE steps SET status = 'skipped', finished_at = now() WHERE id = $1
`

func (q *Queries) SetStepSkipped(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, setStepSkipped, id)
	return err
}

const setStepStatus = `-- name: SetStepStatus :exec
UPDATE steps SET status = $2 WHERE id = $1
`

type SetStepStatusParams struct {
	ID     string `json:"id"`
	Status string `json:"status"`
}

func (q *Queries) SetStepStatus(ctx context.Context, arg SetStepStatusParams) error {
	_, err := q.db.Exec(ctx, setStepStatus, arg.ID, arg.Status)
	return err
}

const setStepTaskToken = `-- name: SetStepTaskToken :exec
UPDATE steps SET task_token = $2 WHERE id = $1
`

type SetStepTaskTokenParams struct {
	ID        string  `json:"id"`
	TaskToken *string `json:"task_token"`
}

func (q *Queries) SetStepTaskToken(ctx context.Context, arg SetStepTaskTokenParams) error {
	_, err := q.db.Exec(ctx, setStepTaskToken, arg.ID, arg.TaskToken)
	return err
}

const setStepTaskTokens = `-- name: SetStepTaskTokens :exec
UPDATE steps SET task_token = t.token
FROM (SELECT unnest($1::uuid[]) AS id, unnest($2::text[]) AS token) t
WHERE steps.id = t.id
`

type SetStepTaskTokensParams struct {
	Ids    []string `json:"ids"`
	Tokens []string `json:"tokens"`
}

// Batch variant: stamp every claimed step's task token in ONE round-trip
// instead of one UPDATE per step (the claim path's hottest write).
func (q *Queries) SetStepTaskTokens(ctx context.Context, arg SetStepTaskTokensParams) error {
	_, err := q.db.Exec(ctx, setStepTaskTokens, arg.Ids, arg.Tokens)
	return err
}

const sweepStaleRunningSteps = `-- name: SweepStaleRunningSteps :execrows
UPDATE steps SET status = 'failed',
    result = ('{"stepName":"' || name || '","success":false,"error":"step timed out (sweep)"}')::jsonb,
    finished_at = now()
WHERE status = 'running' AND deadline_at < now()
`

func (q *Queries) SweepStaleRunningSteps(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, sweepStaleRunningSteps)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateStepResult = `-- name: UpdateStepResult :exec
UPDATE steps SET status = $2, result = $3, finished_at = now() WHERE id = $1
`

type UpdateStepResultParams struct {
	ID     string `json:"id"`
	Status string `json:"status"`
	Result []byte `json:"result"`
}

func (q *Queries) UpdateStepResult(ctx context.Context, arg UpdateStepResultParams) error {
	_, err := q.db.Exec(ctx, updateStepResult, arg.ID, arg.Status, arg.Result)
	return err
}
