// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: step_assignments.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const bindAssignment = `-- name: BindAssignment :exec
UPDATE step_assignments SET
    status = 'assigned', machine_id = $1,
    assigned_at = now(), claim_deadline_at = $2
WHERE id = $3 AND status = 'pending'
`

type BindAssignmentParams struct {
	MachineID       *string    `json:"machine_id"`
	ClaimDeadlineAt *time.Time `json:"claim_deadline_at"`
	ID              string     `json:"id"`
}

// Scheduler → machine binding. claim_deadline_at bounds how long the agent has to
// pick it up before the sweep unbinds it.
func (q *Queries) BindAssignment(ctx context.Context, arg BindAssignmentParams) error {
	_, err := q.db.Exec(ctx, bindAssignment, arg.MachineID, arg.ClaimDeadlineAt, arg.ID)
	return err
}

const cancelRunAssignments = `-- name: CancelRunAssignments :execrows
UPDATE step_assignments SET status = 'cancelled', finished_at = now()
WHERE run_id = $1 AND status IN ('pending', 'assigned')
`

// CleanupRun / engine cancellation: kill work that has not reached an agent yet.
func (q *Queries) CancelRunAssignments(ctx context.Context, runID string) (int64, error) {
	result, err := q.db.Exec(ctx, cancelRunAssignments, runID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const claimAssignmentForAgent = `-- name: ClaimAssignmentForAgent :one
UPDATE step_assignments SET status = 'running', started_at = now()
WHERE id = (
    SELECT sa.id FROM step_assignments sa
    WHERE sa.machine_id = $1 AND sa.status = 'assigned'
    ORDER BY sa.assigned_at
    LIMIT 1
    FOR UPDATE SKIP LOCKED
)
RETURNING id, run_id, step_name, attempt, payload
`

type ClaimAssignmentForAgentRow struct {
	ID       string `json:"id"`
	RunID    string `json:"run_id"`
	StepName string `json:"step_name"`
	Attempt  int32  `json:"attempt"`
	Payload  []byte `json:"payload"`
}

// Agent ClaimStep: atomically take the oldest assigned work for this machine.
func (q *Queries) ClaimAssignmentForAgent(ctx context.Context, machineID *string) (ClaimAssignmentForAgentRow, error) {
	row := q.db.QueryRow(ctx, claimAssignmentForAgent, machineID)
	var i ClaimAssignmentForAgentRow
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.StepName,
		&i.Attempt,
		&i.Payload,
	)
	return i, err
}

const claimPendingAssignments = `-- name: ClaimPendingAssignments :many
SELECT id, step_id, workflow_id, run_id, step_name, attempt,
       cpu_millis, memory_mb, disk_gb
FROM step_assignments
WHERE pool_id = $1 AND status = 'pending'
ORDER BY created_at
LIMIT $2
FOR UPDATE SKIP LOCKED
`

type ClaimPendingAssignmentsParams struct {
	PoolID string `json:"pool_id"`
	Limit  int32  `json:"limit"`
}

type ClaimPendingAssignmentsRow struct {
	ID         string `json:"id"`
	StepID     string `json:"step_id"`
	WorkflowID string `json:"workflow_id"`
	RunID      string `json:"run_id"`
	StepName   string `json:"step_name"`
	Attempt    int32  `json:"attempt"`
	CpuMillis  int64  `json:"cpu_millis"`
	MemoryMb   int64  `json:"memory_mb"`
	DiskGb     int64  `json:"disk_gb"`
}

// Fleet scheduler input: oldest-first pending work for one pool.
func (q *Queries) ClaimPendingAssignments(ctx context.Context, arg ClaimPendingAssignmentsParams) ([]ClaimPendingAssignmentsRow, error) {
	rows, err := q.db.Query(ctx, claimPendingAssignments, arg.PoolID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ClaimPendingAssignmentsRow{}
	for rows.Next() {
		var i ClaimPendingAssignmentsRow
		if err := rows.Scan(
			&i.ID,
			&i.StepID,
			&i.WorkflowID,
			&i.RunID,
			&i.StepName,
			&i.Attempt,
			&i.CpuMillis,
			&i.MemoryMb,
			&i.DiskGb,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const cleanupOldStepAssignments = `-- name: CleanupOldStepAssignments :exec
DELETE FROM step_assignments WHERE id IN (
    SELECT id FROM step_assignments
    WHERE status IN ('succeeded', 'failed', 'cancelled', 'lost')
      AND finished_at < now() - make_interval(days => $1::int)
    LIMIT 2000
)
`

// Retention: terminal assignments past the window. They do NOT cascade from
// DeleteOldRuns (step_assignments has no FK to runs — deliberate, to keep the
// hot dispatch path off the runs lock), and each carries the fattest JSONB
// payload in the operational path, so this is the top bloat vector. Batched, on
// the same window as runs retention.
func (q *Queries) CleanupOldStepAssignments(ctx context.Context, retentionDays int32) error {
	_, err := q.db.Exec(ctx, cleanupOldStepAssignments, retentionDays)
	return err
}

const failAssignment = `-- name: FailAssignment :one
UPDATE step_assignments SET status = 'failed', error = $1, finished_at = now()
WHERE id = $2 AND status IN ('assigned', 'running')
RETURNING id, step_id, workflow_id, run_id, step_name, attempt
`

type FailAssignmentParams struct {
	Error *string `json:"error"`
	ID    string  `json:"id"`
}

type FailAssignmentRow struct {
	ID         string `json:"id"`
	StepID     string `json:"step_id"`
	WorkflowID string `json:"workflow_id"`
	RunID      string `json:"run_id"`
	StepName   string `json:"step_name"`
	Attempt    int32  `json:"attempt"`
}

// Fails one assignment (agent-reported death or restart reconcile), returning
// the identifiers the caller needs to emit the step-result signal.
func (q *Queries) FailAssignment(ctx context.Context, arg FailAssignmentParams) (FailAssignmentRow, error) {
	row := q.db.QueryRow(ctx, failAssignment, arg.Error, arg.ID)
	var i FailAssignmentRow
	err := row.Scan(
		&i.ID,
		&i.StepID,
		&i.WorkflowID,
		&i.RunID,
		&i.StepName,
		&i.Attempt,
	)
	return i, err
}

const failMachineAssignments = `-- name: FailMachineAssignments :many
UPDATE step_assignments SET status = 'lost', error = $1, finished_at = now()
WHERE machine_id = $2 AND status IN ('assigned', 'running')
RETURNING id, step_id, workflow_id, run_id, step_name, attempt
`

type FailMachineAssignmentsParams struct {
	Error     *string `json:"error"`
	MachineID *string `json:"machine_id"`
}

type FailMachineAssignmentsRow struct {
	ID         string `json:"id"`
	StepID     string `json:"step_id"`
	WorkflowID string `json:"workflow_id"`
	RunID      string `json:"run_id"`
	StepName   string `json:"step_name"`
	Attempt    int32  `json:"attempt"`
}

// Machine lost: every live assignment on it fails; the caller emits a step-result
// signal per row so the engine's existing retry path takes over.
func (q *Queries) FailMachineAssignments(ctx context.Context, arg FailMachineAssignmentsParams) ([]FailMachineAssignmentsRow, error) {
	rows, err := q.db.Query(ctx, failMachineAssignments, arg.Error, arg.MachineID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FailMachineAssignmentsRow{}
	for rows.Next() {
		var i FailMachineAssignmentsRow
		if err := rows.Scan(
			&i.ID,
			&i.StepID,
			&i.WorkflowID,
			&i.RunID,
			&i.StepName,
			&i.Attempt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const finishAssignment = `-- name: FinishAssignment :execrows
UPDATE step_assignments SET
    status = $1, error = $2, finished_at = now()
WHERE id = $3 AND status IN ('pending', 'assigned', 'running')
`

type FinishAssignmentParams struct {
	Status string  `json:"status"`
	Error  *string `json:"error"`
	ID     string  `json:"id"`
}

// :execrows so CompleteAssignment can detect a duplicate completion (0 rows =
// the assignment was already finalized by an earlier delivery) and skip the
// steps_completed bump + busy→idle transition, which would otherwise drift the
// machine's stats and accounting on a redelivered result.
func (q *Queries) FinishAssignment(ctx context.Context, arg FinishAssignmentParams) (int64, error) {
	result, err := q.db.Exec(ctx, finishAssignment, arg.Status, arg.Error, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getAssignment = `-- name: GetAssignment :one
SELECT id, step_id, workflow_id, run_id, step_name, attempt, pool_id, machine_id, status, cpu_millis, memory_mb, disk_gb, payload, cancel_requested, error, created_at, assigned_at, claim_deadline_at, started_at, finished_at FROM step_assignments WHERE id = $1
`

func (q *Queries) GetAssignment(ctx context.Context, id string) (StepAssignment, error) {
	row := q.db.QueryRow(ctx, getAssignment, id)
	var i StepAssignment
	err := row.Scan(
		&i.ID,
		&i.StepID,
		&i.WorkflowID,
		&i.RunID,
		&i.StepName,
		&i.Attempt,
		&i.PoolID,
		&i.MachineID,
		&i.Status,
		&i.CpuMillis,
		&i.MemoryMb,
		&i.DiskGb,
		&i.Payload,
		&i.CancelRequested,
		&i.Error,
		&i.CreatedAt,
		&i.AssignedAt,
		&i.ClaimDeadlineAt,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const insertStepAssignment = `-- name: InsertStepAssignment :one
INSERT INTO step_assignments (
    step_id, workflow_id, run_id, step_name, attempt, pool_id,
    cpu_millis, memory_mb, disk_gb, payload
) VALUES (
    $1, $2, $3, $4, $5, $6,
    $7, $8, $9, $10
) RETURNING id
`

type InsertStepAssignmentParams struct {
	StepID     string `json:"step_id"`
	WorkflowID string `json:"workflow_id"`
	RunID      string `json:"run_id"`
	StepName   string `json:"step_name"`
	Attempt    int32  `json:"attempt"`
	PoolID     string `json:"pool_id"`
	CpuMillis  int64  `json:"cpu_millis"`
	MemoryMb   int64  `json:"memory_mb"`
	DiskGb     int64  `json:"disk_gb"`
	Payload    []byte `json:"payload"`
}

// Machine executor dispatch: a 'pending' assignment IS the pending-capacity queue —
// dispatch never blocks on capacity; the fleet loop owns boot-new decisions.
func (q *Queries) InsertStepAssignment(ctx context.Context, arg InsertStepAssignmentParams) (string, error) {
	row := q.db.QueryRow(ctx, insertStepAssignment,
		arg.StepID,
		arg.WorkflowID,
		arg.RunID,
		arg.StepName,
		arg.Attempt,
		arg.PoolID,
		arg.CpuMillis,
		arg.MemoryMb,
		arg.DiskGb,
		arg.Payload,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}

const listActiveAssignmentsForMachine = `-- name: ListActiveAssignmentsForMachine :many
SELECT id, step_id, run_id, step_name, attempt, status, cpu_millis, memory_mb
FROM step_assignments
WHERE machine_id = $1 AND status IN ('assigned', 'running')
`

type ListActiveAssignmentsForMachineRow struct {
	ID        string `json:"id"`
	StepID    string `json:"step_id"`
	RunID     string `json:"run_id"`
	StepName  string `json:"step_name"`
	Attempt   int32  `json:"attempt"`
	Status    string `json:"status"`
	CpuMillis int64  `json:"cpu_millis"`
	MemoryMb  int64  `json:"memory_mb"`
}

func (q *Queries) ListActiveAssignmentsForMachine(ctx context.Context, machineID *string) ([]ListActiveAssignmentsForMachineRow, error) {
	rows, err := q.db.Query(ctx, listActiveAssignmentsForMachine, machineID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveAssignmentsForMachineRow{}
	for rows.Next() {
		var i ListActiveAssignmentsForMachineRow
		if err := rows.Scan(
			&i.ID,
			&i.StepID,
			&i.RunID,
			&i.StepName,
			&i.Attempt,
			&i.Status,
			&i.CpuMillis,
			&i.MemoryMb,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCancelRequestedForMachine = `-- name: ListCancelRequestedForMachine :many
SELECT id, run_id, step_name FROM step_assignments
WHERE machine_id = $1 AND status = 'running' AND cancel_requested = true
`

type ListCancelRequestedForMachineRow struct {
	ID       string `json:"id"`
	RunID    string `json:"run_id"`
	StepName string `json:"step_name"`
}

func (q *Queries) ListCancelRequestedForMachine(ctx context.Context, machineID *string) ([]ListCancelRequestedForMachineRow, error) {
	rows, err := q.db.Query(ctx, listCancelRequestedForMachine, machineID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCancelRequestedForMachineRow{}
	for rows.Next() {
		var i ListCancelRequestedForMachineRow
		if err := rows.Scan(&i.ID, &i.RunID, &i.StepName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRunAssignments = `-- name: ListRunAssignments :many
SELECT a.id, a.step_id, a.workflow_id, a.run_id, a.step_name, a.attempt, a.pool_id, a.machine_id, a.status, a.cpu_millis, a.memory_mb, a.disk_gb, a.payload, a.cancel_requested, a.error, a.created_at, a.assigned_at, a.claim_deadline_at, a.started_at, a.finished_at, m.instance_type, m.capacity_type, m.price_per_hour_usd
FROM step_assignments a
LEFT JOIN machines m ON m.id = a.machine_id
WHERE a.run_id = $1
ORDER BY a.created_at
`

type ListRunAssignmentsRow struct {
	ID              string         `json:"id"`
	StepID          string         `json:"step_id"`
	WorkflowID      string         `json:"workflow_id"`
	RunID           string         `json:"run_id"`
	StepName        string         `json:"step_name"`
	Attempt         int32          `json:"attempt"`
	PoolID          string         `json:"pool_id"`
	MachineID       *string        `json:"machine_id"`
	Status          string         `json:"status"`
	CpuMillis       int64          `json:"cpu_millis"`
	MemoryMb        int64          `json:"memory_mb"`
	DiskGb          int64          `json:"disk_gb"`
	Payload         []byte         `json:"payload"`
	CancelRequested bool           `json:"cancel_requested"`
	Error           *string        `json:"error"`
	CreatedAt       time.Time      `json:"created_at"`
	AssignedAt      *time.Time     `json:"assigned_at"`
	ClaimDeadlineAt *time.Time     `json:"claim_deadline_at"`
	StartedAt       *time.Time     `json:"started_at"`
	FinishedAt      *time.Time     `json:"finished_at"`
	InstanceType    *string        `json:"instance_type"`
	CapacityType    *string        `json:"capacity_type"`
	PricePerHourUsd pgtype.Numeric `json:"price_per_hour_usd"`
}

// Run placement panel: which machine executed each step, and when.
func (q *Queries) ListRunAssignments(ctx context.Context, runID string) ([]ListRunAssignmentsRow, error) {
	rows, err := q.db.Query(ctx, listRunAssignments, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRunAssignmentsRow{}
	for rows.Next() {
		var i ListRunAssignmentsRow
		if err := rows.Scan(
			&i.ID,
			&i.StepID,
			&i.WorkflowID,
			&i.RunID,
			&i.StepName,
			&i.Attempt,
			&i.PoolID,
			&i.MachineID,
			&i.Status,
			&i.CpuMillis,
			&i.MemoryMb,
			&i.DiskGb,
			&i.Payload,
			&i.CancelRequested,
			&i.Error,
			&i.CreatedAt,
			&i.AssignedAt,
			&i.ClaimDeadlineAt,
			&i.StartedAt,
			&i.FinishedAt,
			&i.InstanceType,
			&i.CapacityType,
			&i.PricePerHourUsd,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const machineFreeCapacity = `-- name: MachineFreeCapacity :many
SELECT m.id, m.status, m.cpu_millis, m.memory_mb, m.last_heartbeat_at, m.capacity_type,
       COALESCE(SUM(a.cpu_millis) FILTER (WHERE a.status IN ('assigned','running')), 0)::bigint AS committed_cpu_millis,
       COALESCE(SUM(a.memory_mb) FILTER (WHERE a.status IN ('assigned','running')), 0)::bigint AS committed_memory_mb,
       COALESCE(array_agg(DISTINCT a.run_id) FILTER (WHERE a.status IN ('assigned','running','succeeded','failed')), '{}')::uuid[] AS active_run_ids
FROM machines m
LEFT JOIN step_assignments a ON a.machine_id = m.id
WHERE m.pool_id = $1 AND m.status IN ('idle', 'busy')
GROUP BY m.id
`

type MachineFreeCapacityRow struct {
	ID                 string     `json:"id"`
	Status             string     `json:"status"`
	CpuMillis          int64      `json:"cpu_millis"`
	MemoryMb           int64      `json:"memory_mb"`
	LastHeartbeatAt    *time.Time `json:"last_heartbeat_at"`
	CapacityType       *string    `json:"capacity_type"`
	CommittedCpuMillis int64      `json:"committed_cpu_millis"`
	CommittedMemoryMb  int64      `json:"committed_memory_mb"`
	ActiveRunIds       []string   `json:"active_run_ids"`
}

// Scheduler input: candidate machines for a pool with their committed capacity.
// Free = machines.cpu_millis − committed (computed by the caller); no reserved
// counters to drift. active_run_ids drives HARD run affinity, so it includes
// runs whose earlier steps already finished here (the workspace directory
// outlives the assignment) — 'lost' (machine death; retries start fresh) and
// 'cancelled' assignments don't pin a run.
func (q *Queries) MachineFreeCapacity(ctx context.Context, poolID string) ([]MachineFreeCapacityRow, error) {
	rows, err := q.db.Query(ctx, machineFreeCapacity, poolID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MachineFreeCapacityRow{}
	for rows.Next() {
		var i MachineFreeCapacityRow
		if err := rows.Scan(
			&i.ID,
			&i.Status,
			&i.CpuMillis,
			&i.MemoryMb,
			&i.LastHeartbeatAt,
			&i.CapacityType,
			&i.CommittedCpuMillis,
			&i.CommittedMemoryMb,
			&i.ActiveRunIds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pendingAssignmentDemand = `-- name: PendingAssignmentDemand :many
SELECT pool_id, count(*) AS n,
       COALESCE(SUM(cpu_millis), 0)::bigint AS cpu_millis,
       COALESCE(SUM(memory_mb), 0)::bigint AS memory_mb
FROM step_assignments WHERE status = 'pending'
GROUP BY pool_id
`

type PendingAssignmentDemandRow struct {
	PoolID    string `json:"pool_id"`
	N         int64  `json:"n"`
	CpuMillis int64  `json:"cpu_millis"`
	MemoryMb  int64  `json:"memory_mb"`
}

// Fleet scheduler input: unbound demand per pool (ALL pending, incl. work pinned
// to an existing holder — the scheduler still has to place those on their holder).
func (q *Queries) PendingAssignmentDemand(ctx context.Context) ([]PendingAssignmentDemandRow, error) {
	rows, err := q.db.Query(ctx, pendingAssignmentDemand)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PendingAssignmentDemandRow{}
	for rows.Next() {
		var i PendingAssignmentDemandRow
		if err := rows.Scan(
			&i.PoolID,
			&i.N,
			&i.CpuMillis,
			&i.MemoryMb,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pendingProvisioningDemand = `-- name: PendingProvisioningDemand :many
SELECT sa.pool_id, count(*) AS n
FROM step_assignments sa
WHERE sa.status = 'pending'
  AND NOT EXISTS (
    SELECT 1
    FROM step_assignments held
    JOIN machines m ON m.id = held.machine_id
    WHERE held.run_id = sa.run_id
      AND m.pool_id = sa.pool_id
      AND m.status IN ('idle', 'busy')
      AND held.status IN ('assigned', 'running', 'succeeded', 'failed')
  )
GROUP BY sa.pool_id
`

type PendingProvisioningDemandRow struct {
	PoolID string `json:"pool_id"`
	N      int64  `json:"n"`
}

// Fleet provisioner input: pending demand a NEW machine can actually serve.
// Excludes pending assignments whose run is already pinned by HARD affinity to a
// live (idle/busy) holder machine in the same pool — booting can't take that work
// (it can only run on the holder), so it must not inflate the provisioning
// deficit. The affinity rule mirrors MachineFreeCapacity: assigned/running/
// succeeded/failed pin a run to its workspace machine; lost/cancelled don't.
func (q *Queries) PendingProvisioningDemand(ctx context.Context) ([]PendingProvisioningDemandRow, error) {
	rows, err := q.db.Query(ctx, pendingProvisioningDemand)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PendingProvisioningDemandRow{}
	for rows.Next() {
		var i PendingProvisioningDemandRow
		if err := rows.Scan(&i.PoolID, &i.N); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pendingProvisioningDemandByGroup = `-- name: PendingProvisioningDemandByGroup :many
SELECT sa.pool_id,
       COALESCE(pr.branch, '') AS branch,
       COALESCE(pr.trigger_type, '') AS event,
       count(*) AS n
FROM step_assignments sa
LEFT JOIN pipeline_runs pr ON pr.id = sa.run_id
WHERE sa.status = 'pending'
  AND NOT EXISTS (
    SELECT 1
    FROM step_assignments held
    JOIN machines m ON m.id = held.machine_id
    WHERE held.run_id = sa.run_id
      AND m.pool_id = sa.pool_id
      AND m.status IN ('idle', 'busy')
      AND held.status IN ('assigned', 'running', 'succeeded', 'failed')
  )
GROUP BY sa.pool_id, pr.branch, pr.trigger_type
`

type PendingProvisioningDemandByGroupRow struct {
	PoolID string `json:"pool_id"`
	Branch string `json:"branch"`
	Event  string `json:"event"`
	N      int64  `json:"n"`
}

// Same provisionable demand as PendingProvisioningDemand, but split by the run's
// (branch, event) so the fleet can resolve per-branch/event economics policy
// (main → stable, PRs → interruptible) before quoting. Joins pipeline_runs for
// the branch/trigger_type; a run with a null branch/type collapses to ” (the
// wildcard context, which only matches an override whose field is also empty).
// LEFT JOIN so demand never vanishes when a run row is missing (it collapses to
// the ” wildcard context instead) — an INNER JOIN would silently drop such
// assignments from the provisioning deficit.
func (q *Queries) PendingProvisioningDemandByGroup(ctx context.Context) ([]PendingProvisioningDemandByGroupRow, error) {
	rows, err := q.db.Query(ctx, pendingProvisioningDemandByGroup)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PendingProvisioningDemandByGroupRow{}
	for rows.Next() {
		var i PendingProvisioningDemandByGroupRow
		if err := rows.Scan(
			&i.PoolID,
			&i.Branch,
			&i.Event,
			&i.N,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const releaseUnclaimedAssignments = `-- name: ReleaseUnclaimedAssignments :many
UPDATE step_assignments SET
    status = 'pending', machine_id = NULL, assigned_at = NULL, claim_deadline_at = NULL
WHERE id IN (
    SELECT id FROM step_assignments
    WHERE status = 'assigned' AND claim_deadline_at < now()
    FOR UPDATE SKIP LOCKED
)
RETURNING id, machine_id
`

type ReleaseUnclaimedAssignmentsRow struct {
	ID        string  `json:"id"`
	MachineID *string `json:"machine_id"`
}

// Sweep: assigned but never claimed before the deadline → back to pending. The
// machine gets a strike (tracked by the fleet loop, not here).
func (q *Queries) ReleaseUnclaimedAssignments(ctx context.Context) ([]ReleaseUnclaimedAssignmentsRow, error) {
	rows, err := q.db.Query(ctx, releaseUnclaimedAssignments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReleaseUnclaimedAssignmentsRow{}
	for rows.Next() {
		var i ReleaseUnclaimedAssignmentsRow
		if err := rows.Scan(&i.ID, &i.MachineID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const requestAssignmentCancel = `-- name: RequestAssignmentCancel :execrows
UPDATE step_assignments SET cancel_requested = true
WHERE run_id = $1 AND status = 'running'
`

// Running work: flag for delivery via the ExecuteStep stream or next heartbeat.
func (q *Queries) RequestAssignmentCancel(ctx context.Context, runID string) (int64, error) {
	result, err := q.db.Exec(ctx, requestAssignmentCancel, runID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const staleRunningAssignmentsForMachine = `-- name: StaleRunningAssignmentsForMachine :many
SELECT id, step_id, workflow_id, run_id, step_name, attempt
FROM step_assignments
WHERE machine_id = $1
  AND status = 'running'
  AND started_at < now() - make_interval(secs := $2::double precision)
  AND NOT (id = ANY($3::uuid[]))
`

type StaleRunningAssignmentsForMachineParams struct {
	MachineID *string  `json:"machine_id"`
	GraceSecs float64  `json:"grace_secs"`
	ActiveIds []string `json:"active_ids"`
}

type StaleRunningAssignmentsForMachineRow struct {
	ID         string `json:"id"`
	StepID     string `json:"step_id"`
	WorkflowID string `json:"workflow_id"`
	RunID      string `json:"run_id"`
	StepName   string `json:"step_name"`
	Attempt    int32  `json:"attempt"`
}

// Agent-restart recovery: 'running' assignments the machine's heartbeat no
// longer claims, past a grace period since they started.
func (q *Queries) StaleRunningAssignmentsForMachine(ctx context.Context, arg StaleRunningAssignmentsForMachineParams) ([]StaleRunningAssignmentsForMachineRow, error) {
	rows, err := q.db.Query(ctx, staleRunningAssignmentsForMachine, arg.MachineID, arg.GraceSecs, arg.ActiveIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StaleRunningAssignmentsForMachineRow{}
	for rows.Next() {
		var i StaleRunningAssignmentsForMachineRow
		if err := rows.Scan(
			&i.ID,
			&i.StepID,
			&i.WorkflowID,
			&i.RunID,
			&i.StepName,
			&i.Attempt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const terminalRunIDs = `-- name: TerminalRunIDs :many
SELECT id FROM pipeline_runs
WHERE id = ANY($1::uuid[])
  AND status IN ('succeeded', 'failed', 'cancelled')
`

// Heartbeat GC input: of the run ids resident on a machine's disk, which have
// reached a terminal state (their workspace dirs are safe to delete).
func (q *Queries) TerminalRunIDs(ctx context.Context, runIds []string) ([]string, error) {
	rows, err := q.db.Query(ctx, terminalRunIDs, runIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
