// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tag_keys.sql

package db

import (
	"context"
	"time"
)

const createTagKey = `-- name: CreateTagKey :one
INSERT INTO tag_keys (org_id, key, label, allowed_values, color)
VALUES ($1, $2, $3, $4, $5)
RETURNING id
`

type CreateTagKeyParams struct {
	OrgID         string   `json:"org_id"`
	Key           string   `json:"key"`
	Label         string   `json:"label"`
	AllowedValues []string `json:"allowed_values"`
	Color         string   `json:"color"`
}

func (q *Queries) CreateTagKey(ctx context.Context, arg CreateTagKeyParams) (string, error) {
	row := q.db.QueryRow(ctx, createTagKey,
		arg.OrgID,
		arg.Key,
		arg.Label,
		arg.AllowedValues,
		arg.Color,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}

const deleteTagKey = `-- name: DeleteTagKey :execrows
DELETE FROM tag_keys WHERE id = $1
`

func (q *Queries) DeleteTagKey(ctx context.Context, id string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteTagKey, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listTagKeys = `-- name: ListTagKeys :many
SELECT id, key, label, allowed_values, color, created_at
FROM tag_keys WHERE org_id = $1 ORDER BY key
`

type ListTagKeysRow struct {
	ID            string    `json:"id"`
	Key           string    `json:"key"`
	Label         string    `json:"label"`
	AllowedValues []string  `json:"allowed_values"`
	Color         string    `json:"color"`
	CreatedAt     time.Time `json:"created_at"`
}

func (q *Queries) ListTagKeys(ctx context.Context, orgID string) ([]ListTagKeysRow, error) {
	rows, err := q.db.Query(ctx, listTagKeys, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTagKeysRow{}
	for rows.Next() {
		var i ListTagKeysRow
		if err := rows.Scan(
			&i.ID,
			&i.Key,
			&i.Label,
			&i.AllowedValues,
			&i.Color,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTagKey = `-- name: UpdateTagKey :exec
UPDATE tag_keys
SET label = $2, allowed_values = $3, color = $4
WHERE id = $1
`

type UpdateTagKeyParams struct {
	ID            string   `json:"id"`
	Label         string   `json:"label"`
	AllowedValues []string `json:"allowed_values"`
	Color         string   `json:"color"`
}

func (q *Queries) UpdateTagKey(ctx context.Context, arg UpdateTagKeyParams) error {
	_, err := q.db.Exec(ctx, updateTagKey,
		arg.ID,
		arg.Label,
		arg.AllowedValues,
		arg.Color,
	)
	return err
}
