// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: timers.sql

package db

import (
	"context"
	"time"
)

const cancelAllWorkflowTimers = `-- name: CancelAllWorkflowTimers :exec
UPDATE timers SET fired = true WHERE workflow_id = $1 AND fired = false
`

func (q *Queries) CancelAllWorkflowTimers(ctx context.Context, workflowID string) error {
	_, err := q.db.Exec(ctx, cancelAllWorkflowTimers, workflowID)
	return err
}

const cancelTimer = `-- name: CancelTimer :exec
UPDATE timers SET fired = true
WHERE workflow_id = $1 AND step_name = $2 AND timer_type = $3 AND fired = false
`

type CancelTimerParams struct {
	WorkflowID string `json:"workflow_id"`
	StepName   string `json:"step_name"`
	TimerType  string `json:"timer_type"`
}

func (q *Queries) CancelTimer(ctx context.Context, arg CancelTimerParams) error {
	_, err := q.db.Exec(ctx, cancelTimer, arg.WorkflowID, arg.StepName, arg.TimerType)
	return err
}

const cleanupFiredTimers = `-- name: CleanupFiredTimers :exec
DELETE FROM timers WHERE fired = true AND created_at < now() - interval '1 hour'
`

func (q *Queries) CleanupFiredTimers(ctx context.Context) error {
	_, err := q.db.Exec(ctx, cleanupFiredTimers)
	return err
}

const createTimer = `-- name: CreateTimer :exec
INSERT INTO timers (workflow_id, step_name, timer_type, fires_at)
VALUES ($1, $2, $3, now() + make_interval(secs := $4))
ON CONFLICT (workflow_id, step_name, timer_type) DO NOTHING
`

type CreateTimerParams struct {
	WorkflowID string  `json:"workflow_id"`
	StepName   string  `json:"step_name"`
	TimerType  string  `json:"timer_type"`
	Secs       float64 `json:"secs"`
}

func (q *Queries) CreateTimer(ctx context.Context, arg CreateTimerParams) error {
	_, err := q.db.Exec(ctx, createTimer,
		arg.WorkflowID,
		arg.StepName,
		arg.TimerType,
		arg.Secs,
	)
	return err
}

const lockNextDueTimer = `-- name: LockNextDueTimer :one
SELECT id, workflow_id, step_name, timer_type
FROM timers
WHERE fired = false AND fires_at <= now()
ORDER BY fires_at
LIMIT 1
FOR UPDATE SKIP LOCKED
`

type LockNextDueTimerRow struct {
	ID         string `json:"id"`
	WorkflowID string `json:"workflow_id"`
	StepName   string `json:"step_name"`
	TimerType  string `json:"timer_type"`
}

// Claims one due timer, locking the row (FOR UPDATE SKIP LOCKED) for the duration
// of the caller's transaction. The caller handles the timer's effect and marks it
// fired in the SAME transaction, so `fired = true` only commits if the effect
// commits — a crash mid-handle rolls back and the timer is retried next tick
// (exactly-once handling, not the previous at-most-once).
func (q *Queries) LockNextDueTimer(ctx context.Context) (LockNextDueTimerRow, error) {
	row := q.db.QueryRow(ctx, lockNextDueTimer)
	var i LockNextDueTimerRow
	err := row.Scan(
		&i.ID,
		&i.WorkflowID,
		&i.StepName,
		&i.TimerType,
	)
	return i, err
}

const markTimerFired = `-- name: MarkTimerFired :exec
UPDATE timers SET fired = true WHERE id = $1
`

func (q *Queries) MarkTimerFired(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, markTimerFired, id)
	return err
}

const nextTimerDue = `-- name: NextTimerDue :one
SELECT min(fires_at)::timestamptz FROM timers WHERE fired = false
`

// The soonest unfired timer, used by the adaptive poll to cap its backoff —
// a due timer must not wait out a long idle-poll interval.
func (q *Queries) NextTimerDue(ctx context.Context) (time.Time, error) {
	row := q.db.QueryRow(ctx, nextTimerDue)
	var column_1 time.Time
	err := row.Scan(&column_1)
	return column_1, err
}

const upsertTimer = `-- name: UpsertTimer :exec
INSERT INTO timers (workflow_id, step_name, timer_type, fires_at)
VALUES ($1, $2, $3, now() + make_interval(secs := $4))
ON CONFLICT (workflow_id, step_name, timer_type)
DO UPDATE SET fires_at = EXCLUDED.fires_at, fired = false
`

type UpsertTimerParams struct {
	WorkflowID string  `json:"workflow_id"`
	StepName   string  `json:"step_name"`
	TimerType  string  `json:"timer_type"`
	Secs       float64 `json:"secs"`
}

func (q *Queries) UpsertTimer(ctx context.Context, arg UpsertTimerParams) error {
	_, err := q.db.Exec(ctx, upsertTimer,
		arg.WorkflowID,
		arg.StepName,
		arg.TimerType,
		arg.Secs,
	)
	return err
}
