// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: timers.sql

package db

import (
	"context"
)

const cancelAllWorkflowTimers = `-- name: CancelAllWorkflowTimers :exec
UPDATE timers SET fired = true WHERE workflow_id = $1 AND fired = false
`

func (q *Queries) CancelAllWorkflowTimers(ctx context.Context, workflowID string) error {
	_, err := q.db.Exec(ctx, cancelAllWorkflowTimers, workflowID)
	return err
}

const cancelTimer = `-- name: CancelTimer :exec
UPDATE timers SET fired = true
WHERE workflow_id = $1 AND step_name = $2 AND timer_type = $3 AND fired = false
`

type CancelTimerParams struct {
	WorkflowID string `json:"workflow_id"`
	StepName   string `json:"step_name"`
	TimerType  string `json:"timer_type"`
}

func (q *Queries) CancelTimer(ctx context.Context, arg CancelTimerParams) error {
	_, err := q.db.Exec(ctx, cancelTimer, arg.WorkflowID, arg.StepName, arg.TimerType)
	return err
}

const cleanupFiredTimers = `-- name: CleanupFiredTimers :exec
DELETE FROM timers WHERE fired = true AND created_at < now() - interval '1 hour'
`

func (q *Queries) CleanupFiredTimers(ctx context.Context) error {
	_, err := q.db.Exec(ctx, cleanupFiredTimers)
	return err
}

const createTimer = `-- name: CreateTimer :exec
INSERT INTO timers (workflow_id, step_name, timer_type, fires_at)
VALUES ($1, $2, $3, now() + make_interval(secs := $4))
ON CONFLICT (workflow_id, step_name, timer_type) DO NOTHING
`

type CreateTimerParams struct {
	WorkflowID string  `json:"workflow_id"`
	StepName   string  `json:"step_name"`
	TimerType  string  `json:"timer_type"`
	Secs       float64 `json:"secs"`
}

func (q *Queries) CreateTimer(ctx context.Context, arg CreateTimerParams) error {
	_, err := q.db.Exec(ctx, createTimer,
		arg.WorkflowID,
		arg.StepName,
		arg.TimerType,
		arg.Secs,
	)
	return err
}

const fireDueTimers = `-- name: FireDueTimers :many
UPDATE timers SET fired = true
WHERE id IN (
    SELECT id FROM timers
    WHERE fired = false AND fires_at <= now()
    ORDER BY fires_at
    LIMIT 100
    FOR UPDATE SKIP LOCKED
)
RETURNING id, workflow_id, step_name, timer_type
`

type FireDueTimersRow struct {
	ID         string `json:"id"`
	WorkflowID string `json:"workflow_id"`
	StepName   string `json:"step_name"`
	TimerType  string `json:"timer_type"`
}

func (q *Queries) FireDueTimers(ctx context.Context) ([]FireDueTimersRow, error) {
	rows, err := q.db.Query(ctx, fireDueTimers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FireDueTimersRow{}
	for rows.Next() {
		var i FireDueTimersRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkflowID,
			&i.StepName,
			&i.TimerType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertTimer = `-- name: UpsertTimer :exec
INSERT INTO timers (workflow_id, step_name, timer_type, fires_at)
VALUES ($1, $2, $3, now() + make_interval(secs := $4))
ON CONFLICT (workflow_id, step_name, timer_type)
DO UPDATE SET fires_at = EXCLUDED.fires_at, fired = false
`

type UpsertTimerParams struct {
	WorkflowID string  `json:"workflow_id"`
	StepName   string  `json:"step_name"`
	TimerType  string  `json:"timer_type"`
	Secs       float64 `json:"secs"`
}

func (q *Queries) UpsertTimer(ctx context.Context, arg UpsertTimerParams) error {
	_, err := q.db.Exec(ctx, upsertTimer,
		arg.WorkflowID,
		arg.StepName,
		arg.TimerType,
		arg.Secs,
	)
	return err
}
