// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: webhooks.sql

package db

import (
	"context"
)

const createWebhook = `-- name: CreateWebhook :one
INSERT INTO webhooks (project_id, url, secret, events)
VALUES ($1, $2, $3, $4)
RETURNING id
`

type CreateWebhookParams struct {
	ProjectID string `json:"project_id"`
	Url       string `json:"url"`
	Secret    string `json:"secret"`
	Events    []byte `json:"events"`
}

func (q *Queries) CreateWebhook(ctx context.Context, arg CreateWebhookParams) (string, error) {
	row := q.db.QueryRow(ctx, createWebhook,
		arg.ProjectID,
		arg.Url,
		arg.Secret,
		arg.Events,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}

const deleteWebhook = `-- name: DeleteWebhook :exec
DELETE FROM webhooks WHERE id = $1 AND project_id = $2
`

type DeleteWebhookParams struct {
	ID        string `json:"id"`
	ProjectID string `json:"project_id"`
}

func (q *Queries) DeleteWebhook(ctx context.Context, arg DeleteWebhookParams) error {
	_, err := q.db.Exec(ctx, deleteWebhook, arg.ID, arg.ProjectID)
	return err
}

const getActiveWebhooksForEvent = `-- name: GetActiveWebhooksForEvent :many
SELECT w.id, w.url, w.secret
FROM webhooks w
JOIN projects p ON w.project_id = p.id
JOIN pipeline_runs pr ON pr.project_id = p.id
WHERE pr.id = $1
  AND w.is_active = true
  AND w.events @> to_jsonb($2::text)
`

type GetActiveWebhooksForEventParams struct {
	ID      string `json:"id"`
	Column2 string `json:"column_2"`
}

type GetActiveWebhooksForEventRow struct {
	ID     string `json:"id"`
	Url    string `json:"url"`
	Secret string `json:"secret"`
}

func (q *Queries) GetActiveWebhooksForEvent(ctx context.Context, arg GetActiveWebhooksForEventParams) ([]GetActiveWebhooksForEventRow, error) {
	rows, err := q.db.Query(ctx, getActiveWebhooksForEvent, arg.ID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetActiveWebhooksForEventRow{}
	for rows.Next() {
		var i GetActiveWebhooksForEventRow
		if err := rows.Scan(&i.ID, &i.Url, &i.Secret); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectWebhooks = `-- name: ListProjectWebhooks :many
SELECT id, project_id, url, secret, events, is_active, created_at
FROM webhooks WHERE project_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListProjectWebhooks(ctx context.Context, projectID string) ([]Webhook, error) {
	rows, err := q.db.Query(ctx, listProjectWebhooks, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Webhook{}
	for rows.Next() {
		var i Webhook
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Url,
			&i.Secret,
			&i.Events,
			&i.IsActive,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
