// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: workflows.sql

package db

import (
	"context"
	"time"
)

const cancelChildWorkflows = `-- name: CancelChildWorkflows :exec
UPDATE workflows SET status = 'cancelled', cancelled_at = now(), finished_at = now()
WHERE parent_id = $1 AND status IN ('pending', 'running')
`

func (q *Queries) CancelChildWorkflows(ctx context.Context, parentID *string) error {
	_, err := q.db.Exec(ctx, cancelChildWorkflows, parentID)
	return err
}

const cancelWorkflow = `-- name: CancelWorkflow :exec
UPDATE workflows SET status = 'cancelled', cancelled_at = now(), finished_at = now()
WHERE id = $1 AND status IN ('pending', 'running')
`

func (q *Queries) CancelWorkflow(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, cancelWorkflow, id)
	return err
}

const finishWorkflow = `-- name: FinishWorkflow :exec
UPDATE workflows SET status = $2, finished_at = now() WHERE id = $1
`

type FinishWorkflowParams struct {
	ID     string `json:"id"`
	Status string `json:"status"`
}

func (q *Queries) FinishWorkflow(ctx context.Context, arg FinishWorkflowParams) error {
	_, err := q.db.Exec(ctx, finishWorkflow, arg.ID, arg.Status)
	return err
}

const getExistingWorkflow = `-- name: GetExistingWorkflow :one
SELECT id FROM workflows WHERE run_id = $1 AND parent_id IS NULL
`

func (q *Queries) GetExistingWorkflow(ctx context.Context, runID string) (string, error) {
	row := q.db.QueryRow(ctx, getExistingWorkflow, runID)
	var id string
	err := row.Scan(&id)
	return id, err
}

const getWorkflowDAGWaves = `-- name: GetWorkflowDAGWaves :one
SELECT dag_waves FROM workflows WHERE id = $1
`

func (q *Queries) GetWorkflowDAGWaves(ctx context.Context, id string) ([]byte, error) {
	row := q.db.QueryRow(ctx, getWorkflowDAGWaves, id)
	var dag_waves []byte
	err := row.Scan(&dag_waves)
	return dag_waves, err
}

const getWorkflowInput = `-- name: GetWorkflowInput :one
SELECT input FROM workflows WHERE id = $1
`

func (q *Queries) GetWorkflowInput(ctx context.Context, id string) ([]byte, error) {
	row := q.db.QueryRow(ctx, getWorkflowInput, id)
	var input []byte
	err := row.Scan(&input)
	return input, err
}

const getWorkflowInputs = `-- name: GetWorkflowInputs :many
SELECT id, input FROM workflows WHERE id = ANY($1::uuid[])
`

type GetWorkflowInputsRow struct {
	ID    string `json:"id"`
	Input []byte `json:"input"`
}

// Batch variant: fetch inputs for all workflows in a claimed step batch in one
// round-trip (kills the per-step N+1 in claimAndDispatch).
func (q *Queries) GetWorkflowInputs(ctx context.Context, workflowIds []string) ([]GetWorkflowInputsRow, error) {
	rows, err := q.db.Query(ctx, getWorkflowInputs, workflowIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetWorkflowInputsRow{}
	for rows.Next() {
		var i GetWorkflowInputsRow
		if err := rows.Scan(&i.ID, &i.Input); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getWorkflowParent = `-- name: GetWorkflowParent :one
SELECT parent_id, parent_step FROM workflows WHERE id = $1
`

type GetWorkflowParentRow struct {
	ParentID   *string `json:"parent_id"`
	ParentStep *string `json:"parent_step"`
}

func (q *Queries) GetWorkflowParent(ctx context.Context, id string) (GetWorkflowParentRow, error) {
	row := q.db.QueryRow(ctx, getWorkflowParent, id)
	var i GetWorkflowParentRow
	err := row.Scan(&i.ParentID, &i.ParentStep)
	return i, err
}

const getWorkflowStatus = `-- name: GetWorkflowStatus :one
SELECT run_id, status, started_at, finished_at FROM workflows WHERE id = $1
`

type GetWorkflowStatusRow struct {
	RunID      string     `json:"run_id"`
	Status     string     `json:"status"`
	StartedAt  *time.Time `json:"started_at"`
	FinishedAt *time.Time `json:"finished_at"`
}

func (q *Queries) GetWorkflowStatus(ctx context.Context, id string) (GetWorkflowStatusRow, error) {
	row := q.db.QueryRow(ctx, getWorkflowStatus, id)
	var i GetWorkflowStatusRow
	err := row.Scan(
		&i.RunID,
		&i.Status,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const insertWorkflow = `-- name: InsertWorkflow :one
INSERT INTO workflows (run_id, parent_id, parent_step, status, input)
VALUES ($1, $2, $3, 'pending', $4)
RETURNING id
`

type InsertWorkflowParams struct {
	RunID      string  `json:"run_id"`
	ParentID   *string `json:"parent_id"`
	ParentStep *string `json:"parent_step"`
	Input      []byte  `json:"input"`
}

func (q *Queries) InsertWorkflow(ctx context.Context, arg InsertWorkflowParams) (string, error) {
	row := q.db.QueryRow(ctx, insertWorkflow,
		arg.RunID,
		arg.ParentID,
		arg.ParentStep,
		arg.Input,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}

const lockWorkflow = `-- name: LockWorkflow :one
SELECT status, dag_waves, step_outputs, input
FROM workflows WHERE id = $1 FOR UPDATE
`

type LockWorkflowRow struct {
	Status      string `json:"status"`
	DagWaves    []byte `json:"dag_waves"`
	StepOutputs []byte `json:"step_outputs"`
	Input       []byte `json:"input"`
}

func (q *Queries) LockWorkflow(ctx context.Context, id string) (LockWorkflowRow, error) {
	row := q.db.QueryRow(ctx, lockWorkflow, id)
	var i LockWorkflowRow
	err := row.Scan(
		&i.Status,
		&i.DagWaves,
		&i.StepOutputs,
		&i.Input,
	)
	return i, err
}

const recentlyFinishedRunIDs = `-- name: RecentlyFinishedRunIDs :many
SELECT DISTINCT pr.id AS run_id FROM pipeline_runs pr
JOIN workflows w ON w.run_id = pr.id
WHERE w.status IN ('succeeded', 'failed', 'cancelled')
AND w.finished_at >= now() - interval '10 minutes'
AND w.parent_id IS NULL
`

func (q *Queries) RecentlyFinishedRunIDs(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, recentlyFinishedRunIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var run_id string
		if err := rows.Scan(&run_id); err != nil {
			return nil, err
		}
		items = append(items, run_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sweepStaleWorkflows = `-- name: SweepStaleWorkflows :exec
UPDATE workflows SET status = 'failed', finished_at = now()
WHERE status = 'running'
AND NOT EXISTS (
    SELECT 1 FROM steps
    WHERE workflow_id = workflows.id
    AND status NOT IN ('succeeded', 'failed', 'skipped', 'cancelled')
)
`

func (q *Queries) SweepStaleWorkflows(ctx context.Context) error {
	_, err := q.db.Exec(ctx, sweepStaleWorkflows)
	return err
}

const updateStepOutputs = `-- name: UpdateStepOutputs :exec
UPDATE workflows SET step_outputs = step_outputs || $2::jsonb WHERE id = $1
`

type UpdateStepOutputsParams struct {
	ID      string `json:"id"`
	Column2 []byte `json:"column_2"`
}

func (q *Queries) UpdateStepOutputs(ctx context.Context, arg UpdateStepOutputsParams) error {
	_, err := q.db.Exec(ctx, updateStepOutputs, arg.ID, arg.Column2)
	return err
}

const updateWorkflowPipeline = `-- name: UpdateWorkflowPipeline :exec
UPDATE workflows SET pipeline_yaml = $2, pipeline_def = $3, dag_waves = $4,
    status = 'running', started_at = now()
WHERE id = $1
`

type UpdateWorkflowPipelineParams struct {
	ID           string `json:"id"`
	PipelineYaml []byte `json:"pipeline_yaml"`
	PipelineDef  []byte `json:"pipeline_def"`
	DagWaves     []byte `json:"dag_waves"`
}

func (q *Queries) UpdateWorkflowPipeline(ctx context.Context, arg UpdateWorkflowPipelineParams) error {
	_, err := q.db.Exec(ctx, updateWorkflowPipeline,
		arg.ID,
		arg.PipelineYaml,
		arg.PipelineDef,
		arg.DagWaves,
	)
	return err
}
