// Package wsagent implements the workspace agent gRPC server.
//
// The workspace agent runs as a dedicated pod for the duration of a pipeline
// run. It exposes the WorkspaceService gRPC API backed by a local emptyDir
// volume, giving all step pods a fast, in-cluster shared filesystem without
// requiring cluster-level storage drivers.
//
// NOTE: This package imports protogen/workspace/v1 which is generated by
// `task proto-gen`. Run that command before building.
package wsagent

import (
	"context"
	"fmt"
	"io"
	"net"
	"os"
	"os/signal"
	"sync"
	"sync/atomic"
	"syscall"
	"time"

	"github.com/NerdMeNot/flint/pkg/wsfs"
	workspacev1 "github.com/NerdMeNot/flint/protogen/workspace/v1"
	"github.com/rs/zerolog/log"
	"github.com/zeebo/xxh3"
	"google.golang.org/grpc"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/reflection"
	"google.golang.org/grpc/status"
)

// Server implements WorkspaceServiceServer backed by a LocalFS.
// It maintains an in-memory manifest of all stored files so that agents can
// perform incremental sync using GetManifest + targeted Put/Get calls.
type Server struct {
	workspacev1.UnimplementedWorkspaceServiceServer

	fs *wsfs.LocalFS

	mu       sync.RWMutex
	manifest wsfs.Manifest // path → ManifestEntry, updated on every Put/Remove
	version  atomic.Int64  // incremented on every manifest mutation
}

// NewServer creates a Server rooted at dir. dir must exist.
func NewServer(dir string) (*Server, error) {
	lfs, err := wsfs.NewLocal(dir)
	if err != nil {
		return nil, fmt.Errorf("wsagent: init filesystem: %w", err)
	}
	return &Server{
		fs:       lfs,
		manifest: make(wsfs.Manifest),
	}, nil
}

// ListenAndServe starts the gRPC server on addr, authenticates all calls
// with token, and blocks until SIGTERM/SIGINT or the context is cancelled.
// It performs a graceful shutdown with a 15-second drain window.
func ListenAndServe(ctx context.Context, addr, token, rootDir string) error {
	srv, err := NewServer(rootDir)
	if err != nil {
		return err
	}

	unaryInt, streamInt := NewTokenInterceptors(token)
	grpcSrv := grpc.NewServer(
		grpc.ChainUnaryInterceptor(unaryInt),
		grpc.ChainStreamInterceptor(streamInt),
	)
	workspacev1.RegisterWorkspaceServiceServer(grpcSrv, srv)
	reflection.Register(grpcSrv) // aids debugging; does not bypass auth

	lis, err := net.Listen("tcp", addr)
	if err != nil {
		return fmt.Errorf("wsagent: listen %s: %w", addr, err)
	}

	log.Info().
		Str("addr", addr).
		Str("root", rootDir).
		Msg("workspace agent listening")

	// Serve in a goroutine so we can handle shutdown signals.
	serveErr := make(chan error, 1)
	go func() {
		if err := grpcSrv.Serve(lis); err != nil {
			serveErr <- err
		}
		close(serveErr)
	}()

	// Wait for context cancellation or OS signal.
	quit := make(chan os.Signal, 1)
	signal.Notify(quit, syscall.SIGTERM, syscall.SIGINT)
	defer signal.Stop(quit)

	select {
	case <-ctx.Done():
		log.Info().Msg("workspace agent: context cancelled, shutting down")
	case sig := <-quit:
		log.Info().Str("signal", sig.String()).Msg("workspace agent: signal received, shutting down")
	case err := <-serveErr:
		return err
	}

	// Graceful stop: give in-flight RPCs up to 15 seconds to complete.
	stopped := make(chan struct{})
	go func() {
		grpcSrv.GracefulStop()
		close(stopped)
	}()
	select {
	case <-stopped:
	case <-time.After(15 * time.Second):
		log.Warn().Msg("workspace agent: graceful stop timed out, forcing")
		grpcSrv.Stop()
	}

	return <-serveErr
}

// ─────────────────────────────────────────────────────────────
// WorkspaceService RPC implementations
// ─────────────────────────────────────────────────────────────

// Put receives a client-streaming upload. The first message must carry the
// destination path; subsequent messages carry content chunks.
// The server computes an xxh3 hash of the received content and updates the
// in-memory manifest on successful completion.
func (s *Server) Put(stream workspacev1.WorkspaceService_PutServer) error {
	// First message: path declaration.
	first, err := stream.Recv()
	if err != nil {
		return status.Errorf(codes.InvalidArgument, "expected path message: %v", err)
	}
	pathMsg, ok := first.Data.(*workspacev1.PutRequest_Path)
	if !ok || pathMsg.Path == "" {
		return status.Error(codes.InvalidArgument, "first Put message must declare the destination path")
	}

	w, err := s.fs.Create(stream.Context(), pathMsg.Path)
	if err != nil {
		return mapFSError("create", pathMsg.Path, err)
	}
	defer w.Close()

	h := xxh3.New()
	var total int64

	for {
		msg, err := stream.Recv()
		if err == io.EOF {
			break
		}
		if err != nil {
			return status.Errorf(codes.Internal, "recv chunk: %v", err)
		}
		chunk, ok := msg.Data.(*workspacev1.PutRequest_Chunk)
		if !ok {
			return status.Error(codes.InvalidArgument, "unexpected path message mid-stream")
		}
		n, err := w.Write(chunk.Chunk)
		if err != nil {
			return status.Errorf(codes.Internal, "write chunk: %v", err)
		}
		h.Write(chunk.Chunk) //nolint:errcheck // xxh3 never errors
		total += int64(n)
	}

	if err := w.Close(); err != nil {
		return status.Errorf(codes.Internal, "close file: %v", err)
	}

	// Update manifest.
	hash := fmt.Sprintf("%x", h.Sum64())
	s.mu.Lock()
	s.manifest[pathMsg.Path] = wsfs.ManifestEntry{
		Hash:  hash,
		Size:  total,
		Mtime: time.Now().Unix(),
	}
	s.version.Add(1)
	s.mu.Unlock()

	log.Debug().
		Str("path", pathMsg.Path).
		Int64("bytes", total).
		Str("hash", hash[:8]+"…").
		Msg("wsagent: put complete")

	return stream.SendAndClose(&workspacev1.PutResponse{BytesWritten: total})
}

// Get opens the requested file and streams its content in 256 KiB chunks.
func (s *Server) Get(req *workspacev1.GetRequest, stream workspacev1.WorkspaceService_GetServer) error {
	r, err := s.fs.Open(stream.Context(), req.Path)
	if err != nil {
		return mapFSError("open", req.Path, err)
	}
	defer r.Close()

	const chunkSize = 256 * 1024
	buf := make([]byte, chunkSize)
	for {
		n, err := r.Read(buf)
		if n > 0 {
			chunk := make([]byte, n)
			copy(chunk, buf[:n])
			if sendErr := stream.Send(&workspacev1.GetResponse{Chunk: chunk}); sendErr != nil {
				return sendErr
			}
		}
		if err == io.EOF {
			return nil
		}
		if err != nil {
			return status.Errorf(codes.Internal, "read %q: %v", req.Path, err)
		}
	}
}

// Stat returns metadata for a single path.
func (s *Server) Stat(ctx context.Context, req *workspacev1.StatRequest) (*workspacev1.StatResponse, error) {
	info, err := s.fs.Stat(ctx, req.Path)
	if err != nil {
		return nil, mapFSError("stat", req.Path, err)
	}
	return &workspacev1.StatResponse{
		Name:        info.Name,
		Size:        info.Size,
		ModTimeUnix: info.ModTime.Unix(),
		IsDir:       info.IsDir,
	}, nil
}

// ReadDir lists directory entries.
func (s *Server) ReadDir(ctx context.Context, req *workspacev1.ReadDirRequest) (*workspacev1.ReadDirResponse, error) {
	entries, err := s.fs.ReadDir(ctx, req.Path)
	if err != nil {
		return nil, mapFSError("readdir", req.Path, err)
	}
	proto := make([]*workspacev1.DirEntry, 0, len(entries))
	for _, e := range entries {
		proto = append(proto, &workspacev1.DirEntry{
			Name:  e.Name,
			IsDir: e.IsDir,
			Size:  e.Size,
		})
	}
	return &workspacev1.ReadDirResponse{Entries: proto}, nil
}

// MkdirAll creates a directory and all required parents.
func (s *Server) MkdirAll(ctx context.Context, req *workspacev1.MkdirAllRequest) (*workspacev1.MkdirAllResponse, error) {
	if err := s.fs.MkdirAll(ctx, req.Path); err != nil {
		return nil, mapFSError("mkdirall", req.Path, err)
	}
	return &workspacev1.MkdirAllResponse{}, nil
}

// Remove deletes a file and removes it from the manifest.
func (s *Server) Remove(ctx context.Context, req *workspacev1.RemoveRequest) (*workspacev1.RemoveResponse, error) {
	if err := s.fs.Remove(ctx, req.Path); err != nil {
		return nil, mapFSError("remove", req.Path, err)
	}
	s.mu.Lock()
	delete(s.manifest, req.Path)
	s.version.Add(1)
	s.mu.Unlock()
	return &workspacev1.RemoveResponse{}, nil
}

// GetManifest returns the server's current file manifest and a monotonic
// version counter. The version counter is incremented on every Put or Remove,
// allowing agents to skip SyncIn when their cached version matches.
func (s *Server) GetManifest(_ context.Context, _ *workspacev1.GetManifestRequest) (*workspacev1.GetManifestResponse, error) {
	s.mu.RLock()
	entries := make([]*workspacev1.ManifestEntry, 0, len(s.manifest))
	for path, e := range s.manifest {
		entries = append(entries, &workspacev1.ManifestEntry{
			Path:      path,
			Hash:      e.Hash,
			Size:      e.Size,
			MtimeUnix: e.Mtime,
		})
	}
	version := s.version.Load()
	s.mu.RUnlock()

	return &workspacev1.GetManifestResponse{
		Entries: entries,
		Version: version,
	}, nil
}

// ─────────────────────────────────────────────────────────────
// helpers
// ─────────────────────────────────────────────────────────────

// mapFSError translates wsfs sentinel errors to gRPC status codes so that
// the remote client can reconstruct them via mapGRPCError.
func mapFSError(op, path string, err error) error {
	if err == nil {
		return nil
	}
	if wsfs.IsNotExist(err) {
		return status.Errorf(codes.NotFound, "%s %q: not found", op, path)
	}
	if wsfs.IsPermission(err) {
		return status.Errorf(codes.PermissionDenied, "%s %q: permission denied", op, path)
	}
	return status.Errorf(codes.Internal, "%s %q: %v", op, path, err)
}
