//go:build !ignore_autogenerated

// Code generated by hand. Regenerate with: task crd-gen
// controller-gen will replace this file when CRD generation is set up.

package v1

import (
	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyObject implements runtime.Object.
func (in *ForgeConnection) DeepCopyObject() runtime.Object {
	if in == nil {
		return nil
	}
	out := new(ForgeConnection)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all fields into another ForgeConnection.
func (in *ForgeConnection) DeepCopyInto(out *ForgeConnection) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

func (in *ForgeConnectionSpec) DeepCopyInto(out *ForgeConnectionSpec) {
	*out = *in
	if in.GitHub != nil {
		out.GitHub = new(GitHubConnectionSpec)
		*out.GitHub = *in.GitHub
	}
	if in.GitLab != nil {
		out.GitLab = new(GitLabConnectionSpec)
		*out.GitLab = *in.GitLab
	}
	if in.Bitbucket != nil {
		out.Bitbucket = new(BitbucketConnectionSpec)
		*out.Bitbucket = *in.Bitbucket
	}
}

func (in *ForgeConnectionStatus) DeepCopyInto(out *ForgeConnectionStatus) {
	*out = *in
	if in.Conditions != nil {
		out.Conditions = make([]metav1.Condition, len(in.Conditions))
		for i := range in.Conditions {
			in.Conditions[i].DeepCopyInto(&out.Conditions[i])
		}
	}
	if in.LastVerifiedAt != nil {
		out.LastVerifiedAt = in.LastVerifiedAt.DeepCopy()
	}
}

// DeepCopyObject implements runtime.Object.
func (in *ForgeConnectionList) DeepCopyObject() runtime.Object {
	if in == nil {
		return nil
	}
	out := new(ForgeConnectionList)
	in.DeepCopyInto(out)
	return out
}

func (in *ForgeConnectionList) DeepCopyInto(out *ForgeConnectionList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		out.Items = make([]ForgeConnection, len(in.Items))
		for i := range in.Items {
			in.Items[i].DeepCopyInto(&out.Items[i])
		}
	}
}

// DeepCopyObject implements runtime.Object.
func (in *Pipeline) DeepCopyObject() runtime.Object {
	if in == nil {
		return nil
	}
	out := new(Pipeline)
	in.DeepCopyInto(out)
	return out
}

func (in *Pipeline) DeepCopyInto(out *Pipeline) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

func (in *PipelineSpec) DeepCopyInto(out *PipelineSpec) {
	*out = *in
	if in.Tags != nil {
		out.Tags = make([]string, len(in.Tags))
		copy(out.Tags, in.Tags)
	}
	if in.PipelineSource != nil {
		out.PipelineSource = new(PipelineSourceSpec)
		*out.PipelineSource = *in.PipelineSource
	}
}

func (in *PipelineStatus) DeepCopyInto(out *PipelineStatus) {
	*out = *in
	if in.Conditions != nil {
		out.Conditions = make([]metav1.Condition, len(in.Conditions))
		for i := range in.Conditions {
			in.Conditions[i].DeepCopyInto(&out.Conditions[i])
		}
	}
	if in.LastSyncTime != nil {
		out.LastSyncTime = in.LastSyncTime.DeepCopy()
	}
}

// DeepCopyObject implements runtime.Object.
func (in *PipelineList) DeepCopyObject() runtime.Object {
	if in == nil {
		return nil
	}
	out := new(PipelineList)
	in.DeepCopyInto(out)
	return out
}

func (in *PipelineList) DeepCopyInto(out *PipelineList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		out.Items = make([]Pipeline, len(in.Items))
		for i := range in.Items {
			in.Items[i].DeepCopyInto(&out.Items[i])
		}
	}
}

// DeepCopyObject implements runtime.Object.
func (in *RunnerPool) DeepCopyObject() runtime.Object {
	if in == nil {
		return nil
	}
	out := new(RunnerPool)
	in.DeepCopyInto(out)
	return out
}

func (in *RunnerPool) DeepCopyInto(out *RunnerPool) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

func (in *RunnerPoolSpec) DeepCopyInto(out *RunnerPoolSpec) {
	*out = *in
	in.Profile.DeepCopyInto(&out.Profile)
	if in.Scheduling != nil {
		out.Scheduling = new(SchedulingSpec)
		in.Scheduling.DeepCopyInto(out.Scheduling)
	}
	if in.Spot != nil {
		out.Spot = new(SpotSpec)
		*out.Spot = *in.Spot
	}
}

func (in *ResourceProfileSpec) DeepCopyInto(out *ResourceProfileSpec) {
	*out = *in
	if in.GPU != nil {
		out.GPU = new(GPUSpec)
		*out.GPU = *in.GPU
	}
}

func (in *SchedulingSpec) DeepCopyInto(out *SchedulingSpec) {
	*out = *in
	if in.NodeSelector != nil {
		out.NodeSelector = make(map[string]string, len(in.NodeSelector))
		for k, v := range in.NodeSelector {
			out.NodeSelector[k] = v
		}
	}
	if in.Tolerations != nil {
		out.Tolerations = make([]corev1.Toleration, len(in.Tolerations))
		copy(out.Tolerations, in.Tolerations)
	}
}

func (in *RunnerPoolStatus) DeepCopyInto(out *RunnerPoolStatus) {
	*out = *in
	if in.Conditions != nil {
		out.Conditions = make([]metav1.Condition, len(in.Conditions))
		for i := range in.Conditions {
			in.Conditions[i].DeepCopyInto(&out.Conditions[i])
		}
	}
}

// DeepCopyObject implements runtime.Object.
func (in *RunnerPoolList) DeepCopyObject() runtime.Object {
	if in == nil {
		return nil
	}
	out := new(RunnerPoolList)
	in.DeepCopyInto(out)
	return out
}

func (in *RunnerPoolList) DeepCopyInto(out *RunnerPoolList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		out.Items = make([]RunnerPool, len(in.Items))
		for i := range in.Items {
			in.Items[i].DeepCopyInto(&out.Items[i])
		}
	}
}

// ── AuthProvider ────────────────────────────────────────────

func (in *AuthProvider) DeepCopyObject() runtime.Object {
	if in == nil {
		return nil
	}
	out := new(AuthProvider)
	in.DeepCopyInto(out)
	return out
}

func (in *AuthProvider) DeepCopyInto(out *AuthProvider) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

func (in *AuthProviderSpec) DeepCopyInto(out *AuthProviderSpec) {
	*out = *in
	if in.OIDC != nil {
		out.OIDC = new(OIDCProviderSpec)
		in.OIDC.DeepCopyInto(out.OIDC)
	}
	if in.SAML != nil {
		out.SAML = new(SAMLProviderSpec)
		in.SAML.DeepCopyInto(out.SAML)
	}
}

func (in *OIDCProviderSpec) DeepCopyInto(out *OIDCProviderSpec) {
	*out = *in
	if in.Scopes != nil {
		out.Scopes = make([]string, len(in.Scopes))
		copy(out.Scopes, in.Scopes)
	}
}

func (in *SAMLProviderSpec) DeepCopyInto(out *SAMLProviderSpec) {
	*out = *in
	if in.CertificateRef != nil {
		out.CertificateRef = new(SecretKeyRef)
		*out.CertificateRef = *in.CertificateRef
	}
	if in.PrivateKeyRef != nil {
		out.PrivateKeyRef = new(SecretKeyRef)
		*out.PrivateKeyRef = *in.PrivateKeyRef
	}
}

func (in *AuthProviderStatus) DeepCopyInto(out *AuthProviderStatus) {
	*out = *in
	if in.Conditions != nil {
		out.Conditions = make([]metav1.Condition, len(in.Conditions))
		for i := range in.Conditions {
			in.Conditions[i].DeepCopyInto(&out.Conditions[i])
		}
	}
	if in.LastVerifiedAt != nil {
		out.LastVerifiedAt = in.LastVerifiedAt.DeepCopy()
	}
}

func (in *AuthProviderList) DeepCopyObject() runtime.Object {
	if in == nil {
		return nil
	}
	out := new(AuthProviderList)
	in.DeepCopyInto(out)
	return out
}

func (in *AuthProviderList) DeepCopyInto(out *AuthProviderList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		out.Items = make([]AuthProvider, len(in.Items))
		for i := range in.Items {
			in.Items[i].DeepCopyInto(&out.Items[i])
		}
	}
}
