// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: agent/v1/agent.proto

package agentv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AgentService_RegisterMachine_FullMethodName    = "/agent.v1.AgentService/RegisterMachine"
	AgentService_ClaimStep_FullMethodName          = "/agent.v1.AgentService/ClaimStep"
	AgentService_ExecuteStep_FullMethodName        = "/agent.v1.AgentService/ExecuteStep"
	AgentService_ReportStepComplete_FullMethodName = "/agent.v1.AgentService/ReportStepComplete"
	AgentService_Heartbeat_FullMethodName          = "/agent.v1.AgentService/Heartbeat"
	AgentService_GetStepSecrets_FullMethodName     = "/agent.v1.AgentService/GetStepSecrets"
	AgentService_GetCloneToken_FullMethodName      = "/agent.v1.AgentService/GetCloneToken"
)

// AgentServiceClient is the client API for AgentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AgentService is the control-plane contract for the per-machine flint-agent
// daemon. The flow: a machine registers once (bootstrap or pool join token →
// per-machine bearer token), heartbeats every ~10s (lease keep-alive; drain/
// shutdown/cancel/GC signals piggyback on the response), long-polls ClaimStep
// for assigned work, streams logs over ExecuteStep while a step runs, and
// reports the outcome via ReportStepComplete (unary, so delivery survives a
// dropped stream).
//
// All RPCs except RegisterMachine authenticate with the machine bearer token
// (authorization: Bearer <token>). Data-plane pulls that carry a per-step task
// token (secrets, clone tokens) stay on the server's HTTP /internal endpoints.
type AgentServiceClient interface {
	// RegisterMachine exchanges a one-time bootstrap token (elastic machines,
	// minted at provider.Create) or a long-lived pool join token (static
	// machines) for the machine identity and bearer token.
	RegisterMachine(ctx context.Context, in *RegisterMachineRequest, opts ...grpc.CallOption) (*RegisterMachineResponse, error)
	// ClaimStep long-polls for work assigned to this machine (the server parks
	// the call up to wait_seconds, woken by the scheduler). The agent calls it
	// once per free execution slot.
	ClaimStep(ctx context.Context, in *ClaimStepRequest, opts ...grpc.CallOption) (*ClaimStepResponse, error)
	// ExecuteStep is a bidirectional stream for the lifetime of one step:
	// agent sends log batches / lifecycle updates, server sends cancellation.
	ExecuteStep(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ExecuteStepRequest, ExecuteStepResponse], error)
	// ReportStepComplete is the final, task-token-authenticated completion
	// report. Unary and retried so the engine hears the outcome even if the
	// stream died. Carries the log digest for tail repair.
	ReportStepComplete(ctx context.Context, in *ReportStepCompleteRequest, opts ...grpc.CallOption) (*ReportStepCompleteResponse, error)
	// Heartbeat keeps the machine's lease alive (~10s cadence; the server
	// expires machines at 3× the interval). The response is the server's
	// command channel: drain/shutdown, step cancellations, and workspace GC.
	Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error)
	// GetStepSecrets resolves a step's secret mapping at execution time. Pull
	// keeps secret values out of assignment payloads and the database: exposure
	// is bounded to the execution window, and the server re-checks that the
	// assignment is live and bound to the calling machine on every call.
	GetStepSecrets(ctx context.Context, in *GetStepSecretsRequest, opts ...grpc.CallOption) (*GetStepSecretsResponse, error)
	// GetCloneToken mints a short-lived forge token for git operations
	// (mirror fetches, checkout) scoped to the step's repository.
	GetCloneToken(ctx context.Context, in *GetCloneTokenRequest, opts ...grpc.CallOption) (*GetCloneTokenResponse, error)
}

type agentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentServiceClient(cc grpc.ClientConnInterface) AgentServiceClient {
	return &agentServiceClient{cc}
}

func (c *agentServiceClient) RegisterMachine(ctx context.Context, in *RegisterMachineRequest, opts ...grpc.CallOption) (*RegisterMachineResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterMachineResponse)
	err := c.cc.Invoke(ctx, AgentService_RegisterMachine_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) ClaimStep(ctx context.Context, in *ClaimStepRequest, opts ...grpc.CallOption) (*ClaimStepResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClaimStepResponse)
	err := c.cc.Invoke(ctx, AgentService_ClaimStep_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) ExecuteStep(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ExecuteStepRequest, ExecuteStepResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AgentService_ServiceDesc.Streams[0], AgentService_ExecuteStep_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ExecuteStepRequest, ExecuteStepResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentService_ExecuteStepClient = grpc.BidiStreamingClient[ExecuteStepRequest, ExecuteStepResponse]

func (c *agentServiceClient) ReportStepComplete(ctx context.Context, in *ReportStepCompleteRequest, opts ...grpc.CallOption) (*ReportStepCompleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReportStepCompleteResponse)
	err := c.cc.Invoke(ctx, AgentService_ReportStepComplete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HeartbeatResponse)
	err := c.cc.Invoke(ctx, AgentService_Heartbeat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) GetStepSecrets(ctx context.Context, in *GetStepSecretsRequest, opts ...grpc.CallOption) (*GetStepSecretsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetStepSecretsResponse)
	err := c.cc.Invoke(ctx, AgentService_GetStepSecrets_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) GetCloneToken(ctx context.Context, in *GetCloneTokenRequest, opts ...grpc.CallOption) (*GetCloneTokenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCloneTokenResponse)
	err := c.cc.Invoke(ctx, AgentService_GetCloneToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AgentServiceServer is the server API for AgentService service.
// All implementations must embed UnimplementedAgentServiceServer
// for forward compatibility.
//
// AgentService is the control-plane contract for the per-machine flint-agent
// daemon. The flow: a machine registers once (bootstrap or pool join token →
// per-machine bearer token), heartbeats every ~10s (lease keep-alive; drain/
// shutdown/cancel/GC signals piggyback on the response), long-polls ClaimStep
// for assigned work, streams logs over ExecuteStep while a step runs, and
// reports the outcome via ReportStepComplete (unary, so delivery survives a
// dropped stream).
//
// All RPCs except RegisterMachine authenticate with the machine bearer token
// (authorization: Bearer <token>). Data-plane pulls that carry a per-step task
// token (secrets, clone tokens) stay on the server's HTTP /internal endpoints.
type AgentServiceServer interface {
	// RegisterMachine exchanges a one-time bootstrap token (elastic machines,
	// minted at provider.Create) or a long-lived pool join token (static
	// machines) for the machine identity and bearer token.
	RegisterMachine(context.Context, *RegisterMachineRequest) (*RegisterMachineResponse, error)
	// ClaimStep long-polls for work assigned to this machine (the server parks
	// the call up to wait_seconds, woken by the scheduler). The agent calls it
	// once per free execution slot.
	ClaimStep(context.Context, *ClaimStepRequest) (*ClaimStepResponse, error)
	// ExecuteStep is a bidirectional stream for the lifetime of one step:
	// agent sends log batches / lifecycle updates, server sends cancellation.
	ExecuteStep(grpc.BidiStreamingServer[ExecuteStepRequest, ExecuteStepResponse]) error
	// ReportStepComplete is the final, task-token-authenticated completion
	// report. Unary and retried so the engine hears the outcome even if the
	// stream died. Carries the log digest for tail repair.
	ReportStepComplete(context.Context, *ReportStepCompleteRequest) (*ReportStepCompleteResponse, error)
	// Heartbeat keeps the machine's lease alive (~10s cadence; the server
	// expires machines at 3× the interval). The response is the server's
	// command channel: drain/shutdown, step cancellations, and workspace GC.
	Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error)
	// GetStepSecrets resolves a step's secret mapping at execution time. Pull
	// keeps secret values out of assignment payloads and the database: exposure
	// is bounded to the execution window, and the server re-checks that the
	// assignment is live and bound to the calling machine on every call.
	GetStepSecrets(context.Context, *GetStepSecretsRequest) (*GetStepSecretsResponse, error)
	// GetCloneToken mints a short-lived forge token for git operations
	// (mirror fetches, checkout) scoped to the step's repository.
	GetCloneToken(context.Context, *GetCloneTokenRequest) (*GetCloneTokenResponse, error)
	mustEmbedUnimplementedAgentServiceServer()
}

// UnimplementedAgentServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAgentServiceServer struct{}

func (UnimplementedAgentServiceServer) RegisterMachine(context.Context, *RegisterMachineRequest) (*RegisterMachineResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterMachine not implemented")
}
func (UnimplementedAgentServiceServer) ClaimStep(context.Context, *ClaimStepRequest) (*ClaimStepResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ClaimStep not implemented")
}
func (UnimplementedAgentServiceServer) ExecuteStep(grpc.BidiStreamingServer[ExecuteStepRequest, ExecuteStepResponse]) error {
	return status.Error(codes.Unimplemented, "method ExecuteStep not implemented")
}
func (UnimplementedAgentServiceServer) ReportStepComplete(context.Context, *ReportStepCompleteRequest) (*ReportStepCompleteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportStepComplete not implemented")
}
func (UnimplementedAgentServiceServer) Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Heartbeat not implemented")
}
func (UnimplementedAgentServiceServer) GetStepSecrets(context.Context, *GetStepSecretsRequest) (*GetStepSecretsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStepSecrets not implemented")
}
func (UnimplementedAgentServiceServer) GetCloneToken(context.Context, *GetCloneTokenRequest) (*GetCloneTokenResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCloneToken not implemented")
}
func (UnimplementedAgentServiceServer) mustEmbedUnimplementedAgentServiceServer() {}
func (UnimplementedAgentServiceServer) testEmbeddedByValue()                      {}

// UnsafeAgentServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentServiceServer will
// result in compilation errors.
type UnsafeAgentServiceServer interface {
	mustEmbedUnimplementedAgentServiceServer()
}

func RegisterAgentServiceServer(s grpc.ServiceRegistrar, srv AgentServiceServer) {
	// If the following call panics, it indicates UnimplementedAgentServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AgentService_ServiceDesc, srv)
}

func _AgentService_RegisterMachine_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterMachineRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).RegisterMachine(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_RegisterMachine_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).RegisterMachine(ctx, req.(*RegisterMachineRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_ClaimStep_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClaimStepRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).ClaimStep(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_ClaimStep_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).ClaimStep(ctx, req.(*ClaimStepRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_ExecuteStep_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AgentServiceServer).ExecuteStep(&grpc.GenericServerStream[ExecuteStepRequest, ExecuteStepResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentService_ExecuteStepServer = grpc.BidiStreamingServer[ExecuteStepRequest, ExecuteStepResponse]

func _AgentService_ReportStepComplete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReportStepCompleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).ReportStepComplete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_ReportStepComplete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).ReportStepComplete(ctx, req.(*ReportStepCompleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_Heartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HeartbeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).Heartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_Heartbeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).Heartbeat(ctx, req.(*HeartbeatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_GetStepSecrets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStepSecretsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).GetStepSecrets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_GetStepSecrets_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).GetStepSecrets(ctx, req.(*GetStepSecretsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_GetCloneToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCloneTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).GetCloneToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_GetCloneToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).GetCloneToken(ctx, req.(*GetCloneTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AgentService_ServiceDesc is the grpc.ServiceDesc for AgentService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AgentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "agent.v1.AgentService",
	HandlerType: (*AgentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterMachine",
			Handler:    _AgentService_RegisterMachine_Handler,
		},
		{
			MethodName: "ClaimStep",
			Handler:    _AgentService_ClaimStep_Handler,
		},
		{
			MethodName: "ReportStepComplete",
			Handler:    _AgentService_ReportStepComplete_Handler,
		},
		{
			MethodName: "Heartbeat",
			Handler:    _AgentService_Heartbeat_Handler,
		},
		{
			MethodName: "GetStepSecrets",
			Handler:    _AgentService_GetStepSecrets_Handler,
		},
		{
			MethodName: "GetCloneToken",
			Handler:    _AgentService_GetCloneToken_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ExecuteStep",
			Handler:       _AgentService_ExecuteStep_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "agent/v1/agent.proto",
}
