// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	logsink "github.com/NerdMeNot/flint/pkg/logsink"
	mock "github.com/stretchr/testify/mock"
)

// LogSink is an autogenerated mock type for the LogSink type
type LogSink struct {
	mock.Mock
}

// Read provides a mock function with given fields: ctx, ref
func (_m *LogSink) Read(ctx context.Context, ref logsink.LogRef) ([]logsink.LogLine, error) {
	ret := _m.Called(ctx, ref)

	if len(ret) == 0 {
		panic("no return value specified for Read")
	}

	var r0 []logsink.LogLine
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, logsink.LogRef) ([]logsink.LogLine, error)); ok {
		return rf(ctx, ref)
	}
	if rf, ok := ret.Get(0).(func(context.Context, logsink.LogRef) []logsink.LogLine); ok {
		r0 = rf(ctx, ref)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]logsink.LogLine)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, logsink.LogRef) error); ok {
		r1 = rf(ctx, ref)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Tail provides a mock function with given fields: ctx, ref
func (_m *LogSink) Tail(ctx context.Context, ref logsink.LogRef) (<-chan logsink.LogLine, error) {
	ret := _m.Called(ctx, ref)

	if len(ret) == 0 {
		panic("no return value specified for Tail")
	}

	var r0 <-chan logsink.LogLine
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, logsink.LogRef) (<-chan logsink.LogLine, error)); ok {
		return rf(ctx, ref)
	}
	if rf, ok := ret.Get(0).(func(context.Context, logsink.LogRef) <-chan logsink.LogLine); ok {
		r0 = rf(ctx, ref)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan logsink.LogLine)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, logsink.LogRef) error); ok {
		r1 = rf(ctx, ref)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Write provides a mock function with given fields: ctx, ref, lines
func (_m *LogSink) Write(ctx context.Context, ref logsink.LogRef, lines []logsink.LogLine) error {
	ret := _m.Called(ctx, ref, lines)

	if len(ret) == 0 {
		panic("no return value specified for Write")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, logsink.LogRef, []logsink.LogLine) error); ok {
		r0 = rf(ctx, ref, lines)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewLogSink creates a new instance of LogSink. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewLogSink(t interface {
	mock.TestingT
	Cleanup(func())
}) *LogSink {
	mock := &LogSink{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
