// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	auth "github.com/NerdMeNot/flint/internal/auth"
	mock "github.com/stretchr/testify/mock"
)

// SAMLAuth is an autogenerated mock type for the SAMLAuth type
type SAMLAuth struct {
	mock.Mock
}

// AuthURL provides a mock function with given fields: relayState
func (_m *SAMLAuth) AuthURL(relayState string) (string, error) {
	ret := _m.Called(relayState)

	if len(ret) == 0 {
		panic("no return value specified for AuthURL")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (string, error)); ok {
		return rf(relayState)
	}
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(relayState)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(relayState)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MetadataXML provides a mock function with no fields
func (_m *SAMLAuth) MetadataXML() ([]byte, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for MetadataXML")
	}

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]byte, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []byte); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ValidateResponse provides a mock function with given fields: samlResponse
func (_m *SAMLAuth) ValidateResponse(samlResponse string) (*auth.Claims, error) {
	ret := _m.Called(samlResponse)

	if len(ret) == 0 {
		panic("no return value specified for ValidateResponse")
	}

	var r0 *auth.Claims
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*auth.Claims, error)); ok {
		return rf(samlResponse)
	}
	if rf, ok := ret.Get(0).(func(string) *auth.Claims); ok {
		r0 = rf(samlResponse)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*auth.Claims)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(samlResponse)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewSAMLAuth creates a new instance of SAMLAuth. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSAMLAuth(t interface {
	mock.TestingT
	Cleanup(func())
}) *SAMLAuth {
	mock := &SAMLAuth{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
