/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TeamsRouteImport } from './routes/teams'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LoadtestRouteImport } from './routes/loadtest'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkflowsIndexRouteImport } from './routes/workflows.index'
import { Route as SettingsIndexRouteImport } from './routes/settings.index'
import { Route as CiIndexRouteImport } from './routes/ci.index'
import { Route as WorkflowsIdRouteImport } from './routes/workflows.$id'
import { Route as SettingsWorkspacesRouteImport } from './routes/settings.workspaces'
import { Route as SettingsVariablesRouteImport } from './routes/settings.variables'
import { Route as SettingsUsersRouteImport } from './routes/settings.users'
import { Route as SettingsTeamsRouteImport } from './routes/settings.teams'
import { Route as SettingsSsoRouteImport } from './routes/settings.sso'
import { Route as SettingsSessionsRouteImport } from './routes/settings.sessions'
import { Route as SettingsSecurityRouteImport } from './routes/settings.security'
import { Route as SettingsRunnersRouteImport } from './routes/settings.runners'
import { Route as SettingsRolesRouteImport } from './routes/settings.roles'
import { Route as SettingsEnvironmentsRouteImport } from './routes/settings.environments'
import { Route as SettingsConnectionsRouteImport } from './routes/settings.connections'
import { Route as SettingsAuditLogRouteImport } from './routes/settings.audit-log'
import { Route as SettingsApiKeysRouteImport } from './routes/settings.api-keys'
import { Route as CiProjectsRouteImport } from './routes/ci.projects'
import { Route as CiGatesRouteImport } from './routes/ci.gates'
import { Route as SettingsUsersIndexRouteImport } from './routes/settings.users.index'
import { Route as SettingsTeamsIndexRouteImport } from './routes/settings.teams.index'
import { Route as SettingsEnvironmentsIndexRouteImport } from './routes/settings.environments.index'
import { Route as CiRunsIndexRouteImport } from './routes/ci.runs.index'
import { Route as CiProjectsIndexRouteImport } from './routes/ci.projects.index'
import { Route as SettingsUsersIdRouteImport } from './routes/settings.users.$id'
import { Route as SettingsTeamsIdRouteImport } from './routes/settings.teams.$id'
import { Route as SettingsEnvironmentsIdRouteImport } from './routes/settings.environments.$id'
import { Route as CiRunsIdRouteImport } from './routes/ci.runs.$id'
import { Route as CiProjectsIdRouteImport } from './routes/ci.projects.$id'
import { Route as ApiRpcSplatRouteImport } from './routes/api/rpc.$'

const TeamsRoute = TeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LoadtestRoute = LoadtestRouteImport.update({
  id: '/loadtest',
  path: '/loadtest',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkflowsIndexRoute = WorkflowsIndexRouteImport.update({
  id: '/workflows/',
  path: '/workflows/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRoute,
} as any)
const CiIndexRoute = CiIndexRouteImport.update({
  id: '/ci/',
  path: '/ci/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkflowsIdRoute = WorkflowsIdRouteImport.update({
  id: '/workflows/$id',
  path: '/workflows/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsWorkspacesRoute = SettingsWorkspacesRouteImport.update({
  id: '/workspaces',
  path: '/workspaces',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsVariablesRoute = SettingsVariablesRouteImport.update({
  id: '/variables',
  path: '/variables',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsUsersRoute = SettingsUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsTeamsRoute = SettingsTeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsSsoRoute = SettingsSsoRouteImport.update({
  id: '/sso',
  path: '/sso',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsSessionsRoute = SettingsSessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsSecurityRoute = SettingsSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsRunnersRoute = SettingsRunnersRouteImport.update({
  id: '/runners',
  path: '/runners',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsRolesRoute = SettingsRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsEnvironmentsRoute = SettingsEnvironmentsRouteImport.update({
  id: '/environments',
  path: '/environments',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsConnectionsRoute = SettingsConnectionsRouteImport.update({
  id: '/connections',
  path: '/connections',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsAuditLogRoute = SettingsAuditLogRouteImport.update({
  id: '/audit-log',
  path: '/audit-log',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsApiKeysRoute = SettingsApiKeysRouteImport.update({
  id: '/api-keys',
  path: '/api-keys',
  getParentRoute: () => SettingsRoute,
} as any)
const CiProjectsRoute = CiProjectsRouteImport.update({
  id: '/ci/projects',
  path: '/ci/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const CiGatesRoute = CiGatesRouteImport.update({
  id: '/ci/gates',
  path: '/ci/gates',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsUsersIndexRoute = SettingsUsersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsUsersRoute,
} as any)
const SettingsTeamsIndexRoute = SettingsTeamsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsTeamsRoute,
} as any)
const SettingsEnvironmentsIndexRoute =
  SettingsEnvironmentsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => SettingsEnvironmentsRoute,
  } as any)
const CiRunsIndexRoute = CiRunsIndexRouteImport.update({
  id: '/ci/runs/',
  path: '/ci/runs/',
  getParentRoute: () => rootRouteImport,
} as any)
const CiProjectsIndexRoute = CiProjectsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CiProjectsRoute,
} as any)
const SettingsUsersIdRoute = SettingsUsersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => SettingsUsersRoute,
} as any)
const SettingsTeamsIdRoute = SettingsTeamsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => SettingsTeamsRoute,
} as any)
const SettingsEnvironmentsIdRoute = SettingsEnvironmentsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => SettingsEnvironmentsRoute,
} as any)
const CiRunsIdRoute = CiRunsIdRouteImport.update({
  id: '/ci/runs/$id',
  path: '/ci/runs/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CiProjectsIdRoute = CiProjectsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => CiProjectsRoute,
} as any)
const ApiRpcSplatRoute = ApiRpcSplatRouteImport.update({
  id: '/api/rpc/$',
  path: '/api/rpc/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/loadtest': typeof LoadtestRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRouteWithChildren
  '/teams': typeof TeamsRoute
  '/ci/gates': typeof CiGatesRoute
  '/ci/projects': typeof CiProjectsRouteWithChildren
  '/settings/api-keys': typeof SettingsApiKeysRoute
  '/settings/audit-log': typeof SettingsAuditLogRoute
  '/settings/connections': typeof SettingsConnectionsRoute
  '/settings/environments': typeof SettingsEnvironmentsRouteWithChildren
  '/settings/roles': typeof SettingsRolesRoute
  '/settings/runners': typeof SettingsRunnersRoute
  '/settings/security': typeof SettingsSecurityRoute
  '/settings/sessions': typeof SettingsSessionsRoute
  '/settings/sso': typeof SettingsSsoRoute
  '/settings/teams': typeof SettingsTeamsRouteWithChildren
  '/settings/users': typeof SettingsUsersRouteWithChildren
  '/settings/variables': typeof SettingsVariablesRoute
  '/settings/workspaces': typeof SettingsWorkspacesRoute
  '/workflows/$id': typeof WorkflowsIdRoute
  '/ci/': typeof CiIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/workflows/': typeof WorkflowsIndexRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/ci/projects/$id': typeof CiProjectsIdRoute
  '/ci/runs/$id': typeof CiRunsIdRoute
  '/settings/environments/$id': typeof SettingsEnvironmentsIdRoute
  '/settings/teams/$id': typeof SettingsTeamsIdRoute
  '/settings/users/$id': typeof SettingsUsersIdRoute
  '/ci/projects/': typeof CiProjectsIndexRoute
  '/ci/runs/': typeof CiRunsIndexRoute
  '/settings/environments/': typeof SettingsEnvironmentsIndexRoute
  '/settings/teams/': typeof SettingsTeamsIndexRoute
  '/settings/users/': typeof SettingsUsersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/loadtest': typeof LoadtestRoute
  '/login': typeof LoginRoute
  '/teams': typeof TeamsRoute
  '/ci/gates': typeof CiGatesRoute
  '/settings/api-keys': typeof SettingsApiKeysRoute
  '/settings/audit-log': typeof SettingsAuditLogRoute
  '/settings/connections': typeof SettingsConnectionsRoute
  '/settings/roles': typeof SettingsRolesRoute
  '/settings/runners': typeof SettingsRunnersRoute
  '/settings/security': typeof SettingsSecurityRoute
  '/settings/sessions': typeof SettingsSessionsRoute
  '/settings/sso': typeof SettingsSsoRoute
  '/settings/variables': typeof SettingsVariablesRoute
  '/settings/workspaces': typeof SettingsWorkspacesRoute
  '/workflows/$id': typeof WorkflowsIdRoute
  '/ci': typeof CiIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/workflows': typeof WorkflowsIndexRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/ci/projects/$id': typeof CiProjectsIdRoute
  '/ci/runs/$id': typeof CiRunsIdRoute
  '/settings/environments/$id': typeof SettingsEnvironmentsIdRoute
  '/settings/teams/$id': typeof SettingsTeamsIdRoute
  '/settings/users/$id': typeof SettingsUsersIdRoute
  '/ci/projects': typeof CiProjectsIndexRoute
  '/ci/runs': typeof CiRunsIndexRoute
  '/settings/environments': typeof SettingsEnvironmentsIndexRoute
  '/settings/teams': typeof SettingsTeamsIndexRoute
  '/settings/users': typeof SettingsUsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/loadtest': typeof LoadtestRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRouteWithChildren
  '/teams': typeof TeamsRoute
  '/ci/gates': typeof CiGatesRoute
  '/ci/projects': typeof CiProjectsRouteWithChildren
  '/settings/api-keys': typeof SettingsApiKeysRoute
  '/settings/audit-log': typeof SettingsAuditLogRoute
  '/settings/connections': typeof SettingsConnectionsRoute
  '/settings/environments': typeof SettingsEnvironmentsRouteWithChildren
  '/settings/roles': typeof SettingsRolesRoute
  '/settings/runners': typeof SettingsRunnersRoute
  '/settings/security': typeof SettingsSecurityRoute
  '/settings/sessions': typeof SettingsSessionsRoute
  '/settings/sso': typeof SettingsSsoRoute
  '/settings/teams': typeof SettingsTeamsRouteWithChildren
  '/settings/users': typeof SettingsUsersRouteWithChildren
  '/settings/variables': typeof SettingsVariablesRoute
  '/settings/workspaces': typeof SettingsWorkspacesRoute
  '/workflows/$id': typeof WorkflowsIdRoute
  '/ci/': typeof CiIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/workflows/': typeof WorkflowsIndexRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/ci/projects/$id': typeof CiProjectsIdRoute
  '/ci/runs/$id': typeof CiRunsIdRoute
  '/settings/environments/$id': typeof SettingsEnvironmentsIdRoute
  '/settings/teams/$id': typeof SettingsTeamsIdRoute
  '/settings/users/$id': typeof SettingsUsersIdRoute
  '/ci/projects/': typeof CiProjectsIndexRoute
  '/ci/runs/': typeof CiRunsIndexRoute
  '/settings/environments/': typeof SettingsEnvironmentsIndexRoute
  '/settings/teams/': typeof SettingsTeamsIndexRoute
  '/settings/users/': typeof SettingsUsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/loadtest'
    | '/login'
    | '/settings'
    | '/teams'
    | '/ci/gates'
    | '/ci/projects'
    | '/settings/api-keys'
    | '/settings/audit-log'
    | '/settings/connections'
    | '/settings/environments'
    | '/settings/roles'
    | '/settings/runners'
    | '/settings/security'
    | '/settings/sessions'
    | '/settings/sso'
    | '/settings/teams'
    | '/settings/users'
    | '/settings/variables'
    | '/settings/workspaces'
    | '/workflows/$id'
    | '/ci/'
    | '/settings/'
    | '/workflows/'
    | '/api/rpc/$'
    | '/ci/projects/$id'
    | '/ci/runs/$id'
    | '/settings/environments/$id'
    | '/settings/teams/$id'
    | '/settings/users/$id'
    | '/ci/projects/'
    | '/ci/runs/'
    | '/settings/environments/'
    | '/settings/teams/'
    | '/settings/users/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/loadtest'
    | '/login'
    | '/teams'
    | '/ci/gates'
    | '/settings/api-keys'
    | '/settings/audit-log'
    | '/settings/connections'
    | '/settings/roles'
    | '/settings/runners'
    | '/settings/security'
    | '/settings/sessions'
    | '/settings/sso'
    | '/settings/variables'
    | '/settings/workspaces'
    | '/workflows/$id'
    | '/ci'
    | '/settings'
    | '/workflows'
    | '/api/rpc/$'
    | '/ci/projects/$id'
    | '/ci/runs/$id'
    | '/settings/environments/$id'
    | '/settings/teams/$id'
    | '/settings/users/$id'
    | '/ci/projects'
    | '/ci/runs'
    | '/settings/environments'
    | '/settings/teams'
    | '/settings/users'
  id:
    | '__root__'
    | '/'
    | '/loadtest'
    | '/login'
    | '/settings'
    | '/teams'
    | '/ci/gates'
    | '/ci/projects'
    | '/settings/api-keys'
    | '/settings/audit-log'
    | '/settings/connections'
    | '/settings/environments'
    | '/settings/roles'
    | '/settings/runners'
    | '/settings/security'
    | '/settings/sessions'
    | '/settings/sso'
    | '/settings/teams'
    | '/settings/users'
    | '/settings/variables'
    | '/settings/workspaces'
    | '/workflows/$id'
    | '/ci/'
    | '/settings/'
    | '/workflows/'
    | '/api/rpc/$'
    | '/ci/projects/$id'
    | '/ci/runs/$id'
    | '/settings/environments/$id'
    | '/settings/teams/$id'
    | '/settings/users/$id'
    | '/ci/projects/'
    | '/ci/runs/'
    | '/settings/environments/'
    | '/settings/teams/'
    | '/settings/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoadtestRoute: typeof LoadtestRoute
  LoginRoute: typeof LoginRoute
  SettingsRoute: typeof SettingsRouteWithChildren
  TeamsRoute: typeof TeamsRoute
  CiGatesRoute: typeof CiGatesRoute
  CiProjectsRoute: typeof CiProjectsRouteWithChildren
  WorkflowsIdRoute: typeof WorkflowsIdRoute
  CiIndexRoute: typeof CiIndexRoute
  WorkflowsIndexRoute: typeof WorkflowsIndexRoute
  ApiRpcSplatRoute: typeof ApiRpcSplatRoute
  CiRunsIdRoute: typeof CiRunsIdRoute
  CiRunsIndexRoute: typeof CiRunsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/teams': {
      id: '/teams'
      path: '/teams'
      fullPath: '/teams'
      preLoaderRoute: typeof TeamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loadtest': {
      id: '/loadtest'
      path: '/loadtest'
      fullPath: '/loadtest'
      preLoaderRoute: typeof LoadtestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflows/': {
      id: '/workflows/'
      path: '/workflows'
      fullPath: '/workflows/'
      preLoaderRoute: typeof WorkflowsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/ci/': {
      id: '/ci/'
      path: '/ci'
      fullPath: '/ci/'
      preLoaderRoute: typeof CiIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflows/$id': {
      id: '/workflows/$id'
      path: '/workflows/$id'
      fullPath: '/workflows/$id'
      preLoaderRoute: typeof WorkflowsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/workspaces': {
      id: '/settings/workspaces'
      path: '/workspaces'
      fullPath: '/settings/workspaces'
      preLoaderRoute: typeof SettingsWorkspacesRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/variables': {
      id: '/settings/variables'
      path: '/variables'
      fullPath: '/settings/variables'
      preLoaderRoute: typeof SettingsVariablesRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/users': {
      id: '/settings/users'
      path: '/users'
      fullPath: '/settings/users'
      preLoaderRoute: typeof SettingsUsersRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/teams': {
      id: '/settings/teams'
      path: '/teams'
      fullPath: '/settings/teams'
      preLoaderRoute: typeof SettingsTeamsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/sso': {
      id: '/settings/sso'
      path: '/sso'
      fullPath: '/settings/sso'
      preLoaderRoute: typeof SettingsSsoRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/sessions': {
      id: '/settings/sessions'
      path: '/sessions'
      fullPath: '/settings/sessions'
      preLoaderRoute: typeof SettingsSessionsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/security': {
      id: '/settings/security'
      path: '/security'
      fullPath: '/settings/security'
      preLoaderRoute: typeof SettingsSecurityRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/runners': {
      id: '/settings/runners'
      path: '/runners'
      fullPath: '/settings/runners'
      preLoaderRoute: typeof SettingsRunnersRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/roles': {
      id: '/settings/roles'
      path: '/roles'
      fullPath: '/settings/roles'
      preLoaderRoute: typeof SettingsRolesRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/environments': {
      id: '/settings/environments'
      path: '/environments'
      fullPath: '/settings/environments'
      preLoaderRoute: typeof SettingsEnvironmentsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/connections': {
      id: '/settings/connections'
      path: '/connections'
      fullPath: '/settings/connections'
      preLoaderRoute: typeof SettingsConnectionsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/audit-log': {
      id: '/settings/audit-log'
      path: '/audit-log'
      fullPath: '/settings/audit-log'
      preLoaderRoute: typeof SettingsAuditLogRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/api-keys': {
      id: '/settings/api-keys'
      path: '/api-keys'
      fullPath: '/settings/api-keys'
      preLoaderRoute: typeof SettingsApiKeysRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/ci/projects': {
      id: '/ci/projects'
      path: '/ci/projects'
      fullPath: '/ci/projects'
      preLoaderRoute: typeof CiProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ci/gates': {
      id: '/ci/gates'
      path: '/ci/gates'
      fullPath: '/ci/gates'
      preLoaderRoute: typeof CiGatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/users/': {
      id: '/settings/users/'
      path: '/'
      fullPath: '/settings/users/'
      preLoaderRoute: typeof SettingsUsersIndexRouteImport
      parentRoute: typeof SettingsUsersRoute
    }
    '/settings/teams/': {
      id: '/settings/teams/'
      path: '/'
      fullPath: '/settings/teams/'
      preLoaderRoute: typeof SettingsTeamsIndexRouteImport
      parentRoute: typeof SettingsTeamsRoute
    }
    '/settings/environments/': {
      id: '/settings/environments/'
      path: '/'
      fullPath: '/settings/environments/'
      preLoaderRoute: typeof SettingsEnvironmentsIndexRouteImport
      parentRoute: typeof SettingsEnvironmentsRoute
    }
    '/ci/runs/': {
      id: '/ci/runs/'
      path: '/ci/runs'
      fullPath: '/ci/runs/'
      preLoaderRoute: typeof CiRunsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ci/projects/': {
      id: '/ci/projects/'
      path: '/'
      fullPath: '/ci/projects/'
      preLoaderRoute: typeof CiProjectsIndexRouteImport
      parentRoute: typeof CiProjectsRoute
    }
    '/settings/users/$id': {
      id: '/settings/users/$id'
      path: '/$id'
      fullPath: '/settings/users/$id'
      preLoaderRoute: typeof SettingsUsersIdRouteImport
      parentRoute: typeof SettingsUsersRoute
    }
    '/settings/teams/$id': {
      id: '/settings/teams/$id'
      path: '/$id'
      fullPath: '/settings/teams/$id'
      preLoaderRoute: typeof SettingsTeamsIdRouteImport
      parentRoute: typeof SettingsTeamsRoute
    }
    '/settings/environments/$id': {
      id: '/settings/environments/$id'
      path: '/$id'
      fullPath: '/settings/environments/$id'
      preLoaderRoute: typeof SettingsEnvironmentsIdRouteImport
      parentRoute: typeof SettingsEnvironmentsRoute
    }
    '/ci/runs/$id': {
      id: '/ci/runs/$id'
      path: '/ci/runs/$id'
      fullPath: '/ci/runs/$id'
      preLoaderRoute: typeof CiRunsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ci/projects/$id': {
      id: '/ci/projects/$id'
      path: '/$id'
      fullPath: '/ci/projects/$id'
      preLoaderRoute: typeof CiProjectsIdRouteImport
      parentRoute: typeof CiProjectsRoute
    }
    '/api/rpc/$': {
      id: '/api/rpc/$'
      path: '/api/rpc/$'
      fullPath: '/api/rpc/$'
      preLoaderRoute: typeof ApiRpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface SettingsEnvironmentsRouteChildren {
  SettingsEnvironmentsIdRoute: typeof SettingsEnvironmentsIdRoute
  SettingsEnvironmentsIndexRoute: typeof SettingsEnvironmentsIndexRoute
}

const SettingsEnvironmentsRouteChildren: SettingsEnvironmentsRouteChildren = {
  SettingsEnvironmentsIdRoute: SettingsEnvironmentsIdRoute,
  SettingsEnvironmentsIndexRoute: SettingsEnvironmentsIndexRoute,
}

const SettingsEnvironmentsRouteWithChildren =
  SettingsEnvironmentsRoute._addFileChildren(SettingsEnvironmentsRouteChildren)

interface SettingsTeamsRouteChildren {
  SettingsTeamsIdRoute: typeof SettingsTeamsIdRoute
  SettingsTeamsIndexRoute: typeof SettingsTeamsIndexRoute
}

const SettingsTeamsRouteChildren: SettingsTeamsRouteChildren = {
  SettingsTeamsIdRoute: SettingsTeamsIdRoute,
  SettingsTeamsIndexRoute: SettingsTeamsIndexRoute,
}

const SettingsTeamsRouteWithChildren = SettingsTeamsRoute._addFileChildren(
  SettingsTeamsRouteChildren,
)

interface SettingsUsersRouteChildren {
  SettingsUsersIdRoute: typeof SettingsUsersIdRoute
  SettingsUsersIndexRoute: typeof SettingsUsersIndexRoute
}

const SettingsUsersRouteChildren: SettingsUsersRouteChildren = {
  SettingsUsersIdRoute: SettingsUsersIdRoute,
  SettingsUsersIndexRoute: SettingsUsersIndexRoute,
}

const SettingsUsersRouteWithChildren = SettingsUsersRoute._addFileChildren(
  SettingsUsersRouteChildren,
)

interface SettingsRouteChildren {
  SettingsApiKeysRoute: typeof SettingsApiKeysRoute
  SettingsAuditLogRoute: typeof SettingsAuditLogRoute
  SettingsConnectionsRoute: typeof SettingsConnectionsRoute
  SettingsEnvironmentsRoute: typeof SettingsEnvironmentsRouteWithChildren
  SettingsRolesRoute: typeof SettingsRolesRoute
  SettingsRunnersRoute: typeof SettingsRunnersRoute
  SettingsSecurityRoute: typeof SettingsSecurityRoute
  SettingsSessionsRoute: typeof SettingsSessionsRoute
  SettingsSsoRoute: typeof SettingsSsoRoute
  SettingsTeamsRoute: typeof SettingsTeamsRouteWithChildren
  SettingsUsersRoute: typeof SettingsUsersRouteWithChildren
  SettingsVariablesRoute: typeof SettingsVariablesRoute
  SettingsWorkspacesRoute: typeof SettingsWorkspacesRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsApiKeysRoute: SettingsApiKeysRoute,
  SettingsAuditLogRoute: SettingsAuditLogRoute,
  SettingsConnectionsRoute: SettingsConnectionsRoute,
  SettingsEnvironmentsRoute: SettingsEnvironmentsRouteWithChildren,
  SettingsRolesRoute: SettingsRolesRoute,
  SettingsRunnersRoute: SettingsRunnersRoute,
  SettingsSecurityRoute: SettingsSecurityRoute,
  SettingsSessionsRoute: SettingsSessionsRoute,
  SettingsSsoRoute: SettingsSsoRoute,
  SettingsTeamsRoute: SettingsTeamsRouteWithChildren,
  SettingsUsersRoute: SettingsUsersRouteWithChildren,
  SettingsVariablesRoute: SettingsVariablesRoute,
  SettingsWorkspacesRoute: SettingsWorkspacesRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

interface CiProjectsRouteChildren {
  CiProjectsIdRoute: typeof CiProjectsIdRoute
  CiProjectsIndexRoute: typeof CiProjectsIndexRoute
}

const CiProjectsRouteChildren: CiProjectsRouteChildren = {
  CiProjectsIdRoute: CiProjectsIdRoute,
  CiProjectsIndexRoute: CiProjectsIndexRoute,
}

const CiProjectsRouteWithChildren = CiProjectsRoute._addFileChildren(
  CiProjectsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoadtestRoute: LoadtestRoute,
  LoginRoute: LoginRoute,
  SettingsRoute: SettingsRouteWithChildren,
  TeamsRoute: TeamsRoute,
  CiGatesRoute: CiGatesRoute,
  CiProjectsRoute: CiProjectsRouteWithChildren,
  WorkflowsIdRoute: WorkflowsIdRoute,
  CiIndexRoute: CiIndexRoute,
  WorkflowsIndexRoute: WorkflowsIndexRoute,
  ApiRpcSplatRoute: ApiRpcSplatRoute,
  CiRunsIdRoute: CiRunsIdRoute,
  CiRunsIndexRoute: CiRunsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
