// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: audit_log.sql

package db

import (
	"context"
	"net/netip"
	"time"
)

const insertAuditEntry = `-- name: InsertAuditEntry :exec
INSERT INTO audit_log (org_id, user_id, action, resource_type, resource_id, ip_address)
VALUES ($1, $2, $3, $4, $5, $6::inet)
`

type InsertAuditEntryParams struct {
	OrgID        string     `json:"org_id"`
	UserID       *string    `json:"user_id"`
	Action       string     `json:"action"`
	ResourceType string     `json:"resource_type"`
	ResourceID   *string    `json:"resource_id"`
	Column6      netip.Addr `json:"column_6"`
}

func (q *Queries) InsertAuditEntry(ctx context.Context, arg InsertAuditEntryParams) error {
	_, err := q.db.Exec(ctx, insertAuditEntry,
		arg.OrgID,
		arg.UserID,
		arg.Action,
		arg.ResourceType,
		arg.ResourceID,
		arg.Column6,
	)
	return err
}

const listAuditLog = `-- name: ListAuditLog :many
SELECT al.id, al.user_id, u.email AS user_email, al.action, al.resource_type,
       al.resource_id, al.metadata, al.ip_address, al.created_at
FROM audit_log al
LEFT JOIN users u ON al.user_id = u.id
WHERE al.org_id = $1
  AND ($3::text IS NULL OR al.action = $3)
ORDER BY al.created_at DESC
LIMIT $2
`

type ListAuditLogParams struct {
	OrgID  string  `json:"org_id"`
	Limit  int32   `json:"limit"`
	Action *string `json:"action"`
}

type ListAuditLogRow struct {
	ID           string    `json:"id"`
	UserID       *string   `json:"user_id"`
	UserEmail    *string   `json:"user_email"`
	Action       string    `json:"action"`
	ResourceType string    `json:"resource_type"`
	ResourceID   *string   `json:"resource_id"`
	Metadata     []byte    `json:"metadata"`
	IpAddress    *string   `json:"ip_address"`
	CreatedAt    time.Time `json:"created_at"`
}

func (q *Queries) ListAuditLog(ctx context.Context, arg ListAuditLogParams) ([]ListAuditLogRow, error) {
	rows, err := q.db.Query(ctx, listAuditLog, arg.OrgID, arg.Limit, arg.Action)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAuditLogRow{}
	for rows.Next() {
		var i ListAuditLogRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.UserEmail,
			&i.Action,
			&i.ResourceType,
			&i.ResourceID,
			&i.Metadata,
			&i.IpAddress,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
