// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: forge_connections.sql

package db

import (
	"context"
	"time"
)

const deleteForgeConnection = `-- name: DeleteForgeConnection :execrows
DELETE FROM forge_connections WHERE id = $1
`

func (q *Queries) DeleteForgeConnection(ctx context.Context, id string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteForgeConnection, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteForgeConnectionByID = `-- name: DeleteForgeConnectionByID :exec
DELETE FROM forge_connections WHERE id = $1
`

func (q *Queries) DeleteForgeConnectionByID(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteForgeConnectionByID, id)
	return err
}

const getCloneCredentials = `-- name: GetCloneCredentials :one
SELECT fc.forge_type, fc.credentials_enc
FROM projects p
JOIN forge_connections fc ON p.forge_id = fc.id
WHERE p.repo_path = $1 AND p.is_archived = false
LIMIT 1
`

type GetCloneCredentialsRow struct {
	ForgeType      string `json:"forge_type"`
	CredentialsEnc []byte `json:"credentials_enc"`
}

func (q *Queries) GetCloneCredentials(ctx context.Context, repoPath string) (GetCloneCredentialsRow, error) {
	row := q.db.QueryRow(ctx, getCloneCredentials, repoPath)
	var i GetCloneCredentialsRow
	err := row.Scan(&i.ForgeType, &i.CredentialsEnc)
	return i, err
}

const getWebhookSecret = `-- name: GetWebhookSecret :one
SELECT webhook_secret FROM forge_connections WHERE forge_type = $1 LIMIT 1
`

func (q *Queries) GetWebhookSecret(ctx context.Context, forgeType string) (string, error) {
	row := q.db.QueryRow(ctx, getWebhookSecret, forgeType)
	var webhook_secret string
	err := row.Scan(&webhook_secret)
	return webhook_secret, err
}

const getWebhookSecretByName = `-- name: GetWebhookSecretByName :one
SELECT webhook_secret FROM forge_connections WHERE display_name = $1 LIMIT 1
`

func (q *Queries) GetWebhookSecretByName(ctx context.Context, displayName string) (string, error) {
	row := q.db.QueryRow(ctx, getWebhookSecretByName, displayName)
	var webhook_secret string
	err := row.Scan(&webhook_secret)
	return webhook_secret, err
}

const insertForgeConnection = `-- name: InsertForgeConnection :one
INSERT INTO forge_connections (org_id, forge_type, display_name, webhook_secret, credentials_enc)
VALUES (
    (SELECT id FROM orgs LIMIT 1),
    $1, $2, $3, $4
)
RETURNING id
`

type InsertForgeConnectionParams struct {
	ForgeType      string `json:"forge_type"`
	DisplayName    string `json:"display_name"`
	WebhookSecret  string `json:"webhook_secret"`
	CredentialsEnc []byte `json:"credentials_enc"`
}

func (q *Queries) InsertForgeConnection(ctx context.Context, arg InsertForgeConnectionParams) (string, error) {
	row := q.db.QueryRow(ctx, insertForgeConnection,
		arg.ForgeType,
		arg.DisplayName,
		arg.WebhookSecret,
		arg.CredentialsEnc,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}

const listForgeConnectionNames = `-- name: ListForgeConnectionNames :many
SELECT id, display_name FROM forge_connections
`

type ListForgeConnectionNamesRow struct {
	ID          string `json:"id"`
	DisplayName string `json:"display_name"`
}

func (q *Queries) ListForgeConnectionNames(ctx context.Context) ([]ListForgeConnectionNamesRow, error) {
	rows, err := q.db.Query(ctx, listForgeConnectionNames)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListForgeConnectionNamesRow{}
	for rows.Next() {
		var i ListForgeConnectionNamesRow
		if err := rows.Scan(&i.ID, &i.DisplayName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listForgeConnections = `-- name: ListForgeConnections :many
SELECT id, forge_type, display_name, app_id, installation_id, created_at
FROM forge_connections WHERE org_id = $1 ORDER BY created_at
`

type ListForgeConnectionsRow struct {
	ID             string    `json:"id"`
	ForgeType      string    `json:"forge_type"`
	DisplayName    string    `json:"display_name"`
	AppID          *string   `json:"app_id"`
	InstallationID *string   `json:"installation_id"`
	CreatedAt      time.Time `json:"created_at"`
}

func (q *Queries) ListForgeConnections(ctx context.Context, orgID string) ([]ListForgeConnectionsRow, error) {
	rows, err := q.db.Query(ctx, listForgeConnections, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListForgeConnectionsRow{}
	for rows.Next() {
		var i ListForgeConnectionsRow
		if err := rows.Scan(
			&i.ID,
			&i.ForgeType,
			&i.DisplayName,
			&i.AppID,
			&i.InstallationID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateForgeConnectionByName = `-- name: UpdateForgeConnectionByName :one
UPDATE forge_connections
SET forge_type = $1, display_name = $2, webhook_secret = $3, credentials_enc = $4
WHERE display_name = $5
RETURNING id
`

type UpdateForgeConnectionByNameParams struct {
	ForgeType      string `json:"forge_type"`
	DisplayName    string `json:"display_name"`
	WebhookSecret  string `json:"webhook_secret"`
	CredentialsEnc []byte `json:"credentials_enc"`
	DisplayName_2  string `json:"display_name_2"`
}

func (q *Queries) UpdateForgeConnectionByName(ctx context.Context, arg UpdateForgeConnectionByNameParams) (string, error) {
	row := q.db.QueryRow(ctx, updateForgeConnectionByName,
		arg.ForgeType,
		arg.DisplayName,
		arg.WebhookSecret,
		arg.CredentialsEnc,
		arg.DisplayName_2,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}
