// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package db

import (
	"context"
	"time"
)

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, external_id, name FROM users
WHERE org_id = $1 AND email = $2
`

type GetUserByEmailParams struct {
	OrgID string `json:"org_id"`
	Email string `json:"email"`
}

type GetUserByEmailRow struct {
	ID         string  `json:"id"`
	Email      string  `json:"email"`
	ExternalID string  `json:"external_id"`
	Name       *string `json:"name"`
}

func (q *Queries) GetUserByEmail(ctx context.Context, arg GetUserByEmailParams) (GetUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, arg.OrgID, arg.Email)
	var i GetUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.ExternalID,
		&i.Name,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, email, name, avatar_url, created_at
FROM users WHERE org_id = $1
ORDER BY name LIMIT 100
`

type ListUsersRow struct {
	ID        string    `json:"id"`
	Email     string    `json:"email"`
	Name      *string   `json:"name"`
	AvatarUrl *string   `json:"avatar_url"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) ListUsers(ctx context.Context, orgID string) ([]ListUsersRow, error) {
	rows, err := q.db.Query(ctx, listUsers, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUsersRow{}
	for rows.Next() {
		var i ListUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Name,
			&i.AvatarUrl,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchUsers = `-- name: SearchUsers :many
SELECT id, email, name, avatar_url, created_at
FROM users WHERE org_id = $1 AND (email ILIKE $2 OR name ILIKE $2)
ORDER BY name LIMIT 100
`

type SearchUsersParams struct {
	OrgID string `json:"org_id"`
	Email string `json:"email"`
}

type SearchUsersRow struct {
	ID        string    `json:"id"`
	Email     string    `json:"email"`
	Name      *string   `json:"name"`
	AvatarUrl *string   `json:"avatar_url"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) SearchUsers(ctx context.Context, arg SearchUsersParams) ([]SearchUsersRow, error) {
	rows, err := q.db.Query(ctx, searchUsers, arg.OrgID, arg.Email)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchUsersRow{}
	for rows.Next() {
		var i SearchUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Name,
			&i.AvatarUrl,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertUser = `-- name: UpsertUser :one
INSERT INTO users (org_id, email, external_id, name)
VALUES ($1, $2, $3, $4)
ON CONFLICT (org_id, external_id) DO UPDATE SET
    email = EXCLUDED.email, name = EXCLUDED.name
RETURNING id
`

type UpsertUserParams struct {
	OrgID      string  `json:"org_id"`
	Email      string  `json:"email"`
	ExternalID string  `json:"external_id"`
	Name       *string `json:"name"`
}

func (q *Queries) UpsertUser(ctx context.Context, arg UpsertUserParams) (string, error) {
	row := q.db.QueryRow(ctx, upsertUser,
		arg.OrgID,
		arg.Email,
		arg.ExternalID,
		arg.Name,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}
